### PR TITLE
Making small changes to the PyGRB result page.

### PR DESCRIPTION
**Pull request by a-r-williamson**
Hi @sfairhur ,

These are a few minor tweaks to the result page we've spoken about recently. For an example see
[here](https://geo2.arcca.cf.ac.uk/~c1239174/LVC/ER8/pygrb/GRB150919A/GRB150919A_CLOSED_FVCRZH8I/summary.html).

Andrew

### CODE REVIEW

**Comment by pannarale** [comment]
Hi @a-r-williamson,

Could you include all 6 injected spin components in the [missed injection tables](https://geo2.arcca.cf.ac.uk/~c1239174/LVC/ER8/pygrb/GRB150919A/GRB150919A_CLOSED_FVCRZH8I/NSBHPRECESS_FILTERED_30/efficiency_OFFTRIAL_1/quiet_found_triggers.html)?

Francesco

**Comment by a-r-williamson** [comment]
I see these values at the far right of that table.

**Comment by pannarale** [comment]
Recovered spin components, sorry.

**Comment by a-r-williamson** [comment]
Ok, I'll do that. That change comes in `pylal_cbc_cohptf_efficiency` though, so doesn't affect this pull request.

**Pull request merged**
