### PR TITLE
template duration

### PR DESCRIPTION
**Pull request by ahnitz**
Add template duration to the hdf files. This adds it to the direct inspiral hdf output and also to the xml -> hdf conversion script, which is invoked if you are running the standard pycbc_make_coinc_workflow, instead of pycbc_make_hdf_coinc_workflow.

### CODE REVIEW

**Comment by titodalcanton** [comment]
Wouldn't it make more sense to have the template duration in the bank HDF file instead?

**Comment by tdent** [comment]
Hi Tito -

the template duration is calculated from the lower matched filter frequency cutoff to max amplitude/merger, but the bank may not know about the lower cutoff used for matched filtering.  So the default is to have the matched filter code fill the column. 

Cheers Tom
--
-----------------------------------------
Institute for Gravitational Physics
(Albert Einstein Institute)
Callinstr. 38 
D-30167 Hannover, Germany

**Comment by ahnitz** [comment]
Had to add a small change. I forgot to resort the template durations by the template_id associated with the triggers themselves in the direct HDF inspiral output. This would not affect the xml -> hdf output if you use that path.

**Comment by tdent** [comment]
looks OK - have merged from the browser, hopefully that worked

**Pull request merged**
