### PR TITLE
Implementing two stage clustering for PyGRB

### PR DESCRIPTION
**Pull request by a-r-williamson**
This change will allow for a 2-stage clustering in the PyGRB workflow, to hopefully reduce the memory load involved at this stage, which is currently a big bottleneck (particularly in the online).

This requires using a slightly modified version of `trig_combiner` (see ligo-cbc/pycbc-pylal#35).

This method of clustering can be invoked by adding the following to the configuration files:
```
[workflow-postproc]
postproc-method = COH_PTF_ONLINE
do-two-stage-clustering =
num-stage-one-cluster-jobs = 20
```
I should note that the first argument selects a workflow that allows for two stage clustering *and* also neglects to do `sbv_plotter` jobs on unclustered triggers (these were also high memory load jobs). The second argument is what diverts to a two-stage clustering path, and the third sets how chopped up the triggers are for stage one.

I'll begin addressing the code quality issues when I get a chance. In the mean time, what do folks think about this change?

### CODE REVIEW

**Comment by spxiwh** [comment]
Have you considered converting to a HDF file format before doing the trig_combiner stage (or doing trig_combiner directly into HDF?) Trig_cluster only needs a small subsection of the data to do clustering, which HDF will easily allow you to access (ie. end time and "bestnr"). This would decrease the memory footprint of clustering by a factor of 50 over the XML files.

One landscape-related comment. You are getting warnings about:
```
workflow._adag.addDependency(dep)
```
a lot. Now there are cases where we should use this, and this should probably be exposed as not a "protected" attribute, but if you tell a job x that it is using file A, then the job that produced file A is automatically added as a parent to job x. For almost all jobs in the coh_PTF post-processing it should be possible to add dependancies like this (ie, without adag.addDependency) ... and this is actually why this method is protected. The results page might be one exception, and I can show how this is handled for the all-sky workflow if needed.

And maybe as a consideration for the future: Would you consider moving the html page generation over to the `pycbc_make_html_page` used in other pycbc workflows (including, but not limited to the all-sky search)? It's a bit weird to get started on, but it *is* a lot better than any crappy html pages I might have written (unless you've already moved to something else that I'm not aware of?)!

**Comment by a-r-williamson** [comment]
@spxiwh 
> Have you considered converting to a HDF file format before doing the trig_combiner stage (or doing trig_combiner directly into HDF?) Trig_cluster only needs a small subsection of the data to do clustering, which HDF will easily allow you to access (ie. end time and "bestnr"). This would decrease the memory footprint of clustering by a factor of 50 over the XML files.

I've not looked into this, as it would involve more of a change to the code and the post processing code will (I hope very soon) ported to a new `pycbc` form anyway. Perhaps Cardiff people can weigh in on whether they want to do this now or later.

> but if you tell a job x that it is using file A, then the job that produced file A is automatically added as a parent to job x. For almost all jobs in the coh_PTF post-processing it should be possible to add dependancies like this

The issue here (and I have tried this) is that the codes in `pycbc-pylal` write their outputs straight to a directory. Trying to add these as `File` objects and linking them as input/output results in `pegasus` transfer errors, since `pegasus` expects to find these in the local work directory upon termination of the job, which will not be the case. In the interest of time, and again because this code is soon to be killed off, I went with the easier and quicker option you see here. Perhaps we can overlook the unpleasant nature of calling a protected attribute for now?

> And maybe as a consideration for the future: Would you consider moving the html page generation over to the pycbc_make_html_page used in other pycbc workflows

Again, this would be part of the new post processing development/porting.

**Comment by spxiwh** [comment]
Hi @a-r-williamson is there a specific timeline for the changes you are discussing? Some of this is new to me, and it would be good to get an update on when and how this will happen on the PyCBC call (and if and where help is needed) ... Maybe also other changes/problems (like waveform limitations in coh_PTF) could be discussed.

I can buy the argument of doing a minimal thing now if a larger change is coming imminently, but I'm also worried that temporary solutions tend to become long-term solutions.

Certainly I'm not happy to see this get onto pycbc master until landscape is a lot happier with this. However, I propose one suggestion: Move legacy_ihope.py and postprocessing_cohptf.py into pycbc-pylal. That repository is now *only* used by GRB, so you can do what you want with it and landscape, QC or I won't complain.

**Comment by sfairhur** [comment]
Hi Ian,

In the bigger picture, we have people here (mostly Iain Dorrington) looking at getting the coherent code into pycbc.  So far he's mostly been working on understanding the existing code and the coherent algorithm.  That will naturally make use of all of the pycbc infrastructure, and once that's at a prototype stage, then I think it makes sense to start looking at the post-processing.

For now, the changes that Andrew is making are in order to let us complete the runs more quickly.  In some cases, post-processing is the time limiting factor for the online runs.

**Comment by spxiwh** [comment]
Okay, if the changes being discussed are ones that will come in *after* the matched-filter engine is converted to PyCBC, then I think it is worth looking into more detailed changes to the post-processing code (especially a HDF conversion, which should remove the memory issues, and the ability to specify output files correctly to be able to track this properly with pegasus).

I'd also suggest using the PyCBC clustering functions directly. The logic here is actually based off of the GRB codes, but it wasn't written by me, so it's *much* faster.

Again, though. I might be missing some of the details here, so it would be good to properly understand where we stand on this, so a presentation on the PyCBC call would be good.

**Comment by sfairhur** [comment]
Hi Ian,

Sorry, I don't think I'm being clear.

The changes proposed by Andrew in this code are required now, to make the online runs finish in a reasonable amount of time.  I don't think we should be rewriting the code to hdf files now.  i.e. please approve this change as is, once the issues are resolved.

In parallel, Iain is looking at the coherent search in pycbc.  That won't be ready for a few months but when it is getting closer, we'll look at a new post-processing backend that works with the new filtering code.

**Comment by spxiwh** [comment]
I admit to being somewhat confused by all this. The code review check etc. (which is not a new concept, and not something that only PyCBC does) is an attempt to improve the quality of code going forward. This can be annoying in cases, but in balance I think it is a good thing. It also helps to spread knowledge about the different features of PyCBC.

Anyway, I don't think it's fair to say that this must be approved as is, I think that's against the spirit of what we're trying to do with having this check on pull request. But I don't want to be seen as holding this up or disrupting this, so I simply step away from this. Please find someone else to look over and approve this.

**Comment by a-r-williamson** [comment]
I don't think any of us have said "this must be approved as is". I fully intend to address those code quality issues that can reasonably be addressed while still, hopefully, getting this change up and running soon for the sake of utility.

It has always been the plan to move the post processing over to newer methods. It has also always been isolated in postprocessing_cohptf.py and legacy_ihope.py for the purpose of getting rid of it easily when the time comes. This addition of one function is simply proposed as a solution to a problem that is affecting run times now.

As for completely revamping the way PyGRB's post processing is done before this becomes acceptable (with hdf files/moved to pycbc-pylal), I would only say that this has never been as issue of critical concern up until now, so I'm not sure why it is now.

**Comment by a-r-williamson** [comment]
Code moved to `pycbc-pylal`. See ligo-cbc/pycbc-pylal#36

**Comment by a-r-williamson** [comment]
@pannarale your review doesn't allow us to get this merged, I don't know who is allowed to review pull requests any more.

**Comment by ahnitz** [comment]
@a-r-williamson @pannarale  you should have permission now

**Comment by pannarale** [comment]
Thanks, @ahnitz

**Pull request merged**
