### PR TITLE
Some changes required for PyGRB

### PR DESCRIPTION
**Pull request by a-r-williamson**
This also includes a fix for a bug found in configure.py instances of get_opt_tag() and has_opt_tag().

PyGRB-related changes address bugs introduced by recent changes on master (namespace changes, gating files, etc.), a bug in the open box script, some post processing improvements, and updated example files (to be moved over to code.pycbc.phy.syr.edu at a later time).

### CODE REVIEW

**Comment by duncan-brown** [comment]
@spxiwh do you want me to look at this so we can get it in 1.2.0? This commit looks like the only one that doesn't affect the GRB code:

https://github.com/a-r-williamson/pycbc/commit/089489f849749b76f25173619bf94132c9067057

and it fixes a bug.

**Comment by spxiwh** [comment]
Hi Duncan,

I wasn't sure whether you would want to pull this into v1.2.0 because of the change you refer to. However, as you say, it does seem to be a bug fix (probably a relic of some of the oldest workflow.py code) so I see no reason not to have this in v1.2.0. Merge this now if you want it in v1.2.0. Otherwise I'll merge it tomorrow morning.

**Comment by duncan-brown** [comment]
@spxiwh thanks, I think @sfairhur was hoping that the GRB code could get into 1.2.0, so I'll merge.

**Comment by spxiwh** [comment]
@a-r-williamson  "SpinTaylorFrameless" is ancient (it is the precursor of the modern SpinTaylorTX). Don't use this as a filter waveform. I guess that's being fixed in the C-code change sent around earlier though. TaylorF2, SEOBNRv2_ROM_DoubleSpin or even IMRPhenomD are better choices and the frequency domain waveforms are quicker to generate anyway

SpinTaylorthreePointFivePN has also been deprecated with SpinTaylorT4threePointFivePN, these older waveform approximants are not being updated with new PN terms.

**Comment by a-r-williamson** [comment]
@spxiwh We (Francesco mostly) are working through the C code to allow more approximants, so this is only included as a best currently available option.

**Pull request merged**
