### PR TITLE
Simple workflow for estimating average noise PSD

### PR DESCRIPTION
**Pull request by titodalcanton**
This is a work in progress to implement PSD estimation (averaged over time for each detector, as well as averaged over time and detectors) over a stretch of strain data. We'll need this in O1 to rapidly estimate the PSD in order to build the template bank. We could also add here some basic DQ checks or operations like gating. The PSD averaging program is done, but I'm still working on the workflow generator. Opening this early in case somebody has comments or suggestions.

### CODE REVIEW

**Comment by titodalcanton** [comment]
This is now completed and being tested on ER7 and ER8.

**Comment by spxiwh** [comment]
Hi Tito,

Thanks for doing this, it will be really useful to have! I have a few requests:

 * The argument parsing for time-avg-file is ugly. Can you use the existing multi-detector interface for this. I think you have used this before? If not let me know and I can give pointers.
 * The make_average_psd function shouldn't live in coincidence.py. Maybe tmpltbank.py is more sane? Or somewhere else? Maybe a sort of generica.py?

Less important:

 * Should the SectionNumber class really live in the executable?
 * Why are you using SectionNumber at all, if you don't make a result page for this? Or am I missing something?

Cheers
Ian

**Comment by titodalcanton** [comment]
Hi Ian, I mostly agree with all your points. The result page part I'm not sure about. I was thinking of leaving a couple of sanity plots, but I guess I can make it to just spit out a PSD file and we can revisit it later.

**Comment by spxiwh** [comment]
Hi Tito,

If you want to make a result page here that sounds good to me! I was just confused as this looked like the setup for the all-sky results page, not a specific PSD sanity plot page?

**Comment by titodalcanton** [comment]
Ian, I addressed your comments and tested the workflow on ER7. The resulting PSDs (green below) match your estimations (red below). Small differences are due to my own PSD estimation parameters (which make them a bit smoother) and a slightly different choice of data segmentation since I'm not using the inspiral segments.

h1

h1l1

l1

**Pull request merged**
