### PR TITLE
Add gating files at the workflow level, allow them to be URLs

### PR DESCRIPTION
**Pull request by lppekows**
This adds a new section to the workflow
```
[workflow-gating]
gating-method = PREGENERATED_FILE
gating-pregenerated-file-h1 = (file or URL)
gating-pregenerated-file-l1 = (file or URL)
```

I've confirmed that
  * This section is optional, no error is caused by omitting it
  * Each ifo is optional, in the unlikely case where we only having gating files for one
  * Remote URLs work
  * When provided, the files are added to workflow and the --gating-file argument is added to full data and injection jobs

### CODE REVIEW

**Comment by ahnitz** [comment]
Larne, this looks ok to me. Have you successfully run a workflow this this?

**Comment by duncan-brown** [comment]
Just talked to Larne and he needs to make the same fix for the PSD computation.

**Comment by duncan-brown** [comment]
Larne, assign this to me when you're done and Steve or I will run a complete DAX.

**Comment by lppekows** [comment]
Hi Duncan,

I've added gating to the calculate_psd jobs and verified the DAX.

**Pull request merged**
