### PR TITLE
Add sbank scripts to released virtualenvs

### PR DESCRIPTION
**Pull request by titodalcanton**
This (I think) will add sbank scripts to the release virtualenvs on CVMFS, so they can be used to build template banks with the hyperbank workflow. Addresses #2017.

### CODE REVIEW

**Comment by ahnitz** [comment]
@titodalcanton I think you can test this by checking out the master docker build.  That way we can make sure this worked before making a release.

**Comment by titodalcanton** [comment]
Looks like the master docker image is only built from whatever is currently on master. I could try running the `docker_build_dist.sh` script in a Debian VM and at least see if I get the sbank scripts in the right place.

**Comment by ahnitz** [comment]
@titodalcanton Oh, I guess that might work. I don't think it is too big a deal if you merge and verify in this case though.

**Comment by titodalcanton** [comment]
Ok, I got the whole script tested on a Stretch VM (I had to do a few other Stretch-related edits which I have not committed). The virtualenv builds fine and allows me to generate the uberbank workflow as given on PyCBC's documentation page.

An annoyance is that one cannot just `cp` the sbank scripts, I had to change the script to `make` and `make install` the whole lalinspiral. This adds a few hundred megabytes of static binaries to the virtualenv (in principle a more complex version of the script could go back and remove the ones we do not use, of course).

**Comment by titodalcanton** [comment]
I am merging this so we can actually use the virtualenv on a cluster, as far as I have seen it should not cause issues.

**Pull request merged**
