### PR TITLE
pycbc_inference allow user to set initial positions from an InferenceFile

### PR DESCRIPTION
**Pull request by cmbiwer**
As title says so you can pick up a run from the position it left off. Only for the kombine sampler. Raises a ``NotImplementedError`` for the emcee samplers.

It could be a small, concise project for someone whose getting into the inference code to implement this for emcee as well.

### CODE REVIEW

**Comment by cmbiwer** [comment]
The first part sounds fine. I'll add that to this PR.

But:
>> Second, make it so that the prior is loaded from the config file that was used in the initial run, or at least have a check that the config file name is the same.

I'm not sure this really needs to be added with this PR though. To me this is a separate issue on how to save the prior information to the ``InferenceFile``. And I'm not really a fan of checking that file names are the same.

**Comment by cmbiwer** [comment]
Can put up from where it left off now.

Samples 500-1000 for a run with 1000 iterations: https://sugwg-jobs.phy.syr.edu/~cbiwer/projects/inference_reuse/samples_500_1000_full.png
Samples 0-500 for a run that began at the 500th iteration: https://sugwg-jobs.phy.syr.edu/~cbiwer/projects/inference_reuse/samples_500_1000_reuse.png

**Comment by cdcapano** [comment]
Thanks for adding the ability to pick up where it left off. One other request: can you remove the `samples-file-iteration`? Anything but the last iteration won't work with the state, so there's no point in giving the user the option.

For the thing about the config file: ok, fair enough. The command line is written to the new output file, so there's at least a record of what settings were used.

**Comment by cmbiwer** [comment]
> Anything but the last iteration won't work with the state, so there's no point in giving the user the option.

Well this isn't quite a true statement, you can but it just won't match up with a run that does not have breaks. I've removed it though, no big deal.

> For the thing about the config file: ok, fair enough. The command line is written to the new output file, so there's at least a record of what settings were used.

Well don't get me wrong though, I think it would be nice to have the prior information in the ``InferenceFile`` as you suggestd. I just don't think it needs to be included into this PR.

But please take another look at this PR.

**Pull request merged**
