### PR TITLE
A new-year's attempt to fix all documentation errors

### PR DESCRIPTION
**Pull request by spxiwh**
I thought to myself on Monday, it's a new year, why don't I take a look to see if there have been any issues introduced that cause failures or problems with the documentation build, that won't take very long to fix .... :-S.

This patch fixes *all* warnings in the documentation build (something we've *never* had before). All changes are to documentation, either in-line doc-strings or the documentation .rst files. However, there are a *lot* of changes. This by no means makes the documentation "good". In many cases documentation is missing, or is incomplete. I would like to point people to this page here:

https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#a-guide-to-numpyscipy-documentation

which is probably the most useful reference I found for writing doc-strings. And these links here:

http://docutils.sourceforge.net/docs/user/rst/quickref.html

http://docutils.sourceforge.net/docs/ref/rst/directives.html

as references when writing rst directives.

Especially. Now that the docs build without warnings. If you make changes to documentation pages *build the docs*. Look for warnings and check that the output pages look like you want them to. @duncan-brown I think the auto doc builder is broken again, but can you get it to report warnings somehow if one occurs in the daily builds?

Some notes and some shout outs to people:

 * Sphinx version requirement in now 1.4.2. This, coupled with changes in conf.py, is needed to silence some warnings that should not really be warnings (ie. the DOI external image on the front page and *all* the numpy class member warnings that I'm sure @ahnitz will remember have plagued us since starting PyCBC docs)
 * With that done there is no need for the docs_test command. So I removed it.
 * Old module documentation (time_slides, coincidence in SQL) have just been removed.
 * @cmbiwer Links must go *above* the section header (see hwinj.rst changes)
 * @cdcapano @cmbiwer @micamu The inference module definitely wins the "Module with best documented in-line functions" award. But almost none of it actually compiled! So while the documentation was great, the resulting web-pages were a mess. Please see the edits to this code. Also, given the amount of effort y'all put into this. It would be good to have this stuff highlighted more prominently. The in-line documentation is kind of hidden on the html pages, and must be searched for. You've already made a inference.rst module-level documentation page. I would suggest expanding on that, using sub-pages if necessary. You can just input directly the function/classes documentation, in an order that you choose, and just say this is the BLAH class that is used for this and here is the explanation [input class documentation in full].
 * @cdcapano Basically the same comment for the waveform generator module.
 * @micamu And the same comment for the waveform ringdown module. Here the problem is new lines. Sections must be separated with new lines.
 * @ahnitz / @cmbiwer (not sure who started this): Stop making up section headers! See link above. :-)
 * @cdcapano If you document a class attribute when declaring it with property, don't document it *again* in the main class docstring (see changes to compress.py).

Finally a test of this is here:

https://ldas-jobs.ligo.caltech.edu/~spxiwh/pycbc_docs/docs/html/index.html

(which built without any warnings or errors) and I have turned on "allow edits". So if you want to make fixes/changes please do so, or open a pull request against this branch.

I did *not* add the flag that makes the doc builder fail if a warning is present. Should I?

@titodalcanton There are also a few fixes to the tmpltbank module. As these are tied up with the big patch #1354 I'm going to merge those into that.

### CODE REVIEW

**Comment by spxiwh** [comment]
Landscape is failing because the algorithm it uses to determine code quality also takes into account amount of code in the repository. So by changing (and removing) many pieces of code, the quality can decrease without any new issues being introduced. I think this failure should be ignored.

**Comment by cmbiwer** [comment]
>@ahnitz / @cmbiwer (not sure who started this): Stop making up section headers! See link above. :-)

Just asking so I don't do it again... I assume your talking about in some places our sections use different ASCII characters, eg. some its:
```
&&&&&&&
Section
&&&&&&&
```

And some its:
```
=======
Section
=======
```

I didn't notice any style guide in the links above though. It seems the canonical example uses ``=``, should we just use that then?

**Comment by spxiwh** [comment]
@cmbiwer No that is actually fine. Different ASCII characters indicate different level of headings, but there is not a guideline other than changing it for lower levels. The issue I was referring to was sections called things like:

```
Class Methods
---------------
```

in Class docstrings. These are not recognized. The link at the top gives the recognized section headers.

**Comment by cmbiwer** [comment]
@spxiwh Ah ok, I see it now thanks! I'll use these from now on. Thanks.

**Pull request merged**
