### PR TITLE
Added method to resolve URLs to local filenames

### PR DESCRIPTION
**Pull request by lppekows**
This adds a function, resolve_url that accepts any of
  * http://
  * https://
  * file://
  * plain file names

and returns a local filename, downloading if necessary.  This will be needed to resolve https://github.com/ligo-cbc/pycbc/issues/306 and https://github.com/ligo-cbc/pycbc/issues/311

### CODE REVIEW

**Comment by lppekows** [comment]
To give some more context, the idea is that WorkflowConfigParser would then do

```
configFiles  = [resolve_url(cFile) for cFile in configFiles]
```

I've confirmed that that works, but thought it would be better to split this into two pull requests with a third to follow for pulling in executables.

**Comment by spxiwh** [comment]
Hi Larne,

I think that if I supplied:

splittable= file://localhost/path/to/file.exe

this would not work. Maybe an additional check to strip localhost if it is present at the start for file urls?

**Comment by ahnitz** [comment]
Larne, 

If I am reading this right then it only copies thing to the current directory?  I won't hold this up and I'm OK with this as is, but please take our two requests into advisement for a future patch (perhaps in the next pull request if it isn't hard).

1) Add a directory argument, so that files aren't always copied to the CWD
2) check for the example Ian gives.

**Comment by lppekows** [comment]
Hi Ian, Alex,

thanks, I've opened a new issue to address these two points

**Pull request merged**
