### PR TITLE
Add functions to find intersection of time series

### PR DESCRIPTION
**Pull request by ahnitz**
* Add method to get intersection of two time series
* Add and 'add' method that uses this as well.

### CODE REVIEW

**Comment by spxiwh** [comment]
It seems that you are basically recoding `SimAddInjectionREAL[4,8]TimeSeries`. However that code has one significant advantage: If the sample points don't line up (ie they're offset by 0.5 of a sample point) the XLAL code will do the right thing. Therefore I would either suggest to use the XLAL function internally here, or add the sub-sample functionality. I would think that the main use-case here is to add signals to data, and we shouldn't be losing functionality in implementing that in a way that's more intuitive to use.

**Comment by ahnitz** [comment]
@spxiwh Any update?

**Comment by spxiwh** [comment]
You didn't reply to my comment. Did you make the changes?

**Comment by ahnitz** [comment]
@spxiwh Any update?

**Comment by ahnitz** [comment]
Oh, woops. I guess I didn't. Yes, you can insert at sub-sample precision now. The sample rates are still required to be the same, but they need not align.

**Pull request merged**
