### PR TITLE
New version of the PyCBC install script

### PR DESCRIPTION
**Pull request by duncan-brown**
This version produces both bundles and development environments.

### CODE REVIEW

**Comment by josh-willis** [comment]
@duncan-brown @lppekows I'd like to test this soon and then will approve and merge.  When using it to build a pyinstaller bundle, is it still the case that we only expect that to work on certain machines? (I think it was sugar-dev2, if I remember right)?  If so, can you remind me what those are?  If not I may try at CIT just to see if it works there.

**Comment by duncan-brown** [comment]
@josh-willis to build the bundles for OSG you have to run on sugar-dev2, as that's the only place that currently has the CVMFS python2.7 installed. However, if you're not building OSG bundles, you should be able to build on other machines. I used sugar-dev3 for a python2.6 build. It would be good to try it at Caltech as well.

**Comment by duncan-brown** [comment]
@josh-willis sorry, forgot to commit a bug fix. You'll need that last commit.

**Comment by duncan-brown** [comment]
@josh-willis I just ran this on sugar-dev2 (OSG python 2.7) and sugar-dev3 (SL6 python 2.6) and the builds worked for me. Can you give it a try?

**Comment by josh-willis** [comment]
So for me on pcdev3 at CIT this failed with:
```
Downloading/unpacking https://github.com/duncan-brown/dqsegdb.git@pypi_release#egg=dqsegdb (from -r /home/jwillis/pycbc-6588d98b-44ad-40d0-98ae-238b1415988a/requirements.txt (line 52))
  HTTP error 406 while getting https://github.com/duncan-brown/dqsegdb.git@pypi_release#egg=dqsegdb
  Could not install requirement https://github.com/duncan-brown/dqsegdb.git@pypi_release#egg=dqsegdb (from -r /home/jwillis/pycbc-6588d98b-44ad-40d0-98ae-238b1415988a/requirements.txt (line 52)) because of error HTTP Error 406: Not Acceptable
Could not install requirement https://github.com/duncan-brown/dqsegdb.git@pypi_release#egg=dqsegdb (from -r /home/jwillis/pycbc-6588d98b-44ad-40d0-98ae-238b1415988a/requirements.txt (line 52)) because of HTTP error HTTP Error 406: Not Acceptable for URL https://github.com/duncan-brown/dqsegdb.git@pypi_release#egg=dqsegdb
Storing complete log in /home/jwillis/.pip/pip.log
```
On the [pycbc install instructions](http://ligo-cbc.github.io/pycbc/latest/html/install.html) it seems that the URL is:
```
git+https://github.com/duncan-brown/dqsegdb.git@pypi_release#egg=dqsegdb
```
i.e., there is a `git+` before the URL. Not sure if this somehow got stripped by the shell running the script, or is just missing.

Also, supposing this is fixed, is there some way I need to modify it to point to your branch of pycbc, @duncan-brown ? I assume the script will be setup to pull from `ligo-cbc/master`. Can these changes be easily back-ported to 1.4.0, so that we can build a bundled release of that?

**Comment by duncan-brown** [comment]
Does it work on sugar-dev3? I wonder if that's a network issue. Are you building bundles or not?

Nothing in here is specific to my repo. It should work fine on master.

> On May 19, 2016, at 5:27 PM, Josh Willis <notifications@github.com> wrote:
> 
> So for me on pcdev3 at CIT this failed with:
> 
> Downloading/unpacking https://github.com/duncan-brown/dqsegdb.git@pypi_release#egg=dqsegdb (from -r /home/jwillis/pycbc-6588d98b-44ad-40d0-98ae-238b1415988a/requirements.txt (line 52))
>   HTTP error 406 while getting https://github.com/duncan-brown/dqsegdb.git@pypi_release#egg=dqsegdb
>   Could not install requirement https://github.com/duncan-brown/dqsegdb.git@pypi_release#egg=dqsegdb (from -r /home/jwillis/pycbc-6588d98b-44ad-40d0-98ae-238b1415988a/requirements.txt (line 52)) because of error HTTP Error 406: Not Acceptable
> Could not install requirement https://github.com/duncan-brown/dqsegdb.git@pypi_release#egg=dqsegdb (from -r /home/jwillis/pycbc-6588d98b-44ad-40d0-98ae-238b1415988a/requirements.txt (line 52)) because of HTTP error HTTP Error 406: Not Acceptable for URL https://github.com/duncan-brown/dqsegdb.git@pypi_release#egg=dqsegdb
> Storing complete log in /home/jwillis/.pip/pip.log
> 
> On the pycbc install instructions it seems that the URL is:
> 
> git+https://github.com/duncan-brown/dqsegdb.git@pypi_release#egg=dqsegdb
> 
> i.e., there is a git+ before the URL. Not sure if this somehow got stripped by the shell running the script, or is just missing.
> 
> Also, supposing this is fixed, is there some way I need to modify it to point to your branch of pycbc, @duncan-brown ? I assume the script will be setup to pull from ligo-cbc/master. Can these changes be easily back-ported to 1.4.0, so that we can build a bundled release of that?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> 

-- 

Duncan Brown                         http://dbrown10.expressions.syr.edu
Charles Brightman Professor of Physics     Room 263-1 Physics Department
Director of the Graduate Program      Syracuse University, NY 13244, USA
Phone: 315 443 5993                                    Fax: 315 443 9103

**Comment by josh-willis** [comment]
I am building bundles, but not for OSG.

It still fails on CIT.  The most recent log is available there at:

`/home/jwillis/install_pycbc_20160520025815.log`

The current issue seems to be with the package `upload_docs`, which appears to be a requirement of  `pip-7.1.2` (which is specified in `requirements.txt`). On CIT, this is not found, and not downloaded.  

The build *does* complete on sugar-dev3, and it does indicate that `upload_docs` is in the distribution it has built. But I don't see it installed system wide (if I fire up python and try to import it, that fails) so I don't know why it is found on sugar, but not CIT.  Nor why the pip commands don't just find it as a dependency.

**Comment by ahnitz** [comment]
@duncan-brown I tried this on my laptop. It entered a for loop that repeatedly displays this error message after asking for my ligo.org credentials (why does it need these??). 

```
./install_pycbc.sh: line 191: ecp-cookie-init: command not found

Enter your LIGO.ORG password to get a cookie to clone lalsuite.
./install_pycbc.sh: line 191: ecp-cookie-init: command not found

Enter your LIGO.ORG password to get a cookie to clone lalsuite.
./install_pycbc.sh: line 191: ecp-cookie-init: command not found

Enter your LIGO.ORG password to get a cookie to clone lalsuite.
./install_pycbc.sh: line 191: ecp-cookie-init: command not found

```

Is this because you are tying to use the ecp-cookie-init method to retrieve lalsuite? If that is the case, then can we instead use the github location of the lalsuite mirror, that does not require any credentials or ecp-cookie-init.

**Comment by spxiwh** [comment]
I don't think ecp-cookie-init is needed to anonymously check out lalsuite from it's "standard" location either. It's only needed for authenticated push access.

**Comment by duncan-brown** [comment]
@ahnitz the script has been tested in an LDG environment where ``ecp-cookie-init`` exists. It's not necessary if you don't want to push changes to lalsuite. Given that this code does work on sugar, I suggest @josh-willis merges it, and then you can submit a patch to ask if you want to download lalsuite from github or from git.ligo.org.

**Comment by a-r-williamson** [comment]
I just attempted this on sugar-dev3 (log file `/home/awilliamson/install_pycbc_20160520083555.log`. I ran with:
>LIGO.ORG username:  andrew.williamson
Lalsuite Branch or Tag:  pygrb_o1
Development or released:  2
   (1 is release, 2 is development)
Github Username:  a-r-williamson
Path and architecture for Intel compilervars.sh: /opt/intel/bin/compilervars.sh intel64
Not installing ROM data.

When building the static binaries all but 2 of the builds fail. Running --help on the executables in the `pycbc/tools/static/dist` directory I get:
>Setting up scipy for temporary basedir /usr1/awilliamson/_MEIUnUbO8
/usr1/awilliamson/_MEIUnUbO8/numpy/lib/utils.py:99: DeprecationWarning: `scipy.weave` is deprecated, use `weave` instead!
LD_LIBRARY_PATH=/usr1/awilliamson/_MEIUnUbO8:
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "/home/awilliamson/pycbc-f3c3cec2-0af4-4447-9843-a2e3c848fff4/lib/python2.6/site-packages/PyInstaller/loader/pyi_importers.py", line 271, in load_module
    exec(bytecode, module.__dict__)
  File "/home/awilliamson/pycbc-f3c3cec2-0af4-4447-9843-a2e3c848fff4/src/pycbc/tools/static/build/pycbc_write_results_page/out00-PYZ.pyz/pkg_resources", line 68, in <module>
  File "/home/awilliamson/pycbc-f3c3cec2-0af4-4447-9843-a2e3c848fff4/src/pycbc/tools/static/build/pycbc_write_results_page/out00-PYZ.pyz/pkg_resources.extern", line 60, in load_module
ImportError: The 'packaging' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.

Problem with the way PyInstaller was installed?

**Comment by duncan-brown** [comment]
@josh-willis the patch https://github.com/ligo-cbc/pycbc/pull/848/commits/14cb3b5cb5198cf89b2080320d0c06e94b8d448f should fix the problem that you were seeing at Caltech. Please can you try again?

**Comment by duncan-brown** [comment]
@lppekows have you ever seen the error that @a-r-williamson reports? I can't reproduce it.

**Comment by josh-willis** [comment]
This now builds for me successfully at CIT, and had already done so on sugar-dev3.  So I'll merge it forthwith.  Longer-term, I'd like us to modify the script so that it does not require the ecp-cookie, and also so that we don't disable HDF5 in lalsuite (since we go to the trouble of building HDF5, there's no reason not to point our lalsuite at that build).  But those issues should not hold this up.

@soumide1102 , can you please use this to package and release 1.3.8 and 1.4.0?  Thanks.

**Comment by lppekows** [comment]
@duncan-brown Unfortunately that error is new to me, I'm trying to recreate it now.  While investigating I spotted another potential problem, the intel installation on the nodes is incomplete and the bundle err files report
```
../../../../bin/activate: line 3: /opt/intel/bin/compilervars.sh: No such file or directory
```
This could result in the MKL libraries not being included.  This might not be a problem in practice because the bundle script runs with `getenv=True`, the `activate` script maintains the LD_LIBRARY_PATH, and the submit will be kicked off while the environment is active, but I'll try to confirm that.  (Also, since the production pycbc_inspiral job has to built on dev2 in the local universe it won't be a problem).  Still, I don't know why the installation on the nodes isn't complete, and it should probably be updated.

**Comment by a-r-williamson** [comment]
@soumide1102 if you are going to package 1.4.0 can you please remember to do so against the `pygrb_o1` branch of lalsuite? Thanks.

**Comment by lppekows** [comment]
I can reproduce @a-r-williamson 's issue when building against the `pygrb_o1` branch.  I get the same behavior when building from the command line.  From the note [here](https://github.com/pyinstaller/pyinstaller/issues/1781) the fix is to downgrade setuptools from within the virtual environment
```
source ${NAME}/bin/activate
pip uninstall setuptools
pip install setuptools==19.2
```
after which
```
rm -rf pycbc_inspiral.* build/pycbc_inspiral/
./build_one.sh ../../bin/pycbc_inspiral 
./dist/pycbc_inspiral --help
```
produced a working bundle.  

requirements.txt specifies `setuptools==18.2`, I'm not sure at what point that's getting superseded.  I also have no idea why one branch of lalsuite tickles the bug and others don't...

**Comment by duncan-brown** [comment]
@lppekows, please can you open a separate issue about the setuptools bug so I don't forget?

**Comment by soumide1102** [comment]
@lppekows  @duncan-brown  I ran the script on sugar-dev2 saying "no" for OSG python with the following specifications 
Lalsuite Branch or Tag:  o1_lalinference_20160326
Development or released:  1
   (1 is release, 2 is development)
Released Tag:  v1.3.8
Path and architecture for Intel compilervars.sh: /opt/intel/bin/compilervars.sh intel64
Not installing ROM data.

for which it built the bundles and the script completed successfully.

Then running the same on dev-2 with "yes" to OSG python, the script does not proceed beyond building the bundles and checking the logs. Path to the log file for this test is : /home/soumi.de/projects/cbc/make_bundles/install_pycbc_20160521135528.log

**Pull request merged**
