### PR TITLE
support step in slicing

### LINKED ISSUE #1542: Slicing an array to return every other sample
There currently seems to be no way to do something like:

```
timeseries[::2]
```

with a pycbc TimeSeries.

### PR DESCRIPTION
**Pull request by ahnitz**
I'm removing the error that prevents using the step size. It seems to now work in pycuda, so no reason to block it. 

Fixes #1542

### CODE REVIEW

**Comment by ahnitz** [comment]
(doesn't do anything special with time series at this point though)

**Comment by ahnitz** [comment]
@spxiwh Ok, did the three lines needed to fix delta_t for TimeSeries.

**Comment by spxiwh** [comment]
Slicing frequency series is also a useful operation (e.g. its done in banksim)

**Comment by ahnitz** [comment]
@spxiwh Ok, done.

**Comment by spxiwh** [comment]
Merge when ready then

**Pull request merged**
