### PR TITLE
Inv injections

### PR DESCRIPTION
**Pull request by spxiwh**
Here is the code changes that were needed to make:

https://atlas1.atlas.aei.uni-hannover.de/~spxiwh/LSC/aLIGO/O1/analyses/chunk5/o1-analysis5_pt8_invinjs/

as I showed on the call yesterday.

@tdent wanted to look at the changes to pycbc_page_ifar and suggest improvements to the comment.

There is also a potential issue that without the config file changes that I have, open box plots will appear in section 4. Probably I want to rethink that!

### CODE REVIEW

**Comment by tdent** [comment]
Ian, please separate the two changes (inj / ifar) into two separate issues so that they can be merged and commented independently.

**Comment by spxiwh** [comment]
Tom, why is that necessary? I can respond to comments here. It's just painful to split this up.

**Comment by tdent** [comment]
Isn't that obvious?  It's painful to look at and discuss an issue which contains two completely independent sets of changes.  Also how do we decide when to merge it if one change is OK but the other is still under discussion? 

Anyway, assuming you havent mixed them together in any single commit, you can just make two more topical branches and cherry-pick the relevant commits onto each.

If you *really* object to doing that then I guess I can live with it, but that's my advice.

**Comment by spxiwh** [comment]
Split into #637 and #638

**Pull request closed without merging**
