### PR TITLE
update setup.py to try to use setuptools and list its own dependencies

### PR DESCRIPTION
**Pull request by ahnitz**
This adds the option to use setuptools if it is available and sets some of the PyCBC python dependencies. Please update if the list is wrong. I've also added a default version.py output if one is not installing from a git repo. All of these changes now allow PyCBC to be installed directly from git using pip and have it resolve most of its own python dependencies. 

### Included dependencies which setuptools/pip will download and install for you.
install_requires =  ['Mako>=1.0.1',
                      'argparse>=1.3.0',
                      'decorator>=3.4.2',
                      'numpy>=1.6.4',
                      'scipy>=0.13.0',
                      'matplotlib>=1.3.0',
                      'pillow',
                      'jinja2',
                      ]

### example command to install pycbc using pip 
pip install https://www.github.com/ahnitz/pycbc/tarball/setuptools --user

### Dependencies Not Included:
**All c based dependencies**: lalsuite + its swig bindings, fftw, etc. 
**pylal**: depends on lalsuite to build against, does not fully list its own dependencies
**glue**: depends on lalsuite to build against, does not fully list its own dependencies
**mpld3**: version not yet updated to the one we need, could fork and tag if need be. 

Are there any that I've missed? Are the versions I've nominally required here ok? Is it worth uploading an initial version of PyCBC to the PyPI for testing?

### CODE REVIEW

**Comment by cmbiwer** [comment]
I tested the pull request and everything builds the same.

One comment is that you have the line:
```download_url = 'https://github.com/ligo-cbc/pycbc/tarball/v%s' % VERSION,```

And in your except statement you have `version=0.1`. But there is nothing at the URL download_url: https://github.com/ligo-cbc/pycbc/tarball/v0.1

Is this expected?

Also we should update this page with all the packages not listed already (jinja2, etc.): https://ldas-jobs.ligo.caltech.edu/~cbc/docs/pycbc/install.html

**Comment by ahnitz** [comment]
Hi Chris, the download_url is used by PyPI. The ideas is that we will tag our release with their version number and upload the new version to PyPI. When that happens, it will indeed point to a real file, but as we haven't had a release, it won't, but it also isn't used by anything.

**Comment by ahnitz** [comment]
Chris,

I've updated the install page to include jinja2.

**Comment by cmbiwer** [comment]
Ok, looks good. I've test both the normal install and your pip command. They both work. Though in order to use the pip command on sugardev3 I had to update distribute and numpy first. Matplotlib wanted a higher version of distribute than was installed, and it outputed an `easy_install` command to get it. And scipy wanted a higher version of numpy than was install on the clutser (it didn't check that we were also upgrading numpy I guess).

**Pull request merged**
