### PR TITLE
Enable optimal SNR calculation in workflow

### PR DESCRIPTION
**Pull request by titodalcanton**
Work in progress to enable calculating optimal SNRs of injections in the workflow.

### CODE REVIEW

**Comment by tdent** [comment]
Hi Tito, can the columns to store the values in be arbitrary strings or do they have to be 'blessed' SimInspiral columns?  If the latter then the help should say so and make some suggestions .. 
Ideally the injections should be in an hdf file anyway, but we ain't there yet.

**Comment by titodalcanton** [comment]
I added the missing bits, so this needs to be tested now.

**Comment by titodalcanton** [comment]
Actually no, one last thing missing and also need to add Tom's comment…

**Comment by titodalcanton** [comment]
All the needed changes are in. Testing in ~tito/er8/runs/er8b_c00_1.2.0_optsnrtest.

**Comment by titodalcanton** [comment]
Test run is here:
https://atlas1.atlas.aei.uni-hannover.de/~tito/LSC/er8/er8b_c00_1.2.0_optsnrtest2
The optimal SNRs have been computed and the job dependencies were correct, but something went wrong with the injection recovery. The DAX reduction was also weird, some jobs reran even though I didn't want them to. I wonder if there has been some change in the segdb or in PyCBC itself which somehow broke the DAX reduction functionality from my previous run. I'll try to run a small test workflow from scratch.

**Comment by ahnitz** [comment]
Tito, can you check that the gps times for your new run are the same as the
old one? I had noticed Duncan changed the start/end times slightly and this
screws over a lot of things, including injectoin finding as the injection
set would not be the same as the one actually injected. If this isn't the
case, then I don't know.

**Comment by titodalcanton** [comment]
Alex, you're right, there's the one-second fix to the start and end times.

**Comment by titodalcanton** [comment]
Successful test run: https://atlas1.atlas.aei.uni-hannover.de/~tito/LSC/er8/er8b_c00_1.2.0_optsnrtest2 (the crazy missed injections fall outside of the test bank). Example optimal SNR plots: [minimum optimal SNR](https://atlas1.atlas.aei.uni-hannover.de/~tito/LSC/er8/er8b_c00_1.2.0_optsnrtest2/5._injections/H1L1-PLOT_FOUNDMISSED_ALL_MCHIRP_MINOPTSNR-1126051217-1220400.png) and [combined optimal SNR](https://atlas1.atlas.aei.uni-hannover.de/~tito/LSC/er8/er8b_c00_1.2.0_optsnrtest2/5._injections/H1L1-PLOT_FOUNDMISSED_ALL_MCHIRP_COMBOPTSNR-1126051217-1220400.png)

**Comment by ahnitz** [comment]
Tito, thank you very much for this! I'll merge once the automated tests complete. Can you please also make a change to the configuration repo's plotting.ini file to include this in the found missed plots ?

**Comment by titodalcanton** [comment]
Will do.

**Pull request merged**
