### PR TITLE
Add optional sample_rate arg to psd.from_cli function

### PR DESCRIPTION
**Pull request by cmbiwer**
This PR adds an optional keyword arg to ``psd.from_cli`` called ``sample_rate``. And this PR allows ``pycbc_generate_hwinj`` to use this optional argument.

I received an error ``ValueError: Incorrect choice of segmentation parameters`` and noticed that the ``sample_rate`` var that is calculated is slightly off, eg. it was setting ``sample_rate`` to 16379Hz instead of 16384Hz.

For example:
```
>>> N=4011                                # length of h(t) time series in samples
>>> sample_rate=16384                     # sampling rate of time series
>>> delta_f = 1.0 / ( N ) * sample_rate   # calculate frequency step
>>> ((N/2 +1) -1) * 2 * delta_f           # calculate sampling rate like in psd.from_cli
16379.915233108952
```

I have witnessed this when ``N`` is not an integer multiple of the sampling rate, ie. not our standard ``pycbc_inspiral`` case.

Unless someone else has a better fix. Zero-padding the time series to be an integer multiple of the sampling rate seemed to work as well but gave a division by zero warning.

### CODE REVIEW

**Comment by spxiwh** [comment]
Hi Chris,

I don't think this is the right solution as sample_rate is *not* a parameter you are free to choose given delta_f and N! Please see attached code block:

```
In [1]: N=4011

In [2]: sample_rate=16384

In [3]: delta_f = 1.0 / ( N ) * sample_rate

In [4]: ((N/2 +1) -1) * 2 * delta_f
Out[4]: 16379.915233108952

In [5]: from __future__ import division

In [6]: delta_f = 1.0 / ( N ) * sample_rate

In [7]: ((N/2 +1) -1) * 2 * delta_f
Out[7]: 16384.0
```

So the issue is integer division being used where float division is needed. Probably N/2 needs to be N/2.0 but I would declare all integers here floats (ie. 1.0 and 2.0) or just import division from future and be done with it.

Personally I don't think there is *any* use case where we should be using integer division and not declaring that explicitly with the "//" and "%" operators,.

**Comment by cmbiwer** [comment]
Hey Ian, I agree that sample rate is not free to choose that's why I was hoping someone else had a better thought.

So your solution works for PSD estimation (``--psd-estimation``), it does not work for using PSD models (``--psd-model``). It tries to create an array length from a float when ``--psd-model`` is used. Though the case I actually care about is PSD estimation I was just trying for something that worked in all cases.

I've force pushed a new commit that does the float division and tested it on several of the problematic waveforms I found. It worked in those cases.

And a note, one awkward thing is that ``N/2+1`` is actually the ``length`` arg in ``psd.from_cli`` which in the docstring is written to be an ``int`` (for the reasons with ``--psd-model`` above).

Though in all I'm fine to make this change, since it makes the PSD estimation functionality of ``pycbc_generate_hwinj`` more robust.

**Comment by spxiwh** [comment]
Hi Chris,

Maybe this all boils down to that the PSD module has an implicit requirement that N is even (as I don't think we have thought about supporting FFTs for odd lengthed N ... and probably nor should we). Maybe just make a demand that N is even and round up in generate_hwinj if this is a problem?

What exactly is pycbc_generate_hwinj generating a PSD for? Can it not use a standard binary length number?

Cheers
Ian

**Comment by cmbiwer** [comment]
Hey Ian, I had tried the method of making ``length`` an even integer last night as well. It didn't work out when I tried, here's an example:
```
In [21]: N=4012
In [22]: sample_rate=16384
In [23]: delta_f = 1.0 / ( N ) * sample_rate
In [24]: ((N/2 +1) -1) * 2 * delta_f
Out[24]: 16383.999999999998
```
There's a bit of round-off error here. And it sets ``sample_rate`` as 16383Hz.

``pycbc_generate_hwinj`` is getting a PSD to calculate sigma-squared.

Its not as restrictive that ``length`` needs to be a binary length. The problem arises when ``length`` (length in samples of the PSD output) is not an integer multiple of the sampling rate. If it was this wouldn't be an issue and the ``sample_rate`` calculation would work; we satisfy this condition in the pycbc workflows. I originally just zero-padded the waveform to have a length that is a multiple of the sampling rate but there was a division by zero warning. It would be nice to not have a warning as well.

**Comment by cmbiwer** [comment]
**I will make a new forced push, do not push this PR.**

Duncan and I talked about this PR. Duncan suggested that I revisit my attempt last night of making the timeseries an integer multiple of the sampling rate. I think I this will work, I will test my new fix and force push a new commit.

**Comment by cmbiwer** [comment]
Ok I now have a better solution, zero-padding the waveform time series to an integer multiple of the sampling rate works. The problems I saw last night were due to issue fixed by #279 but I didn't have this commit in my cloned repo.

I tested this PR on the problematic waveforms and saw no warnings.

So this PR now zero-pads the waveform to an integer multiple of the sampling rate. This is done by the ``pad_timeseries_to_integer_length`` function I added. It gets calls on both polarizations after ``get_td_waveform`` is called see lines 271-272 and 329-330.

I also added some comestic changes to the code:
  * Changed ``delta_f = 1.0 / N / h_plus.delta_t`` to ``delta_f = 1.0 / ( N * h_plus.delta_t )``
  * Reduced number of lines in ``get_td_waveform`` calls by reusing ``SimInspiral`` instance
  * Use ``sim.distance`` instead of ``distance`` or ``scale*distance``
  * And I added a ``sys.exit()`` that was missing

**Pull request merged**
