### PR TITLE
Phasetd

### PR DESCRIPTION
**Pull request by ahnitz**
Fix a bug in the way inclination was included and improved the option handling to pycbc_stat_dtphase. Also addes the saving of amplitude parameters to the output histogram.

### CODE REVIEW

**Comment by titodalcanton** [comment]
Hi Alex, assuming I understand the meaning of the variables in `generate_samples()` correctly, I think:
* `dist` should be a power-2 distribution to get a population uniform in 3-volume
* `inc` should be drawn similarly to `dec` a few lines above to have an isotropic distribution
* `ip` and `ic` seem swapped (at least according to the equations in the FindChirp paper)
* In the computation of `phase_diff`, the arguments to `arctan2` should be swapped (i.e. you should be doing `arctan(cross/plus)`) although I can't tell at the moment if that actually makes a difference to the end result.

**Comment by titodalcanton** [comment]
Also, `dist` on line 69 seems to be redefined in line 92.

**Comment by ahnitz** [comment]
On Fri, Jan 8, 2016 at 6:04 PM, Tito Dal Canton <notifications@github.com>
wrote:

> Hi Alex, assuming I understand the meaning of the variables in
> generate_samples() correctly, I think:
>
>    - dist should be a power-2 distribution to get a population uniform in
>    3-volume
>
>
That's right, but scipy doesn't define the function this way. (they do
value - 1)

See
http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.random.power.html


So this should in fact be the way to get a power 2 distribution.

>
>    - inc should be drawn similarly to dec a few lines above to have an
>    isotropic distribution
>
> Let me think about that. You might be right.

>
>    - ip and ic seem swapped (at least according to the equations in the
>    FindChirp paper)
>
> I used the convention that IMRPhenomD is using.

>
>    - In the computation of phase_diff, the arguments to arctan2 should be
>    swapped (i.e. you should be doing arctan(cross/plus)) although I can't
>    tell at the moment if that actually makes a difference to the end result.
>
> —
>
It shouldn't matter, but I'll check.

> Reply to this email directly or view it on GitHub
> <https://github.com/ligo-cbc/pycbc/pull/672#issuecomment-170057054>.
>



-- 
Dr. Alexander Nitz
Max Planck Institute for Gravitational Physics (Albert Einstein Institute)
Callinstrasse 38
D-30167 Hannover,  Germany
Tel: +49 511 762-17097

**Comment by titodalcanton** [comment]
Aha, I think the `uniform` scipy convention has biten me before but clearly not enough to remember it ;)

A couple more comments:
* In lines 94-98, why can't you just draw all the involved variables `size` times instead of using the `resize()`s?
* In line 98, I wouldn't make the width of the time error dependent on the sample rate. How about setting it fixed to 5 ms, similarly to what we use in the coinc window? But I might have missed some discussion with Tom and Steve here…

**Comment by ahnitz** [comment]
On Fri, Jan 8, 2016 at 6:25 PM, Tito Dal Canton <notifications@github.com>
wrote:

> Aha, I think the uniform scipy convention has biten me before but clearly
> not enough to remember it ;)
>
> A couple more comments:
>
>    - In lines 94-98, why can't you just draw all the involved variables
>    size times instead of using the resize()s?
>
> That's simply for performance. I want to fill out more distance values.
They don't need to be independent in all parameters.

>
>    - In line 98, I wouldn't make the width of the time error dependent on
>    the sample rate. How about setting it fixed to 5 ms, similarly to what we
>    use in the coinc window? But I might have missed some discussion with Tom
>    and Steve here…
>
> I've just made it a command line option.


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ligo-cbc/pycbc/pull/672#issuecomment-170064292>.
>



-- 
Dr. Alexander Nitz
Max Planck Institute for Gravitational Physics (Albert Einstein Institute)
Callinstrasse 38
D-30167 Hannover,  Germany
Tel: +49 511 762-17097

**Comment by ahnitz** [comment]
Ok, I'll think I've incorporated your comments. Please take another pass.

**Comment by titodalcanton** [comment]
Thanks, I think it's good now. Before merging, can you add a new test line for pycbc_stat_dtphase to tools/run_travis.sh?

**Pull request merged**
