### PR TITLE
Pegasus Replica Selector URL to URI

### PR DESCRIPTION
**Pull request by stevereyes01**
Addressing open issue #874, Pegasus replica selector should just select by URI not URL. This should tell pegasus to try using these different URI's rather than a very particular URL.

### CODE REVIEW

**Comment by stevereyes01** [comment]
Should I append also file:///cvmfs/.* to pegasus-properties.conf? What rank should we set it to? 

If so we should add it as another pull request, separate from this one.

**Comment by duncan-brown** [comment]
@stevereyes01 the existing ``file:///`` should get cvmfs, so this should be good when travis and landscape complete.

**Comment by lppekows** [comment]
If there's any possibility of running on Stampede or Blue Waters I think `file:///cvmfs/.*` should be listed separately, my vote would be at the first rank.  This will allow for both `/cvmfs` on OSG and `/scratch/stuart` (or wherever) on Stampede.

**Comment by duncan-brown** [comment]
@stevereyes01 @lppekows ok, sounds good. Then let's do
```
pegasus.selector.replica.regex.rank.1=file:///cvmfs/.*
pegasus.selector.replica.regex.rank.2=file://.*
```
and so on.

**Comment by stevereyes01** [comment]
Commited. @duncan-brown @lppekows

**Pull request merged**
