### PR TITLE
Append the git hash to the weave cache path

### PR DESCRIPTION
**Pull request by lppekows**
Scipy.weave caches based on the code and not additional arguments such as flags or support code.  This can lead to kernels not being properly updated.  This patch adds the git hash to the PYTHONCOMPILED path to ensure that the kernels match the current pycbc version.

### CODE REVIEW

**Comment by ahnitz** [comment]
Larne, 

Can you include the version as well, so that this will for release too?

**Comment by josh-willis** [comment]
So this will lead to a proliferation of different cache directories, correct? And will do so anytime pycbc changes, whether or not the relevant weave code needs recompilation.

Though it would require more work, I guess I would rather see an approach that adds a comment to the weave inline code snippets that pycbc uses, which has the hash of the compilation flags and the support code.  That would cause only those functions that need recompilation to be recompiled. And I think that in general developers who write weave-inline functions should also be aware of the necessary support code and compilation flags.

Do others have thoughts on this approach, at least for the longer-term?

**Comment by lppekows** [comment]
Alex, I've included the version in the path.

Josh, yes, this will lead to additional cache directories, although these files are fairly small and will likely be purged periodically.  Alex also wanted a longer-term solution that hashes all the arguments to weave and there's a FIXME in the code to that effect.  For the moment though this fixes the immediate problem without requiring any code changes or concerns about the performance impact of any more sophisticated solution.

**Comment by ahnitz** [comment]
Josh, I agree that in the long term we should use our own version of the weave inline functions that makes sure to include the support code (and flags too!). In the short term, I think we want to make sure that we can trust the process, even if it will be a bit excessive on the temporary file usage for now. Please feel free to revert this if we have a better solution, but until then I am approving this.

**Pull request merged**
