### PR TITLE
speed up statmap_inj so it doesn't stall out the workflow

### PR DESCRIPTION
**Pull request by ahnitz**
Tito, 

This should address the issues we were having this morning with the statmap_inj jobs not finishing.

### CODE REVIEW

**Comment by ahnitz** [comment]
I hope it should be clear what this change is doing, but it may not be why it should speed it up so much. The two things are two avoid an argsort in the background calculation that is only needed when assigning cumulative numbers to the background triggers, and also to semi-presort the background triggers, so that the later argsort goes faster. (the algorithm it uses can take advantage of partially sorted data).

**Comment by titodalcanton** [comment]
Hi Alex, I'd like to try the change myself and check that results are the same, but if you did that already, I'm happy to merge.

**Comment by ahnitz** [comment]
No, please do check. I just thought it might appear mysterious why this
would make much of a difference.

**Comment by duncan-brown** [comment]
Tested and this works.

**Comment by ahnitz** [comment]
What was the test if I may ask?

**Comment by duncan-brown** [comment]
Running by hand and the files look the same. @titodalcanton reported the same thing in chat. Making the plots now.

**Comment by ahnitz** [comment]
Ok, just wanted to make sure, great.

**Comment by titodalcanton** [comment]
Confirmed, I reran the postproc and the found-missed plots and range-vs-ifar are identical.

**Comment by titodalcanton** [comment]
Oh, and all statmap jobs completed within 30 minutes :)

**Pull request merged**
