### PR TITLE
speed of waveform generation where requested df << required

### PR DESCRIPTION
**Pull request by ahnitz**
rebased from master

### CODE REVIEW

**Comment by ahnitz** [comment]
Looks like some fluctuation in the chisq of short templates. https://www.atlas.aei.uni-hannover.de/~ahnitz/LSC/ahnitz/projects/code_testing/romopt/t2/output/local-site-scratch/html/3._single_triggers/3.05_H1_loudest_triggers/
Compare to without this patch.
https://www.atlas.aei.uni-hannover.de/~ahnitz/LSC/ahnitz/projects/code_testing/q1/filterx/local-site-scratch/html/3._single_triggers/3.05_H1_loudest_triggers/

The change to the chisq is simply to truncate the bins when the waveform says it has reached the stop frequency.

**Comment by spxiwh** [comment]
Is the plan to merge this to master now? I think some small fluctuation in the chisq given that we now tell the code the SEOBNRv2 ending frequency is understandable.

Currently this branch has conflicts though.

**Comment by ahnitz** [comment]
I can rebase. I think it might be worth checking some of the chisq edge
cases, but I would like to start merging this soon.

On Tue, Mar 29, 2016 at 11:56 AM, spxiwh <notifications@github.com> wrote:

> Is the plan to merge this to master now? I think some small fluctuation in
> the chisq given that we now tell the code the SEOBNRv2 ending frequency is
> understandable.
>
> Currently this branch has conflicts though.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ligo-cbc/pycbc/pull/742#issuecomment-202813082>
>



-- 
Dr. Alexander Nitz
Max Planck Institute for Gravitational Physics (Albert Einstein Institute)
Callinstrasse 38
D-30167 Hannover,  Germany
Tel: +49 511 762-17097

**Comment by ahnitz** [comment]
I'm not too worried about minor deviations, but I would like someone (maybe me if I find the time later) why the values should change at all. Does the ring down of the SEOBNRv2_ROM, for example actually have some decaying behavior after the reported end frequency. If it were identically zeros, then I am a bit confused why the values would be different at all.

**Comment by spxiwh** [comment]
You're thinking frequency-domain! The max frequency value is calculated from SEOBNRv2, a time-domain model and is some approximation of the final ringdown frequency. However when FFTing a time-domain model you *will* get non-zero values above the "max-frequency". The ROM approximates this, so there is no reason for it to artificially add 0s where there are not 0s.

.... Simply plotting a SEOBNRv2_ROM waveform in F-domain, will presumably confirm non-zero values all the way up to Nyquist.

**Comment by ahnitz** [comment]
I wasn't sure how the conditioning was happening for the Frequency domain SEOBNRv2_ROM. If it is as you say, then the results all make sense.

**Comment by spxiwh** [comment]
Alright, this has been sitting in the pull request list for some time now. The code my still need a little bit of polishing/testing before using in production, but this doesn't affect code unless you specifically request the new functionality (minor the bug fix with SEOBNRv3 end frequency in chisq).

I am therefore merging this to master now.

**Pull request merged**
