### PR TITLE
Solving issue #436 and allowing for two frame conventions in pycbc_dark_vs_bright_injections

### PR DESCRIPTION
**Pull request by pannarale**
@sfairhur This solves the issue you raised (#436) and also allows dark/bright injections to be separated by interpreting the spin components in the sim_inspiral table in two different frame conventions:
(1) L=(0,0,1) [default], where L is the orbital angular momentum direction
(2) N=(0,0,1) [activated by the --frame-axis-view flag], where N is the line of site direction

### CODE REVIEW

**Comment by spxiwh** [comment]
Hi @pannarale, wherever possible we want to avoid having options specified in jobsetup.py. Is there a reason why these options can't simply be specified in the configuration file? If nothing else that makes tasks like review a *lot* easier.

**Comment by pannarale** [comment]
Hi @spxiwh , I *had* hardcoded them because the EOS choice isn't really an option (only one choice is supported).  Following @sfairhur 's suggestion, they are no longer hardcoded and are specified in the configurations files.  These seems to agree with what you are saying.

**Comment by spxiwh** [comment]
Ah, I've just read this a bit more closely, sorry. The code *automatically* adds all options in the appropriate section of the configuration file to the job. So if you put

```
eos=467.3HB
```

into the ini file, in the section matching the executable tag, it will automatically add it to the job. All the lines 1455 - 1473 of jobsetup.py will add these options *a second time*. I think they can simply be removed.

**Comment by spxiwh** [comment]
Specifically see the function here, which is called on initializing an Executable class:

https://github.com/ligo-cbc/pycbc/blob/master/pycbc/workflow/core.py#L322

**Comment by pannarale** [comment]
Nice, thanks! I'll remove the lines then (for the written record, that's lines 1455 - 1463).

**Pull request merged**
