### PR TITLE
Allow banksim to use HDF input template banks

### PR DESCRIPTION
**Pull request by spxiwh**
This patch allows banksim (and bank verificator) to use HDF input files by using the functionality of the TemplateBank class.

I also remove the `filter_low_freq_cutoff_column` option as this is now handled by TemplateBank, and in the era of HDF template banks (ie. today), this will always be explicitly given in the input file.

This has been tested on XML and HDF inputs.

### CODE REVIEW

**Comment by spxiwh** [comment]
Bump

**Comment by titodalcanton** [comment]
Ian, looks like you forgot to remove the option `--filter-low-freq-cutoff-column` from the ArgumentParser. Other than that it looks good. Do you have a before/after banksim for comparison?

**Comment by spxiwh** [comment]
I've removed the now unused command-line arguments.

**Comment by titodalcanton** [comment]
Don't we still need `--filter-low-frequency-cutoff` though? For reading the PSD, normalizing the signals and falling back in case the bank has no `f_low`?

**Comment by spxiwh** [comment]
Oops, I was too eager! Fixed now.

**Pull request merged**
