### PR TITLE
Omicron inspiral timefreq plot for mini-followups

### PR DESCRIPTION
**Pull request by tjmassin**
Tested in pycbc environment installed from Duncan Brown's newest installation instructions.

Working test call:

python pycbc_plot_Nth_loudest_coinc_omicron.py \
--coinc-file /home/tjmassin/public_html/cbc/DQ/ER7/coinc_trig_omicron_map/H1L1-STATMAP_FULL_DATA_FULL_CUMULATIVE_CAT_12H-1117400416-928800.hdf \
--single-ifo-trigs /home/tjmassin/public_html/cbc/DQ/ER7/coinc_trig_omicron_map/H1-HDF_TRIGGER_MERGE_FULL_DATA-1117400416-928800.hdf \
--tmpltbank-file /home/tjmassin/public_html/cbc/DQ/ER7/coinc_trig_omicron_map/H1L1-BANK2HDF-1117400416-928800.hdf \
--output-file /home/tjmassin/public_html/plot_archive/LHO_loudest_foreground_1.png \
--loudest-event-number 1 \
--omicron-dir /home/tjmassin/triggers/ER7/ \
--ifo H1 \

Example output from this call:

https://sugar-jobs.phy.syr.edu/~tjmassin/plot_archive/LHO_loudest_foreground_1.png

### CODE REVIEW

**Comment by ahnitz** [comment]
Thanks TJ, I'll try it out in the morning, but I do have one question (perhaps for everyone). How stable are the omicron trigger locations? Is this something we can rely on for a run. It seems like we've had to run omicron by hand lately.

**Comment by tjmassin** [comment]
The production directories for O1 should absolutely not change during a run. Omicron is running automatically and Larne has an rsync process to copy the files over to SUGAR (I'll double check that, I've been at LLO for a few weeks). If an Omicron job fails, it'll certainly be restarted so that Detchar tools can run for DQ development, so an offline search shouldn't have to worry about it.

**Comment by andrew-lundgren** [comment]
@ahnitz The Omicron trigger locations are stable, but it seems like you are asking more about how stable the trigger production is. At least the h(t) triggers seem to fail for some time each day. There's some information about how the production works at https://wiki.ligo.org/DetChar/LigoOmicronProduction. If someone wants to volunteer to look into log files and debug stability issues that would be great.

**Comment by lppekows** [comment]
Hi TJ, all,

I’ve obtained the necessary robot certificates, but I haven’t set up the cron jobs to do the sync to sugar.  It’s on the TODO list.

Cheers,

							- Larne

**Comment by ahnitz** [comment]
Thanks TJ, the script looks fine and I was able to do a test example.

**Pull request merged**
