### PR TITLE
Reinstating pycbc_splitbank as executable class

### PR DESCRIPTION
**Pull request by a-r-williamson**
Proposed patch to re-allow the use of pycbc_splitbank in workflows. This is still used in PyGRB as of the beginning of O2.

### CODE REVIEW

**Comment by soumide1102** [comment]
@a-r-williamson The patch looks good to me. The new class `PycbcSplitBankXmlExecutable` is adding in the flexibility to choose between `pycbc_splitbank` and `pycbc_hdf5_splitbank` and thus using hdf or xml banks. Maybe @duncan-brown and @cdcapano would also also want to take a look.

**Comment by a-r-williamson** [comment]
I agree entirely.

**Comment by a-r-williamson** [comment]
@spxiwh Let me know if the current changes are suitable.

**Comment by spxiwh** [comment]
@a-r-williamson I think you missed some dots on the extension here. I fixed this directly, and will merge once sanity checks complete.

**Comment by a-r-williamson** [comment]
Actually, I believe it doesn't matter -- see [`pycbc/workflow/core.py:1025`](https://github.com/ligo-cbc/pycbc/blob/master/pycbc/workflow/core.py#L1025)

The other classes have dots though so style-wise your change is nice.

**Pull request merged**
