### PR TITLE
Add hdf module in io package, update and clean up trig fitting code

### PR DESCRIPTION
**Pull request by tdent**

### CODE REVIEW

**Comment by tdent** [comment]
Hmmm, I don't know why there are so many commits in this request.  I thought I did fetch/merge as desired before opening the request ..

**Comment by ahnitz** [comment]
Ah, I don't think you wanted to do a merge, but a rebase instead. Can you try to do that, and then force push the resulting cleaned up version here?

**Comment by ahnitz** [comment]
Tom,

I've assigned pull request #37 to you because I think it will be needed for your background fitting to be added to a detection statistic pycbc_coinc_findtrigs.

 If your background fit parameters can be saved as an hdf file then it can be passed directly to the coincidence code, and will be available to ranking statistic class. The script can handle multiple such files if we decide to use many additional files, so it looks for a special attribute to add them to a list.

stat_file.attrs['stat'] = YOUR_STAT_NAME

This is how the phase-time correlations are already handled. If you have a chance to take a look at how that is implemented, I think it should help clear up how you can add your fitting factors into pycbc_coinc_findtrigs. 

https://github.com/ligo-cbc/pycbc/blob/master/bin/hdfcoinc/pycbc_coinc_findtrigs#L91

**Comment by tdent** [comment]
I didn't see anything about rebasing on the help pages, and there is no explanation about why this request has come up with so many commits although only the files I actually altered are shown as changed.  Presumably it has something to do with the order in which one creates a fork, creates a branch, syncs, commits changes, pushes, merges, etc., but I don't see a canonical procedure for doing this, at least not a foolproof one for avoiding the situation that seems to have occurred here.  I can try undoing the most recent merge and doing rebase and push instead and see if that makes a difference.

**Comment by tdent** [comment]
now trying to rebase and finding a horrendous series of conflicts (ie lots of them) in zpk.py and future.py .. when i fix the conflicts and continue it just says 'nothing has changed, do you want to skip the patch'

**Comment by ahnitz** [comment]
Hi Tom, in this case, you can try doing an interactive rebase from ligo-cbc/pycbc/master and simply pick your additional commits.

**Comment by tdent** [comment]
Hi Alex, 

I am now mystified as to how to proceed.  I have at present the following remotes:

origin	git@github.com:tdent/pycbc.git (fetch)
origin	git@github.com:tdent/pycbc.git (push)
upstream	git@github.com:ligo-cbc/pycbc.git (fetch)
upstream	git@github.com:ligo-cbc/pycbc.git (push)

I have done 'git fetch upstream' and 'git rebase master' and then waded through a huge bunch of conflicts, with the result that 
the head of my local master seems to be at a commit made on June 2, i.e. 3ee2cde864 'record correct bank_chisq_dof value in output sngl tables'.  I can't see if I need to do something else in order to get to the desired point on my feature branch (if I now merge and/or rebase that against local master), and in any case how to get my local master to be up to date with upstream rather than 2 days behind.  

Please advise as to what instructions or commands to use.  I am simply trying to go through what I thought was the usual procedure for preparing a pull request via a topical branch. 

Tom 
--
-----------------------------------------
Institute for Gravitational Physics
(Albert Einstein Institute)
Callinstr. 38 
D-30167 Hannover, Germany

**Comment by ahnitz** [comment]
Tom,

In your case, you tried.

git fetch upstream
git rebase master

If you do this from your topcial branch, then yes, it won't give you what
you want as you are rebasing from your checkout's master branch. You can
rebase your topical branch from upstream directly by doing,

git rebase upstream/master

If you want to make your version of master match upstream then,

git checkout master
git reset --hard upstream/master


Here is what I normally do.

git fetch upstream
git branch FEATURE upstream/master
git checkout FEATURE
# make commits
git push origin FEATURE
# make pull request

**Pull request closed without merging**
