### PR TITLE
Uberbank workflow

### PR DESCRIPTION
**Pull request by spxiwh**
Hi all,

This is the rest of the changes to implement an uberbank workflow in pegasus. To summarize: This, coupled with #986 #976 and #973, implements the following changes:

GEOM BANK

 * The geometric bank workflow is moved over from glue.pipeline to pycbc.workflow. (#973)
 * The geometric bank workflow is edited to use HDF files (and many less files) for internal data products (output is still XML in standard format) (#986)
 * The geometric bank codes are optimized with some numpy-isation (#986)
 * Support for running the geom bank as a sub-workflow is added (here)
 * The general structure of the geom_bank workflow, and scientific input choices, are unchanged. One should still be able to reproduce previous output with the new code.

SBANK

 * A new sbank workflow generator is created using pycbc.workflow, intended to deprecate the version in lalapps (#976).
 * This workflow uses recent changes in sbank to allow for more flexibility in the workflow (#976 and here)
   * Specifically we now have the concept of multiple parallel stages allowing the bank to built up over time, while the user can monitor the process, the chirp-mass binning is also updated each cycle allowing for more efficiency
   * A "readder" stage is added to ensure the parallel jobs do not place templates at the same point in parameter space.
 * Support is added to allow the sbank workflow generator to run as a sub-workflow as well as a standalone workflow. (here)

UBERBANK (all changes here)

 * A, let's call it "first draft", of the uberbank workflow is added, demonstrating how to tie sbank and geom_bank workflows together.
 * This implementation runs 1 sbank workflow and 1 geom_bank workflow independently at first, and then runs 1 further sbank workflow using input from the original two workflows as a seed bank.
 * It would be good to add more flexibility in the structure, but this makes a start, and we can add functionality as needed.
 * Handling of sub-daxes in pycbc.workflow is not as neat as normal files. We might want to consider extending upon the Dax class in workflow.core to make some of the stuff here a little more automatic.

CONFIG FILES

 * I'm still working an optimal config files for this. Especially sbank now has a bunch of knobs and dials to turn, which we want to do to balance efficiency with coverage.
 * For now I attach a short example ini file, which is not intended to produce a decent template bank, but is intended to demonstrate how this works.

[uberbank_config.ini.txt](https://github.com/ligo-cbc/pycbc/files/375415/uberbank_config.ini.txt)

At the moment it would be good to have some people try to run this, I'll try and provide a more meaningful ini file, and let me know if there are problems/suggestions etc. Please feel free to open pull requests against *this* branch, if you want to include functionality in this patch.

### CODE REVIEW

**Comment by spxiwh** [comment]
There will also be documentation updates needed on the template bank docs page. I'll do that after this is merged and we have reasonable example ini files.

**Comment by spxiwh** [comment]
I also forgot a small tweak to sbank itself that is needed. I will open a lal redmine ticket for that.

**Comment by spxiwh** [comment]
https://bugs.ligo.org/redmine/issues/4503

**Comment by spxiwh** [comment]
https://bugs.ligo.org/redmine/issues/4504

**Comment by ahnitz** [comment]
I've looked through the code and don't see any obvious issues.

**Comment by spxiwh** [comment]
Rebasing branch. This is probably ready to be pushed if there are no objections. Further improvements can go into an additional PR request. Contact me directly if you want to look at the developing uberbank config file.

**Comment by titodalcanton** [comment]
Hi Ian, I think I'm ok with pushing this for now. I'll need to play with it to come up with more suggestions.

Actually I do have a first question. In the config file, it looks like at least a couple different sections take a PSD specification. Do we want the ability to build Frankenstein banks where different stages use different PSDs, or should we have a single top-level PSD specification that is then propagated both to the geom bank and all the sbank stages? The latter choice seems a nice protection against potential errors. It would also lift the need for two different PSD formats (.txt and .xml) as the conversion would be done by a short dedicated job.

**Comment by spxiwh** [comment]
Thanks @titodalcanton. I'll push this now then, and open a second pull request with some further optimizations and the promised documentation updates.

I agree that it is sub-optimal to supply the PSD file in multiple places. Ideally this would be specified somewhere at the top and then the substitute option functionality would be used to fill in options wherever it is needed (this also allows an advanced user to use different PSDs if this is ever needed, but make it more normal to just specify one PSD) ... This is also how things like the channel names are specified in the main workflow. I don't really like the idea of having a job that just processes a file (I'm sorry, I'm going to use the gating-file example in the main workflow as an example of how I do not think this should work). However, as sbank and pycbc take different formats of input this becomes tricky. I think the easiest solution though would be to modify one or both to take the other form of input. Certainly, I think PyCBC should be able to read XML-format PSD files ... and this can now be done without needing PyLAL thanks to Leo, which I think was some of the hesitancy against doing this previously.

**Pull request merged**
