### PR TITLE
Short-term kludge to avoid race condition in weave for pycbc_optimal_snr

### PR DESCRIPTION
**Pull request by lppekows**
Addresses https://github.com/ligo-cbc/pycbc/issues/501

This runs the first instance outside Pool.map in order to force the generation of the weave cache to be single-threaded.  This is the same short-term fix that was used in pycbc_calculate_psd.

### CODE REVIEW

**Comment by titodalcanton** [comment]
Larne, if the first injection happens to fall outside of live time in both detectors, no waveform will be generated and no sigma() will be called. Is the cache still generated in that case?

**Comment by lppekows** [comment]
Hi Tito,

Ah, good point, thanks for drawing my attention to it.  I've added a check for this case.

**Comment by titodalcanton** [comment]
Hmm, what I mean is that `inj_table[0]` could be a "dead" injection falling outside of a lock, or in vetoed time. If that's the case for *both* detectors, then I suspect the call `compute_optimal_snr(inj_table[0])` will effectively do nothing and not create the cache. Unfortunately I don't know how to handle this easily/cleanly...

Also, I took care of `pycbc_calculate_psd` in #570, so you can drop that change.

**Comment by titodalcanton** [comment]
Maybe here's a possible solution: can you easily trigger the creation of the cache in a way that doesn't depend on the input to the script?

**Comment by lppekows** [comment]
Hi Tito,

I think it would be difficult to construct an injection and a PSD, so instead I loop through the injections until I find a live one that triggers weave.  This requires changes to a few lines of existing code, which I would have preferred to avoid, but it's not too bad and I've confirmed it works.

**Comment by titodalcanton** [comment]
Larne, I don't like this solution very much, but let's accept it for now since it's a kludge anyway. Thanks.

**Pull request merged**
