### PR TITLE
Using SGRB-related injections only in PyGRB

### PR DESCRIPTION
**Pull request by pannarale**
This one is for @spxiwh and @a-r-williamson.

PyGRB targets potentially "EM bright" signals only.  Injections to assess the its sensitivity must be performed accordingly.
* Adding the bin/pycbc_dark_vs_bright_injections script: this takes an xml table with injections as an input and separates the injections into potentially EM bright and dim, outputing them in two distinct files.
* Using the new tool bin/pycbc_dark_vs_bright_injections directly in the workflow in order to allow PyGRB to inject SGRB-relevant signals only before the jittering takes place.

### CODE REVIEW

**Comment by pannarale** [comment]
I forgot to include setup.py in here.  It's just one additional line ('bin/pycbc_dark_vs_bright_injections',) in scripts = [.  Once your happy with the changes above, we can take care of setup.py in no time.

**Comment by spxiwh** [comment]
@pannarale if you push the change to setup.py to pannarale:master on top of existing changes it will also show up here.

**Comment by pannarale** [comment]
@spxiwh , thanks! I realized that right after writing my previous messages, but you were faster.

**Comment by duncan-brown** [comment]
Please can you wait to merge until after I get 1.2.0 tagged today?

**Comment by duncan-brown** [comment]
Talked to @sfairhur and this is needed for 1.2.0, so please merge.

**Pull request merged**
