### PR TITLE
fix off by df issue with psd read

### PR DESCRIPTION
**Pull request by ahnitz**
alternate fix to #322

### CODE REVIEW

**Comment by spxiwh** [comment]
Alex, there is a potential issue here: If the PSD was computed *when the PSD input file was written* from an f_lower of (say) 30Hz the outputted PSD file will not be valid below 30Hz (all values = 0). In your method here the value in the df array below 30Hz is now computed, but if the value below 30Hz in the input file is not valid you will get garbage.

Of course there are probably potential issues with doing things as I suggested, as if you then upsample the PSD it will be bad. Maybe one way to at least reduce potential issues here is to not use 0 for values < f_low when calculating a PSD. Why not just set the PSD values < f_low to the PSD value *at* f_low (this also removes the warning in all pycbc_inspiral runs)?

Does this make sense? What do you think? (I am happy to do any necessary coding, once we agree the right approach).

**Comment by ahnitz** [comment]
Ian, 

If you combine my patch, with your suggestion to fill the output with values below the f_low with the value at the f_low, then I am happy. Or were you suggesting something slightly different?

**Comment by spxiwh** [comment]
I was suggesting this as a possibility that I would be happy with, but I also wanted to check if you thought this was the right thing.

If you are agreed I will look at creating a patch to fill the output with values below the f_low with the value at the f_low.

**Comment by ahnitz** [comment]
I agree

**Pull request merged**
