### PR TITLE
Small bug fixes

### PR DESCRIPTION
**Pull request by lppekows**
This fixes two minor unrelated problems
  * pycbc_single_template needs the MKL libraries
  * The output to pycbc_page_coincinfo was specified as  "html" instead of "png", causing it to fail with "unsupported format."

### CODE REVIEW

**Comment by ahnitz** [comment]
Larne, 

This isn't right. It does make an html page! Can I see the error specifically?

**Comment by lppekows** [comment]
Hi Alex, you can see the error in context here http://sugar-dev3.phy.syr.edu/pegasus/u/lppekows/r/162/w/2/browser?init_file=page_coincinfo-FULL_DATA_FULL_CUMULATIVE_CAT_123H_FULL_DATA_FULL_BIN_1_0-H1L1_ID150_ID0000175.out.003 

Running from the command line:
```
pycbc_page_coincinfo       --single-trigger-files       H1-HDF_TRIGGER_MERGE_FULL_DATA-961545543-21600.hdf       L1-HDF_TRIGGER_MERGE_FULL_DATA-961545543-21600.hdf       --statmap-file       H1L1-STATMAP_FULL_DATA_FULL_CUMULATIVE_CAT_123H_FULL_DATA_FULL_BIN_1-961545543-21600.hdf       --bank-file       H1L1-BANK2HDF-961545543-21600.hdf       --n-loudest       0       --output-file       H1L1-PAGE_COINCINFO_FULL_DATA_FULL_CUMULATIVE_CAT_123H_FULL_DATA_FULL_BIN_1_0-961545543-21600.html
...
ValueError: Format "html" is not supported.
Supported formats: eps, jpeg, jpg, pdf, pgf, png, ps, raw, rgba, svg, svgz, tif, tiff.
```

Replacing the suffix with '.png' works.  However, the resulting plot just has "no triggers found" so maybe the real problem is an edge case in pycbc_page_coincinfo ?

**Comment by ahnitz** [comment]
Ok, thanks larne. I'll take a look. Do you have the results page after you hacked this 'fix in' that would quickly verify my guess of wha tis happening.

**Comment by lppekows** [comment]
Not yet, I got the run to proceed by doing
```
for sub in `find . -follow -name \*sub | xargs grep -l pycbc_page_coincinfo`; do echo $sub ; sed -i s+html+png+g $sub; done
````
and verified that it got past these jobs, but the result page hasn't been generated yet.

**Comment by ahnitz** [comment]
Ok, larne, can you try using my patch here instead? #373

**Comment by lppekows** [comment]
https://github.com/ligo-cbc/pycbc/pull/373 fixes the underlying problem I had misdiagnosed, I've reverted the change to the workflow generator.

**Pull request merged**
