### PR TITLE
add segments-method to analyze all single ifo time or coinc time

### PR DESCRIPTION
**Pull request by ahnitz**
Tom,

Here is the patch to add back the analyze coinc time only option. I'll let you and Ian decide if this is an ok state to merge to this function, even if it isn't perfect.

### CODE REVIEW

**Comment by spxiwh** [comment]
Okay, let's merge this now to ensure functionality is there for O1.

**Comment by tdent** [comment]
Hi Alex, Ian - 
 OK, now where is the appropriate place to document this?  It's not totally clear to me how it fits in with or replaces the existing options shown in https://ldas-jobs.ligo.caltech.edu/~cbc/docs/pycbc/workflow/segments.html ... ?

**Comment by spxiwh** [comment]
Hi Tom,

Yes, at the moment there is a discontinuity between the documentation of
the segments module and the functions that the HDF5 code is actually using,
as well as some duplication between the HDF5 and sqlite use cases. There is
an ongoing issue to merge this together:

https://github.com/ligo-cbc/pycbc/issues/127

which includes updating the documentation, but as Alex is writing thesis
and I am on vacation in one week from now it is unlikely that this will be
resolved before the end of this month.

Cheers
Ian

**Comment by tdent** [comment]
OK.  In general we should be referencing related issues so that the overall state of things is clear(er). 
In the meantime can I try using this new method to set up a hdf workflow?

**Comment by spxiwh** [comment]
Hi Tom,

Apologies, the reference is here now. You can test this method now. Be aware of #176 though!

Cheers
Ian

**Pull request merged**
