### PR TITLE
Durationstuff

### PR DESCRIPTION
**Pull request by tdent**
Addresses issue #1273 
These changes are likely required to use the template duration (or some other quantity stored in trigger files) as noise distribution parameter for the background fitting stat

### CODE REVIEW

**Comment by duncan-brown** [comment]
@tdent should these be in 1.5.10? If so, please add the milestone.

**Comment by tdent** [comment]
I don't know.  What is the alternative to their being in 1.5.10 and what are the consequences? 
We don't need any changes to analyze with the O1 uberbank; we will need (some of) them to use a larger (either in spin or mass) bank.

**Comment by duncan-brown** [comment]
@tdent it would be nice if 1.5.10 could do a full analysis with the bank we plan to use for O2, but if this hasn't been tested and the relevant changes made to the ini files yet, I would rather wait for 1.6.0 as we need a 1.5.x release that can get through all of the pre-ER10 data without failing (which we currently don't have).

**Comment by tdent** [comment]
I am currently testing the changes to *modules* as far as they affect inspiral jobs (should be zero change to the output).

**Comment by titodalcanton** [comment]
Tom, I only looked at the changes *not* involving your `*_fit_*` executables and they look ok. An optional cosmetic change: how about renaming the "length_in_time" functions to "duration"?

**Comment by tdent** [comment]
so far I was considering the waveform functions as being 'length' and the pnutils ones as 'duration' .. it might make sense to have them all be 'duration' but that would blur the distinction between waveform module functions and pnutils ones

**Comment by tdent** [comment]
@duncan-brown why can't current version get through ER10 data without failing ?  if a bugfix is required it should be made asap.  The O2 variable low freq hyperbank is *not ready yet* so I am considering work to adapt the trig fitting to it as ongoing (hopefully quick) development.

**Comment by duncan-brown** [comment]
Please hold off merging until after 1.5.10 release.

**Comment by tdent** [comment]
An end-to-end test on uberbank chunk3 is here : https://www.atlas.aei.uni-hannover.de/~tdent/LSC/tests/chunk3_combined_er10_trigduration/ 
Should be identical as I have just replaced the calculated-on-the-fly durations with those stored in the trigger files.

**Comment by duncan-brown** [comment]
@tdent https://github.com/ligo-cbc/pycbc/pull/1282 set us back to development, so go ahead when you're ready Tom.

In answer to your question, https://github.com/ligo-cbc/pycbc/pull/1262 broke 1.5.9 and https://github.com/ligo-cbc/pycbc/pull/1276 is needed to fix this.

**Comment by tdent** [comment]
The setting to calculate duration from a fixed cutoff with the SEOBNRv4 formula was tested here:
https://www.atlas.aei.uni-hannover.de/~tdent/LSC/er10/tuning/er10_preh1_vlfc2_o1imbhchisq2/ 
Is anything else needed for the merge?

**Pull request merged**
