### PR TITLE
Remove io.sqlite module

### PR DESCRIPTION
**Pull request by titodalcanton**
On #1686, @ahnitz made the point that `io.sqlite` is no longer needed, so here is the patch to remove it. Since it is still imported by @tdent's code, he gets to be the assignee :)

### CODE REVIEW

**Comment by ahnitz** [comment]
@titodalcanton My guess is that script can be removed too.

**Comment by spxiwh** [comment]
Can we remove:

bin/mvsc/pycbc_mvsc_update_sql

as well? (Or that entire directory?)

**Comment by titodalcanton** [comment]
How about Alex and Ian's comments @tdent ? Should I just drop the script and/or MVSC stuff or would you rather keep them around?

**Comment by tdent** [comment]
Hi, I approved this pull request as it stands, if people would like other changes it is probably better to put in a separate request.

**Pull request merged**
