### PR TITLE
update inferece doc with PSD_INVERSE_LENGTH

### PR DESCRIPTION
**Pull request by Cyberface**
also added OMP_NUM_THREADS=1 before calling pycbc_inference

### CODE REVIEW

**Comment by Cyberface** [comment]
Hey @cdcapano I don't have the power to assign people PRs so I am pinging you.

**Comment by cdcapano** [comment]
@Cyberface I'll assign Chris... but before I do, could you add the change to the segment length and the number of walkers too?

**Comment by cdcapano** [comment]
@ahnitz Can you give @Cyberface the ability to assign people himself?

**Comment by cmbiwer** [comment]
To me ``OMP_NUM_THREADS=1`` is a slightly technical thing. It think it would be nice if it was on a line up with a comment to explain it. Maybe something like:
```
# specifies the number of threads for OpenMP
```

**Comment by Cyberface** [comment]
OK updated, what do you think?

**Comment by cmbiwer** [comment]
Thanks! I also agree with Collin that the number of walkers and iterations needed to be changed to something like those values. I'll merge.

**Comment by cdcapano** [comment]
@cmbiwer About the `OMP_NUM_THREADS` thing... OpenMP is apparently turned on by default in lalsimulation. I found that this can interfere with `pycbc_inference`'s parallelization, at least when using the SEOBNRv2 ROMs. Basically, every time each process generates a waveform, lalsimulation tries to spawn off several parallel jobs to generate the waveform. But that just robs resources from the other processes that `pycbc_inference` has created for multiple walkers. This can lead to a substantial slow-down. The only way to stop lalsimulation from doing that is to either build without omp support (not sure how to do that, and since it's not a default, I'm guessing most users won't either), or manually set the environment variable `OMP_NUM_THREADS=1`. Putting that just before the call to the executable causes the variable to just be set for that executable, so it won't affect anything else someone might be running.

Anyway, yeah, I suppose we could stick something in the documentation about that. Do you want it in this PR, or a new one?

**Comment by cdcapano** [comment]
@Cyberface You still need to change `SEGLEN=8`.

**Comment by cmbiwer** [comment]
@cdcapano Oh yeah, that would be good to document.

If @Cyberface is willing to add it to this PR then by all means please add a bit about lalsimulation and OpenMP.

Otherwise, I could add it later this week if no one else gets around to it.

**Comment by Cyberface** [comment]
Sorry guys I don't know what to do about the ```OMP``` stuff. Did you want me to remove it from the pycbc_inference execution

**Comment by cdcapano** [comment]
@Cyberface No, leave it there. We were saying that an explanation for it should be added to the text after the example, since it might confuse people. If you like, feel free to add something that summarizes what I said above. If not, don't worry about it; @cmbiwer or I will file a new patch for that after this is merged.

**Comment by Cyberface** [comment]
OK updated with a short comment on ```OMP```

**Comment by cdcapano** [comment]
@ahnitz Why isn't this passing the Travis build test? It's just a change to the doc file.

**Pull request merged**
