### PR TITLE
Chunkread

### PR DESCRIPTION
**Pull request by ahnitz**
Start a superclass of the h5py.File object to we can add low level query type functionality. I also add a "select" function that allows one to get columns from and hdf5 file that satisfy some sort of function that returns a boolean. 

Here is an example, 
f = HFile(filename)
snr = f.select(lambda snr: snr > 6, 'H1/snr')

Read in an get only the SNR values above 6. Does not read in all the values at once, which should allow people to write code that uses a lot less memory when making plots, etc. Any function may be given as long as it returns a boolean array the same length as your vector(s).  The following also works.

snr, time = f.select(labmda snr, time: time > 1000000, 'H1/snr', 'H1/end_time')

This should be integrated into the SingleDetTriggers class in the future and others. I'll let the authors of those classes decide how best to do that.

### CODE REVIEW

**Comment by tdent** [comment]
Looks OK.  Could you define 'chunksize' outside the class though (i.e. as a module level variable) .. and/or make it a kwarg to the select function?  In case someone might want to control its value.

**Comment by titodalcanton** [comment]
An optional arg to HFile.__init__() would be best IMO.

**Comment by ahnitz** [comment]
At the moment, I'd like to see if we can get by without changing it. I'd
prefer if people didn't have to think about it. I think the current value
should eliminate memory concerns. The downside will be in processing speed,
but I think 1000000 element operations should be ok for that too. I'd
prefer to put this request in the if we find a need pile.

On Wed, Feb 10, 2016 at 4:11 PM, tdent <notifications@github.com> wrote:

> Looks OK. Could you define 'chunksize' outside the class though (i.e. as a
> module level variable) .. and/or make it a kwarg to the select function? In
> case someone might want to control its value.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ligo-cbc/pycbc/pull/701#issuecomment-182417157>.
>



-- 
Dr. Alexander Nitz
Max Planck Institute for Gravitational Physics (Albert Einstein Institute)
Callinstrasse 38
D-30167 Hannover,  Germany
Tel: +49 511 762-17097

**Comment by tdent** [comment]
No-one's saying users should *have* to think about it.  It's just clearer to use explicitly declared default values rather hard-coded constants.

**Comment by tdent** [comment]
Please add the chunk size as a kwarg with default value to the select() method. 
Has the replacement been tested to be safe inside e.g. a plotting code?

**Comment by ahnitz** [comment]
Ok, keyword argument added. Please take another look.

**Comment by ahnitz** [comment]
Tom, any update on this?

**Comment by tdent** [comment]
I haven't managed to test it yet.  A reasonable test case would be one of the hex bin plot things (in terms of 'does it break the existing convenience classes')

**Comment by titodalcanton** [comment]
I verified that the hex bin plots are unchanged. I'm merging now so we can start developing on top of this.

**Pull request merged**
