### PR TITLE
add mass bins to workflow

### PR DESCRIPTION
**Pull request by ahnitz**
This rolls up #223  and #222 and adds basic mass bins into the workflow. They can be controlled by setting. 

```
[workflow-coincidence]
background-bins = LOW-mchirp-3.48 HIGH-mchirp-6.3

[combine_statmap]
cluster-window = CLUSTER_WINDOW ; Time window to cluster the triggers from the mass bins
```
Please let me know ASAP if you guys think this is a sensible way to present the results and if there should be modifications to other plots/ new plots to be able to understand a mass binned search.

### CODE REVIEW

**Comment by spxiwh** [comment]
As I think this requires Tom's approval of #223 I will wait until that is approved before looking over this. Thanks!

**Comment by titodalcanton** [comment]
Alex, I agree that a plot of the bank would be useful, even without mass bins. Is there a reason why you're calling them "mass bins"? Do we not want the ability to split by spin or any other arbitrary parameter? I suspect splitting by something like the SEOPeak frequency could be useful.

**Comment by cdcapano** [comment]
Yeah, I agree, I don't think we want to limit ourselves to mass. Can this patch do arbitrary parameters? If so, should the argument be called "param-bins"?

**Comment by ahnitz** [comment]
Tito, Collin, if you'd like to separate by something other than mass you'll wan to edit #222, which at the moment is very simple. It selects templates to calculate separate backgrounds for. I'll push through and test "mass" bins, but please feel free to generalize this if you'd like, and rename the options/executables to match.

**Comment by cdcapano** [comment]
Hi Alex,

Yeah, I’d like to take a crack at it during/after the LVC meeting.

Collin

On Aug 28, 2015, at 2:03 PM, Alex Nitz <notifications@github.com<mailto:notifications@github.com>> wrote:


Tito, Collin, if you'd like to separate by something other than mass you'll wan to edit #222<https://github.com/ligo-cbc/pycbc/pull/222>, which at the moment is very simple. It selects templates to calculate separate backgrounds for. I'll push through and test "mass" bins, but please feel free to generalize this if you'd like, and rename the options/executables to match.

**Comment by ahnitz** [comment]
Hi All, 

I've tweaked the plotting to hopefully make more sense in the multiple mass bin scenario.

Here is an example page. 

https://sugar-jobs.phy.syr.edu/~ahnitz/projects/bigdog_rerun/test/w12/gw/html/

**Comment by ahnitz** [comment]
Collin, 

I've renamed the executables and options from 'mass-bins' to a more generic 'background-bins'.  I agree we might want to bin based on spin or some other boundary. 

The binning functionality is entirely contained in a single function, so please look there if you'd like to modify the syntax or improve the functionality. 

https://github.com/ahnitz/pycbc/blob/mbins/pycbc/events/coinc.py#L31

**Comment by spxiwh** [comment]
Am I still waiting on #223 on this? Or should I check this now?

**Comment by ahnitz** [comment]
Ian, I'd appreciate if you check it now. I'll be gone for the next week, so you all might need to make fixes if you find any problems.

**Pull request merged**
