### PR TITLE
New program to re-weight injections by optimal SNR

### PR DESCRIPTION
**Pull request by micamu**
Script that reads the optimal SNR from an xml file and re-draws injection distances based on the optimal snr.
Histograms here https://www.atlas.aei.uni-hannover.de/~miriam.cabero/LSC/tests/edit_xml/

### CODE REVIEW

**Comment by cbc-sugar** [comment]
@micamu can you give the script a more descriptive name? You'll also need to add it to setup.py, i think.

**Comment by cdcapano** [comment]
@micamu @duncan-brown How about 'pycbc_rand_dist_by_optsnr'?

**Comment by duncan-brown** [comment]
What about

pycbc_randomize_inj_dist_by_optsnr

we already have

pycbc_make_coinc_search_workflow

so long names are fine.

> On Nov 5, 2015, at 9:50 AM, Collin Capano <notifications@github.com> wrote:
> 
> @micamu @duncan-brown How about 'pycbc_rand_dist_by_optsnr'?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 

Duncan Brown                      http://www.gravity.phy.syr.edu/~duncan
Associate Professor of Physics         Room 263-1, Department of Physics
Director of the Graduate Program      Syracuse University, NY 13244, USA
Phone: 315 443 5993                                    Fax: 315 443 9103

**Comment by micamu** [comment]
@cdcapano @duncan-brown when you decide on a name, I'll change it and add it to the setup.py

**Comment by micamu** [comment]
@duncan-brown @cdcapano Renamed and added to setup.py

**Comment by titodalcanton** [comment]
Miriam, it's good practice to have something more descriptive in the commit message than 'script for collin'... Something like 'Script for redrawing injection distances based on optimal SNR' would be better.

**Comment by micamu** [comment]
@titodalcanton I know, you have already told me that before. When I used that commit message, I didn't know Collin was planning to merge to master, and then I forgot to change the message later...
@duncan-brown @cdcapano Script renamed with Duncan's suggestion and added to setup.py

**Pull request merged**
