### PR TITLE
Call to ChooseT(F)DWaveform compatible with new interface.

### PR DESCRIPTION
**Pull request by sturani**
Waveform call now compatible with New ChooseWaveform interface.

### CODE REVIEW

**Comment by ahnitz** [comment]
@sturani The landscape report is saying that you have misnamed some variables? Can you patch that? Also, please avoid camelCase for variable names.

**Comment by ahnitz** [comment]
@sturani Riccardo, we'll consider merging this once lalsuite master has also been updated.

**Comment by duncan-brown** [comment]
@sturani @ahnitz @tdent do we need this for O2? Will the changes be made in LALSuite?

**Comment by tdent** [comment]
I don't see a reason why we would *need* it in O2.  However, in order for our injected waveforms not to drift further from other analyses, it should probably be done at some point.  It will be (or already has been) pushed to lalsuite master.

**Comment by duncan-brown** [comment]
@tdent yes, we'll need it if we rebase our lalsuite release to master:
```
Hi All,

I've just pushed to master the NewChooseWform interface, with all its
consequences.
def92e2f7fabb41fe1d4332d5effebfb9973523b
Cheers,

R
```

**Comment by sturani** [comment]
Agree with Tom, it is not needed for O2 but should be done at some point.
And yes, it has been pushed to the master branch of LALsuite about 10hrs
ago.
Cheers,

R

Il 10 nov 2016 12:21, "tdent" <notifications@github.com> ha scritto:

**Comment by duncan-brown** [comment]
In order for this to work, the travis lalsuite checkout needs to be updated. I open a new pull request with this in https://github.com/ligo-cbc/pycbc/pull/1224 to trigger the build and test.

**Comment by ahnitz** [comment]
@duncan-brown If you need to update this, the right method is to create a pull request against Riccardo's branch and have him accept that. Please don't close his pull request and open your own. It's important that people get some credit for the work they've put in on the code side, especially if it isn't from one of the primary developers.

**Comment by duncan-brown** [comment]
@ahnitz look at the way I did it in the other pull request. @sturani will get credit because git does this properly.

**Comment by duncan-brown** [comment]
Having two pull requests is confusing, and this pull will never pass the travis tests. Closing and we can follow Ian's suggestion of doing a rebase and merge on https://github.com/ligo-cbc/pycbc/pull/1224

**Pull request closed without merging**
