### PR TITLE
set site to nonlocal if file is not accessible

### PR DESCRIPTION
**Pull request by ahnitz**

### CODE REVIEW

**Comment by ahnitz** [comment]
Hmmm, I think that might have unintended effects. If you have a file with the same path on your local system then you may choose the wrong file. We'd have to carefully parse that the machine you are running on *is* the host in the path, which I think would also be an uncommon case. If one really wants it to be treated as a local file, one should give a standard path. i.e. isfile *should* fail if you give a url.

**Comment by duncan-brown** [comment]
@ahnitz agreed. How about any URI other than ``file://`` triggers a ``nonlocal`` and you check that it exists for a ``file://`` URL?

**Comment by duncan-brown** [comment]
@ahnitz My algorithm above would work if we make the same assumption that pegasus does that a filename uniquely identifies a file. This is true for frame files, and true for files *within* a workflow.

However, there's a bigger problem here. The file is just called ``phasecorr.hdf`` with no other identifying information. I think that needs to be fixed before ER10. It should contain, at a minimum:

- A reasonably unique filename. Storing metadata in filenames is bad practice technically, but helpful for humans who use ``ls``. Ideally it should have a standard filename that explains where it came from, and maybe some version string, e.g. ``H1L1-PHASECORR_O2_V1-10000000000-10000.hdf``
- The HDF file itself should contain metadata that can be verified against the filename so that the review can make sure that the correct file was used.

I will file an issue for this.

**Comment by spxiwh** [comment]
Having hit this issue, I now understand the point of this. We are trying to pull in a remote file for the phase-time correlation data, but this currently doesn't work in the `file-input-options` scheme in workflow.py.

I agree with Duncan that this filename should probably be changed, but that isn't the point of this pull-request.

TO both @duncan-brown and @ahnitz : Please be clearer with the point of pull-requests and issues. This one has no description whatsoever, and #1163 begins with "the file" without saying what "the file" is.

As this is needed to make the workflow work now, I'm going to merge this.

**Pull request merged**
