### PR TITLE
Allow pycbc_inference_plot_movie to use transforms.py

### PR DESCRIPTION
**Pull request by cmbiwer**
As title says.

### CODE REVIEW

**Comment by micamu** [comment]
@cdcapano @cmbiwer could you merge PR #1685 before we do further changes into pycbc_inference_plot_movie?

**Comment by micamu** [comment]
@cmbiwer have you tested if it works fine?

**Comment by cmbiwer** [comment]
I've merged #1685.

Yeah I've used this PR but there's something up with Travis failing for a few PRs I submitted the same day as this one. I've restarted the check.

**Comment by cmbiwer** [comment]
Just pushed a fix for a missed ``opts.output_file`` --> ``opts.output_prefix``.

**Comment by micamu** [comment]
Oh no, I see now when I changed ```output-file``` --> ```output-prefix```  in the PR you just merged, I didn't change ```opts.output_file``` --> ```opts.output_prefix``` ! You fixed one, but there are a couple more (sorry, my bad).
Do you want to rebase and fix it? Or should I just merge this PR and then fix this issue myself?

**Comment by cmbiwer** [comment]
Ok Miriam, I rebased to pick up your new additions and changed it to ``output_file``. I think that's it but if there are any more, then make a PR and I approve it.

**Comment by micamu** [comment]
Looks good, thanks!

**Pull request merged**
