### PR TITLE
Cython

### PR DESCRIPTION
**Pull request by ahnitz**
As suggested by Duncan M. , add cython to setup_requires if needed for h5py. 

Tom, 

Please let me know if this fixes your issue.

### CODE REVIEW

**Comment by tdent** [comment]
Since I did pip install cython I don't get the error any more, should I try to uninstall it to reproduce the error?

**Comment by ahnitz** [comment]
To reproduce, you'll have to uninstall both cython and h5py. 

pip uninstall cython
pip uninstall h5py

**Comment by tdent** [comment]
OK, having done that and applied the patch shown here, I get an error: 

    $ python setup.py install --user
    Traceback (most recent call last):
    File "setup.py", line 73, in <module>
    if h5py.__version__ < '2.5':
    AttributeError: 'module' object has no attribute '__version__'

**Comment by ahnitz** [comment]
Ok, please try again now.

**Comment by tdent** [comment]
This seems to work OK, please merge when ready

**Pull request merged**
