### PR TITLE
Submit

### PR DESCRIPTION
**Pull request by ahnitz**
Add accounting group option to pycbc_submit_dax*. 

The syntax is as follows

pycbc_submit_dax --dax test.dax --accounting-group test.tags.alex.workflow

### CODE REVIEW

**Comment by duncan-brown** [comment]
There are a couple of bugs. You need to tell getopt about the long option, i.e.

GETOPT_CMD=`getopt -o d:c:a:h --long dax:,cache-file:,accounting-group:,help -n 'pycbc_submit_dax' -- "$@"`

and it looks like you didn't modify the command in the stampede version of the script. It's probably a good idea to also check and see if it has been set, and throw an error if not. See the way I handle the DAX for this.

**Comment by ahnitz** [comment]
I found another bug. You change the submti file directory to the following.

#Make a directory for the submit files
SUBMIT_DIR=`mktemp -d pycbc-tmp.XXXXXXXXXX`

This will place it in the current directory with a random extension. Is
this what you intended?

**Comment by duncan-brown** [comment]
No, I didn't mean that. Can you add the -t option so it does the right thing? I added the template so it's OS X compatible.

**Comment by ahnitz** [comment]
Are there OSX head nodes?

**Comment by ahnitz** [comment]
Change made.

**Comment by duncan-brown** [comment]
> On Jun 11, 2015, at 12:23 PM, Alex Nitz <notifications@github.com> wrote:
> 
> Are there OSX head nodes?

I have condor installed on my desktop, so I should be able to submit to other sites from there.


> 
> On Thu, Jun 11, 2015 at 12:22 PM, Duncan Brown <notifications@github.com>
> wrote:
> 
> > No, I didn't mean that. Can you add the -t option so it does the right
> > thing? I added the template so it's OS X compatible.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ligo-cbc/pycbc/pull/57#issuecomment-111192146>.
> >
> —
> Reply to this email directly or view it on GitHub.
> 

-- 

Duncan Brown                      http://www.gravity.phy.syr.edu/~duncan
Associate Professor of Physics         Room 263-1, Department of Physics
Director of the Graduate Program      Syracuse University, NY 13244, USA
Phone: 315 443 5993                                    Fax: 315 443 9103

**Comment by ahnitz** [comment]
Well, I decided not to remove Mac OSX compatibility, and I've gotten this to work on a test run. May this merge?

**Pull request merged**
