### PR TITLE
Adding IPN sky boxes to PyGRB workflow

### PR DESCRIPTION
**Pull request by a-r-williamson**
Hi @sfairhur ,

This change will allow the workflow to retreive IPN sky box files from the GitLab repo at runtime if the urls are given in the arguments:

[workflow-inspiral]
ipn-search-points = <search-points-url>

[workflow-injections]
ipn-sim-points = <sim-points-url>

The search points are then passed to `lalapps_coh_PTF_inspiral --sky-positions-file <search-points-file>`

The sim points are passed to `lalapps_inspinj --ipn-file <sim-points-file>`

Cheers,
Andrew

### CODE REVIEW

**Comment by sfairhur** [comment]
The changes look fine, but the if statements around line 1445 of jobsetup.py are rather complicated.  Can you try to find a way to simplify the compound if statement?

**Comment by a-r-williamson** [comment]
@sfairhur Thanks.
I've made some changes to these conditional statements with some comments. Any better?

**Comment by pannarale** [comment]
Hi Andrew,

I looked at this too last night and the only suggestion I have is to simplify get_ipn_sky_files.  In there, you are essentially repeating the same set of operations twice, once using "ipn-search-points" and "SEARCH_POINTS", and a second time using "ipn-sim-points" and "SIM_POINTS."  get_ipn_sky_files could be turned into a function get_ipn_sky_file to be called twice at line 166 of pycbc_make_offline_grb_workflow:
search_pts_file = _workflow.get_ipn_sky_files(wflow, "ipn-search-points", "SEARCH_POINTS")
sim_pts_file = _workflow.get_ipn_sky_files(wflow, "ipn-sim-points", "SIM_POINTS")

Francesco

**Comment by a-r-williamson** [comment]
Ok, I agree partly, but would want to keep the description linked to the option. So:

search_pts_file = _workflow.get_ipn_sky_files(wflow, "ipn-search-points")
sim_pts_file = _workflow.get_ipn_sky_files(wflow, "ipn-sim-points")

and the description string is set in the function.

I'll get round to making that change this afternoon.

**Pull request merged**
