### PR TITLE
Rework CPU clustering to use simplified but possibly slower algorithm…

### PR DESCRIPTION
**Pull request by josh-willis**
This pull request is to implement the time-symmetric clustering algorithm, but a simplified form which does not attempt to be performance optimal when the clustering window is large.  It should still be accurate in that case however.

Aside from the Travis build, this needs to be checked with injection runs to verify that there are no suspicious missed injections before merging.

### CODE REVIEW

**Comment by duncan-brown** [comment]
@josh-willis I'll merge this when the travis checks complete, as it does not make the code worse, and does not affect FindChirp clustering, which is our fallback.

**Comment by josh-willis** [comment]
So to test this we would actually need to undo the revert that causes MatchedFilter to fall back to the old clustering method; should I update this pull request with that, or will Soumi or you do that manually when you do your runs?

**Comment by duncan-brown** [comment]
@josh-willis can we make this a command line argument so it can be set in the ini file? Do you want to add that to this pull request?

**Comment by duncan-brown** [comment]
Looks good @lppekows please merge once Travis checks are complete.

**Comment by josh-willis** [comment]
I've updated this with a command line option, 'cluster-function', which should be either 'findchirp' for the old S6 method, or 'symmetric' for the newer one.  It might have seemed more logical to call this 'cluster-window' but that option was already in use to toggle between template and fixed window clustering.

**Pull request merged**
