### PR TITLE
Re-wrote the install documentation to use virtualenv

### PR DESCRIPTION
**Pull request by duncan-brown**
These patched replace the old install instructions with new ones that are based on using virtualenv. They are built at 

https://sugar-jobs.phy.syr.edu/~dbrown/pycbc-docs/install.html

for testing.

### CODE REVIEW

**Comment by lppekows** [comment]
The "setting up pip and virtualenv" page assumes python 2.6, but Atlas is on 2.7 (not to mention users might want to install on their own machines).  It might be worth noting this, or if you want something that can be cut-and-pasted maybe

**Comment by duncan-brown** [comment]
Thanks Larne, the patches above fix that, as well as the issue reported by Andrew. I'll ask Heather to test the CUDA documentation today.

**Comment by duncan-brown** [comment]
Andrew, since you've tested, please can you merge?

**Comment by a-r-williamson** [comment]
Hi Duncan,

Sorry, been teaching a workshop this afternoon so not getting emails. I see
Larne merged, thanks.

Andrew

**Pull request merged**
