### PR TITLE
banksim modified to take psd-file directly

### PR DESCRIPTION
**Pull request by alex-nielsen**
instead of take psd file directly add psd.from_cli

### CODE REVIEW

**Comment by spxiwh** [comment]
Yay, thanks for doing this! Can we do faithsim at the same time? Some suggestions though, you should add the verify options line:

https://github.com/ligo-cbc/pycbc/blob/master/bin/pycbc_geom_nonspinbank#L91

You should probably also add the strain arguments (and their verify group, and the reading group as in):

https://github.com/ligo-cbc/pycbc/blob/master/bin/pycbc_geom_nonspinbank#L73

https://github.com/ligo-cbc/pycbc/blob/master/bin/pycbc_geom_nonspinbank#L92

https://github.com/ligo-cbc/pycbc/blob/master/bin/pycbc_geom_nonspinbank#L105

so that the --psd-estimation option will work.

**Comment by alex-nielsen** [comment]
I added the lines that Ian requested

**Comment by spxiwh** [comment]
Hi Alex,

Thanks, I think you also need to send the strain object to psd.from_cli and then I'm happy:

https://github.com/ligo-cbc/pycbc/blob/master/bin/pycbc_geom_nonspinbank#L119

Cheers
Ian

**Comment by alex-nielsen** [comment]
Hi Ian, see the new commit and notice Tito has assigned this to you.

**Comment by spxiwh** [comment]
Okay, thanks! Please merge this once the checks are complete.

**Comment by alex-nielsen** [comment]
Checks have passed. I can merge it if someone gives me permission.

**Comment by duncan-brown** [comment]
Go for it.

**Comment by tdent** [comment]
Alex doesn't have a big green button on his version of this page saying 'merge pull request' and neither of us can work out why.  (I have one, for instance.)  Anyway, I may as well do it myself

**Pull request merged**
