### PR TITLE
Pylalectomy : no longer use pycbc-pylal functions in binned volume integral

### PR DESCRIPTION
**Pull request by tdent**

### CODE REVIEW

**Comment by tdent** [comment]
@duncan-brown what has to occur in order to proceed with this?

**Comment by duncan-brown** [comment]
@tdent please can you fix the landscape error then I can merge?

**Comment by tdent** [comment]
Landscape indicates 85 issues, mostly docstring formatting from copied pylal code, some are overwriting of builtins, overall will take some time to fix.  Will proceed with this but not as first priority.

**Comment by tdent** [comment]
actually, having 'self.min' and 'self.max' methods all over the place is pretty awful .. I'm definitely fixing that

**Comment by tdent** [comment]
ok, rebased a few hours ago and all checks look happy.

**Pull request merged**
