### PR TITLE
Scatter plots of the ln(likelihood) and histograms for results from inference

### PR DESCRIPTION
**Pull request by micamu**
The module scatter_histograms in pycbc.results can be used for any data consisting of a set of parameters with a z-value to generate figures with scatter plots of each possible combination of the parameters and histograms for each individual parameter.

pycbc_inference_plot_lnpost uses this module to generate a single figure. Example:
https://www.atlas.aei.uni-hannover.de/~miriam.cabero/LSC/ringdown/single_mode/real_gw150914/fix_pol_fromPE/fixed_prior_at_tc_3ms/newplot_example.png
The lines in the histograms represent the 5th and 95th percentile (i.e., the 90% interval), and the median value of the data.

pycbc_inference_plot_movie generates as many figures as given in the option --movie-plots to create a movie that shows how the walkers jump and how fast they converge during the mcmc. It starts creating plots from the very beginning of the run, so it includes the burn-in stage. Examples of the results, where I chose 10 plots:
https://www.atlas.aei.uni-hannover.de/~miriam.cabero/LSC/ringdown/single_mode/real_gw150914/movieplots/newplots_example/
An example of how a movie of this kind looks, for a run where we chose 180 plots, is:
https://www.atlas.aei.uni-hannover.de/~cdcapano/LSC/projects/pycbc_inference/ringdown/walker_movies/fixed_thinint1_180.mp4

### CODE REVIEW

**Comment by micamu** [comment]
@cdcapano I think I implemented all the things we had been talking about. Let me know if there are other things that should be added now.

**Comment by micamu** [comment]
Codacy has an issue understanding how numpy.mgrid works, nothing we can fix.
Besides that, and unless you have further comments, I am done with this PR

**Comment by cmbiwer** [comment]
What's the reason for renaming the existing ``pycbc_inference_plot_posterior`` to ``pycbc_inference_plot_corner``? At the very least you should update the workflow documentation if you rename that executable.

**Comment by micamu** [comment]
@cmbiwer I think @cdcapano wanted to make sure you agree with the name change before making any further changes

**Comment by cdcapano** [comment]
@cmbiwer We renamed plot_posterior to plot_corner because I couldn't think of another name for the new code than `plot_posterior`, since that's what it does. It is meant as a more versatile tool then plot corner, since it allows for both density and scatter plots to be made, and doesn't require the corner package. Are you ok with the renaming? If not, we can change it back. If so, could you point us to what documentation files need to change, so we can change them? Ultimately, I think you should have final say as to when this can be merged, since I'm not really an independent reviewer in this.

**Comment by cmbiwer** [comment]
I guess its fine to rename it.

I would just ask that you change in https://github.com/ligo-cbc/pycbc/blob/master/docs/workflow/pycbc_make_inference_workflow.rst the ``[inference_posterior]`` section to your preferred options for this executable. Since I see there's a lot of ``store_true`` options.

**Comment by micamu** [comment]
It just says 
```[inference_posterior]
; command line options use --help for more information```
What do we need to change?

**Comment by cdcapano** [comment]
@micamu You need to add the options that turn on the particular plots. The old plot posterior didn't require any options, while the new one requires that you specify what plots to create, otherwise it won't do anything. So add:
```
plot-density =
plot-contours =
plot-marginal =
```
to that file.

**Comment by micamu** [comment]
Done

**Comment by cdcapano** [comment]
@cmbiwer Are you happy to merge this? There are a couple of bugs in this patch that we've discovered since; I've put fixes for them into PR #1283. Once this is merged, I'll remove the hold on that one.

**Comment by cmbiwer** [comment]
Hey Collin, didn't realize you were waiting on me. Yeah I'm fine with it, looks like the docs have been updated.

**Pull request merged**
