### PR TITLE
Fix the end point for compression in compress bank

### PR DESCRIPTION
**Pull request by cdcapano**
Currently `pycbc_compress_bank` uses the `end_idx` attribute of `FrequencySeries` to figure out the last sample to use for the compression points. It turns out `end_idx` just returns the length of the `FrequencySeries`, not necessarily the last non-zero point. When decompressing, this causes the waveform to be interpolated beyond where it should normally be terminating, which may be causing templates to match noise better than what they would be when using the full waveform. This patch fixes this by using `numpy.nonzero` instead to find the last index to use for compression points.

Depends on #1491, so putting on hold for now.

### CODE REVIEW

**Comment by soumide1102** [comment]
@ahnitz Did you get a chance to look at this?

**Comment by ahnitz** [comment]
@soumide1102 The PR says it is on hold.

**Comment by soumide1102** [comment]
@ahnitz I think @cdcapano had put this one on hold because depended on #1491 . But that is merged now. So I this should be ready to be reviewed. After you review it, and if the changes look fine to you, I or you can merge it?

**Comment by soumide1102** [comment]
@ahnitz Thanks! I'll fix the merge conflicts in the branch and then merge it.

**Comment by soumide1102** [comment]
@ahnitz The landscape errors have been fixed in #1491 particularly in this commit https://github.com/ligo-cbc/pycbc/pull/1491/commits/7ae42a0b2b3cb4f03997c459623f616dbc084399 . So if I rebase this branch to master and fix the conflicts, those changes would get in.

**Comment by soumide1102** [comment]
@ahnitz I resolved the conflicts, and the landscape errors are gone now.

**Pull request merged**
