### PR TITLE
Coord

### PR DESCRIPTION
**Pull request by ahnitz**

### CODE REVIEW

**Comment by spxiwh** [comment]
This seems like the right solution. Feel free to push when ready, but this should be brought up at the relevant calls.

**Comment by spxiwh** [comment]
Alex, this has unfortunately broken the banksim code now. Reason being that now Fplus and Fcross are numpy.float64 and multiplying these by TimeSeries returns a numpy array and not a TimeSeries.

I have a local fix which is basically something like:

    return float(f_plus) * h_plus + float(f_cross) * h_cross

Is there maybe something better?

**Comment by ahnitz** [comment]
After thinking about it, I think this is fine. Either this, or change the
order of the multiply. Either would work. Please commit your patch when you
are happy that banksim works.

On Tue, Jan 19, 2016 at 6:08 PM, spxiwh <notifications@github.com> wrote:

> Alex, this has unfortunately broken the banksim code now. Reason being
> that now Fplus and Fcross are numpy.float64 and multiplying these by
> TimeSeries returns a numpy array and not a TimeSeries.
>
> I have a local fix which is basically something like:
>
> return float(f_plus) * h_plus + float(f_cross) * h_cross
>
> Is there maybe something better?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ligo-cbc/pycbc/pull/675#issuecomment-172920645>.
>



-- 
Dr. Alexander Nitz
Max Planck Institute for Gravitational Physics (Albert Einstein Institute)
Callinstrasse 38
D-30167 Hannover,  Germany
Tel: +49 511 762-17097

**Comment by spxiwh** [comment]
Alright, flipping the order seems to work too, so I'll try and run this overnight and then submit patch tomorrow.

**Pull request merged**
