### PR TITLE
Remove gatefiles.py and simplify supplied gating files

### PR DESCRIPTION
**Pull request by spxiwh**
We no longer need to treat gating files as special files, needing their own module. Therefore remove the ~200 lines of code and replace with the 2 lines of code that are now needed to do this. Gating files (if used again) should now be supplied like any other option in the [inspiral] (and similar) sections in the .ini file. All the pegasus-ification will be handled internally (this mirrors how PSD files are handled in the bank construction workflows).

Running test_workflow with this in place now.

### CODE REVIEW

**Comment by titodalcanton** [comment]
Hi Ian, great, let me know when your test is successful and I'll merge.

**Comment by spxiwh** [comment]
Test workflow completed successfully.

https://galahad.aei.mpg.de/~spxiwh/LVC/aLIGO/O1/analyses/workflow_testT8/

I'll try and poke landscape now to see if it will run.

**Comment by titodalcanton** [comment]
Hi Ian, it looks like your test workflow was to show that a regular (autogating) workflow didn't break, right? But then I'm a bit confused by the `[workflow-gating]` section in your config file... Is it just a leftover from pre-autogating era? Also, maybe we should try a workflow which does use a gating file?

**Comment by spxiwh** [comment]
Hi Tito, I just ran the test workflow following the instructions on the pycbc-config pages. That .ini file (and basically all the others as well) have a workflow-gating section, but no files, so the generator warns and then continues with no gating files. That probably should be removed ... maybe we should go through the config file for ER9 next week.

**Comment by spxiwh** [comment]
If you want me to run with gating files please point me to some files that are relevant for the times that the test workflow covers

```
start-time = 1128466607
end-time = 1128486607
```

**Comment by spxiwh** [comment]
Rebased because of conflicts

**Comment by titodalcanton** [comment]
Try using the following test gating files which just gate the loudest singles in each detector (and keep autogating enabled):

H1-GATING.txt
```
1128485864.565 0.25 0.25
```

L1-GATING.txt
```
1128485952.788 0.25 0.25
```

Then we can check that the loudest events disappear (or, if they are too long for the gates, that the gates show up in the corresponding spectrograms) and that the user-provided gates show up in the gates plot.

**Comment by spxiwh** [comment]
Seems reasonable, I'll run that now

**Comment by spxiwh** [comment]
Just noting while I'm setting this up: pycbc_single_template is currently *not* being sent autogating options. Is this correct?

**Comment by spxiwh** [comment]
Before starting this I verify that gating files have been identified correctly to pegasus for inspiral jobs:
```
--gating-file <file name="H1-GATING.txt"/> 
```
and calculate_psd jobs:
```
--gating-file <file name="L1-GATING.txt"/>
```

**Comment by titodalcanton** [comment]
In the O1 analysis, single_template jobs were told to autogate:
```
[inspiral&calculate_psd&single_template]
; automatic determination of where to gate
autogating-threshold = 100
autogating-cluster = 0.5
autogating-width = 0.25
autogating-taper = 0.25
autogating-pad = 16
```
Disabling it would probably lead to some confusion in the summary pages, I'd prefer to have it as we did in O1.

**Comment by spxiwh** [comment]
Run is now completed here:

https://galahad.aei.mpg.de/~spxiwh/LVC/aLIGO/O1/analyses/workflow_testT10

I've also added some documentation as requested by landscape (even though unrelated to this patch). From my side this is now ready to merge.

**Comment by titodalcanton** [comment]
Worked as expected, merging.

**Pull request merged**
