### PR TITLE
Add a notebook that demonstrates using pycbc_inspiral to find GW150914

### PR DESCRIPTION
**Pull request by duncan-brown**
This notebook demonstrates running ``pycbc_inspiral`` to find the H1 and L1 triggers corresponding to GW150914.

It also computes the best-fit waveform by amplitude, time, and phase-shifting the best fitting template in the bank. It subtracts this waveform from the input data, recomputes the matched filter, and computes the cross correlation between the residuals.

All of the code and data used in this notebook is available publicly from GitHub or LOSC.

### CODE REVIEW

**Comment by farr** [comment]
@duncan-brown I'm currently running the notebook (downloading data, etc), but I have a question about the phase shifting code:

```python
pycbc.fft.ifft(h1_bank[0]*np.exp(1j*phase_h1),h1_best_fit_waveform)
pycbc.fft.ifft(l1_bank[0]*np.exp(-1j*(phase_l1)),l1_best_fit_waveform)
```

Why the opposite signs in the two detectors?  Is this a PyCBC convention?  It looks like the phase is extracted in the same way from the complex SNR for both signals.

**Comment by farr** [comment]
@duncan-brown Also, it seems to fail with a weave error on my machine (I see that it successfully calls weave in other instances, but here it chokes on finding <error.h>):

```python
!rm -f H1-INSPIRAL_FULL_DATA_JOB0-1126257771-1837.hdf
h1_result = findchirp()
```

```
2017-08-07 12:33:49,865 Running with CPU support: 1 threads
2017-08-07 12:33:49,869 Reading Frames
2017-08-07 12:34:37,999 Highpass Filtering
2017-08-07 12:34:40,583 Converting to float32
2017-08-07 12:34:41,011 Gating glitches
2017-08-07 12:34:41,047 Resampling data
2017-08-07 12:34:45,892 attempting to aquire lock '/var/folders/k6/2zb5xhhn5l100sy98zmf83ym0000gp/T/502_python27_compiled/none/none/code_lockfile' for compiling code
2017-08-07 12:34:45,895 we have aquired the lock
2017-08-07 12:34:48,858 the lock has been released
2017-08-07 12:34:51,680 Highpass Filtering
2017-08-07 12:34:52,363 Remove Padding
2017-08-07 12:34:52,367 Making frequency-domain data segments
2017-08-07 12:34:53,412 Overwhitening frequency-domain data segments
2017-08-07 12:34:53,424 Read in template bank
2017-08-07 12:34:53,733 Full template bank size: 1
2017-08-07 12:34:53,742 0: generating SEOBNRv2 from 25.0 Hz
2017-08-07 12:34:54,735 attempting to aquire lock '/var/folders/k6/2zb5xhhn5l100sy98zmf83ym0000gp/T/502_python27_compiled/none/none/code_lockfile' for compiling code
2017-08-07 12:34:54,736 we have aquired the lock
2017-08-07 12:34:56,172 the lock has been released
2017-08-07 12:34:56,180 Filtering template 1/1 segment 1/1
2017-08-07 12:34:56,184 attempting to aquire lock '/var/folders/k6/2zb5xhhn5l100sy98zmf83ym0000gp/T/502_python27_compiled/none/none/code_lockfile' for compiling code
2017-08-07 12:34:56,185 we have aquired the lock
/var/folders/k6/2zb5xhhn5l100sy98zmf83ym0000gp/T/502_python27_compiled/none/none/sc_69aefe017927593ea71555386ce023aa0.cpp:683:10: fatal error: 'error.h' file not found
#include <error.h>
         ^
1 error generated.
---------------------------------------------------------------------------
CompileError                              Traceback (most recent call last)
<ipython-input-11-0c44c9768d16> in <module>()
      1 get_ipython().system(u'rm -f H1-INSPIRAL_FULL_DATA_JOB0-1126257771-1837.hdf')
----> 2 h1_result = findchirp()

<ipython-input-6-2811a7a56b94> in findchirp(subtract_waveform)
    363                                                              template.sigmasq(stilde.psd),
    364                                                              cluster_window,
--> 365                                                              epoch=stilde._epoch)
    366 
    367                 if not len(idx):

/Users/farr/anaconda3/envs/py2/lib/python2.7/site-packages/PyCBC-2d7f87-py2.7.egg/pycbc/filter/matchedfilter.pyc in full_matched_filter_and_cluster_symm(self, segnum, template_norm, window, epoch)
    258         """
    259         norm = (4.0 * self.delta_f) / sqrt(template_norm)
--> 260         self.correlators[segnum].correlate()
    261         self.ifft.execute()
    262         snrv, idx = self.threshold_and_clusterers[segnum].threshold_and_cluster(self.snr_threshold / norm, window)

/Users/farr/anaconda3/envs/py2/lib/python2.7/site-packages/PyCBC-2d7f87-py2.7.egg/pycbc/filter/matchedfilter_cpu.pyc in correlate(self)
    158                #extra_compile_args = ['-mno-avx -mno-sse2 -mno-sse3 -mno-ssse3 -mno-sse4 -mno-sse4.1 -mno-sse4.2 -mno-sse4a -O2 -w'] + omp_flags,
    159                #extra_compile_args = ['-msse3 -O3 -w'] + omp_flags,
--> 160                libraries = omp_libs, support_code = self.support, auto_downcast = 1)
    161 
    162 

/Users/farr/anaconda3/envs/py2/lib/python2.7/site-packages/weave-0.16.0-py2.7.egg/weave/inline_tools.pyc in inline(code, arg_names, local_dict, global_dict, force, compiler, verbose, support_code, headers, customize, type_converters, auto_downcast, newarr_converter, **kw)
    364                                     type_converters=type_converters,
    365                                     auto_downcast=auto_downcast,
--> 366                                     **kw)
    367 
    368             function_catalog.add_function(code,func,module_dir)

/Users/farr/anaconda3/envs/py2/lib/python2.7/site-packages/PyCBC-2d7f87-py2.7.egg/pycbc/weave.pyc in pycbc_compile_function(code, arg_names, local_dict, global_dict, module_dir, compiler, verbose, support_code, headers, customize, type_converters, auto_downcast, **kw)
     55                      support_code, headers, customize,
     56                      type_converters,
---> 57                      auto_downcast, **kw)
     58 
     59     fcntl.lockf(lockfile, fcntl.LOCK_UN)

/Users/farr/anaconda3/envs/py2/lib/python2.7/site-packages/weave-0.16.0-py2.7.egg/weave/inline_tools.pyc in compile_function(code, arg_names, local_dict, global_dict, module_dir, compiler, verbose, support_code, headers, customize, type_converters, auto_downcast, **kw)
    494     # setting.  All input keywords are passed through to distutils
    495     mod.compile(location=storage_dir,compiler=compiler,
--> 496                 verbose=verbose, **kw)
    497 
    498     # import the module and return the function.  Make sure

/Users/farr/anaconda3/envs/py2/lib/python2.7/site-packages/weave-0.16.0-py2.7.egg/weave/ext_tools.pyc in compile(self, location, compiler, verbose, **kw)
    371         success = build_tools.build_extension(file, temp_dir=temp,
    372                                               compiler_name=compiler,
--> 373                                               verbose=verbose, **kw)
    374         if not success:
    375             raise SystemError('Compilation failed')

/Users/farr/anaconda3/envs/py2/lib/python2.7/site-packages/weave-0.16.0-py2.7.egg/weave/build_tools.pyc in build_extension(module_path, compiler_name, build_dir, temp_dir, verbose, **kw)
    277         environ = copy.deepcopy(os.environ)
    278         try:
--> 279             setup(name=module_name, ext_modules=[ext],verbose=verb)
    280         finally:
    281             # restore state

/Users/farr/anaconda3/envs/py2/lib/python2.7/site-packages/numpy/distutils/core.pyc in setup(**attr)
    167     new_attr['distclass'] = NumpyDistribution
    168 
--> 169     return old_setup(**new_attr)
    170 
    171 def _check_append_library(libraries, item):

/Users/farr/anaconda3/envs/py2/lib/python2.7/distutils/core.pyc in setup(**attrs)
    164                 raise
    165             else:
--> 166                 raise SystemExit, "error: " + str(msg)
    167 
    168     return dist

CompileError: error: Command "g++ -fno-strict-aliasing -I/Users/farr/anaconda3/envs/py2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/farr/anaconda3/envs/py2/lib/python2.7/site-packages/weave-0.16.0-py2.7.egg/weave -I/Users/farr/anaconda3/envs/py2/lib/python2.7/site-packages/weave-0.16.0-py2.7.egg/weave/scxx -I/Users/farr/anaconda3/envs/py2/lib/python2.7/site-packages/numpy/core/include -I/Users/farr/anaconda3/envs/py2/include/python2.7 -c /var/folders/k6/2zb5xhhn5l100sy98zmf83ym0000gp/T/502_python27_compiled/none/none/sc_69aefe017927593ea71555386ce023aa0.cpp -o /var/folders/k6/2zb5xhhn5l100sy98zmf83ym0000gp/T/weave-farr-PUHiGH/python27_intermediate/compiler_e705fb80879d8974226aec45f0ffb3af/var/folders/k6/2zb5xhhn5l100sy98zmf83ym0000gp/T/502_python27_compiled/none/none/sc_69aefe017927593ea71555386ce023aa0.o -march=native -O3 -w " failed with exit status 1
```

Any thoughts?

**Comment by vivienr** [comment]
Hi,

I had a similar error at some point due to weave on OSX. Following https://stackoverflow.com/questions/10327939/error-no-such-instruction-while-assembling-project-on-mac-os-x

I added:

export WEAVE_FLAGS='-mno-avx'

to my set-up and was able to run things. Hope this helps...

**Comment by duncan-brown** [comment]
Note to self: the instructions for starting docker have a stray ``-v``. This should be removed.

**Comment by duncan-brown** [comment]
@farr what @vivienr said.

**Comment by farr** [comment]
@vivienr @duncan-brown Alas, that doesn't work for me.  My issue seems to be that the `error()` function is a `gcc` specific extension that doesn't seem to exist in either `gcc-6` or Apple's `clang`, and it is used outside the `#if _HAVE_AVX` and `#elif _HAVE_SSE3` blocks so just undefining those variables doesn't work.  The offending lines are all in `pycbc/filter/smid_correlate.py`, and for now I've just commented them out and replaced with `fprintf(stderr, ...)` and `return`.

**Comment by farr** [comment]
@vivienr @duncan-brown Whew.  There are a few places where `error()` is used, and it turns out to be easiest to just mock up the function that corresponds to the GCC library function.  The patch looks like

```patch
From 1ca1bdb5e38dcfa070577186fa1cabe034576f94 Mon Sep 17 00:00:00 2001
From: Will Meierjurgen Farr <wmfarr@gmail.com>
Date: Mon, 7 Aug 2017 16:18:39 +0100
Subject: [PATCH 33/33] Removed dependence on GCC  function for better
 standards compliance.

---
 pycbc/events/simd_threshold.py |  8 +++++++-
 pycbc/filter/simd_correlate.py | 12 +++++++++++-
 2 files changed, 18 insertions(+), 2 deletions(-)

diff --git a/pycbc/events/simd_threshold.py b/pycbc/events/simd_threshold.py
index 9d439b3..f478ff4 100644
--- a/pycbc/events/simd_threshold.py
+++ b/pycbc/events/simd_threshold.py
@@ -58,10 +58,16 @@ compartmentalize SIMD code from OpenMP code.
 
 tc_common_support = omp_support + pycbc.opt.simd_intel_intrin_support + """
 #include <stdint.h> // For uint32_t, int64_t
-#include <error.h>
 #include <complex> // Must use C++ header with weave
 #include <math.h> // For M_SQRT2
 
+/* Rough approx of GCC's error function. */
+void error(int status, int errnum, const char *format) {
+  fprintf(stderr, format);
+  if (status != 0) {
+    exit(status);
+  }
+}
 """
 
 # The following maximizes over an interval that can be no longer than
diff --git a/pycbc/filter/simd_correlate.py b/pycbc/filter/simd_correlate.py
index 002612a..b6f9b09 100644
--- a/pycbc/filter/simd_correlate.py
+++ b/pycbc/filter/simd_correlate.py
@@ -42,8 +42,18 @@ ccorrf_parallel: Runs multicore, but not explicitly vectorized.
 
 corr_common_support = omp_support + pycbc.opt.simd_intel_intrin_support + """
 #include <stdint.h> // For uint32_t, int64_t
-#include <error.h>
+#include <errno.h>
+#include <stdio.h>
+#include <stdlib.h>
 #include <complex> // Must use C++ header with weave
+
+/* Rough approx of GCC's error function. */
+void error(int status, int errnum, const char *format) {
+  fprintf(stderr, format);
+  if (status != 0) {
+    exit(status);
+  }
+}
 """
 
 corr_support = corr_common_support + """
-- 
2.10.2

```

I'll submit it to the main line of PyCBC directly.

After applying this patch, I can easily run the notebook, and (modulo the phase issue above), it looks good.  Duncan, if you can provide an explanation for the phases (I agree that they give a good subtraction, but *why*), I'll sign off on the review.

**Comment by duncan-brown** [comment]
@farr as @ahnitz noticed, I'd used ``np.arctan2()`` not ``np.angle()``. The latter fixes it.

**Comment by duncan-brown** [comment]
@farr @ahnitz this is ready for you to approve.

**Pull request merged**
