### PR TITLE
Statmap reorg

### PR DESCRIPTION
**Pull request by ahnitz**
Consolidate functionality that was duplicated in both pycbc_coinc_statmap and pycbc_coinc_statmap_inj into pycbc/events/coinc.py. This adds a generic dictionary array class as well that I've put into io/hdf.py. At some point when we have time, we might want to see if it makes sense to consolidate some of these classes, but at the moment, I can see reasons for each. Also, I added a speed up / minor memory reduction in the clustering algorithm.

### CODE REVIEW

**Comment by tdent** [comment]
Hi Alex - 
I assume the changes, in total, should not make any difference to the pipeline outputs.  I also assume you have checked that - if not, please do so. 
Some comments/suggestions on the code (which does not imply I've been able to look at all of it) follow. 

 - Cluster window doesn't have a default, but the code will fail without it.  I suggest to introduce a default (? whatever value has been most used .. somewhere from 1 to 10s I guess) & change help message to 'Length of time window in seconds to cluster coinc events, default X'
 - Same for veto window.  Suggest making help message more explicit, eg 'time to window out before and after each zerolag trigger for closed-box or `exclusive' results'
 - We may as well fix the algebraic form of the FAP now, it should be `fap = 1 - numpy.exp(- coinc_time / ifar)`.  Please make sure this change is in a commit of its own. 
 - In coinc.py, it looks a bit odd to be importing io and defining a class (StatmapData) inside a function (load_coincs).  Is there any reason not to define the class outside so that it could be accessed from elsewhere?  In fact, the use of functions and classes looks a bit bass-ackwards here.  I'd prefer to have the main code look like e.g. `d = StatmapData(args.coinc_files)` and then have `d.attrs`, `d.seg` and a `d.cluster()` method.  Then e.g. the cluster method would know to use the appropriate timeslide interval value from the file attrs, it would already be an attribute of the instance assigned by `__init__` and you wouldn't have separate variables 'attrs', 'seg' etc. floating around when they ought to be attached to a coinc data instance.  Classes are nice ways of handling data which comes attached to bits of metadata, proliferating variables are not.

**Comment by ahnitz** [comment]
Yes, I have checked that this change does not affect the results.

**Comment by ahnitz** [comment]
Ok, I believe I've addressed your points in the code. I'm doing a quick rerun of the post-processing to make sure I haven't changed results much.

**Comment by ahnitz** [comment]
Ok, this works for me now. Let me know if it ok to merge this.

**Comment by tdent** [comment]
Thanks Alex.  I'm afraid the i/o and data handling is still over complex, it's not clear why it needs to be that way.  
I don't see why we want to define the subclass StatmapData(..) inside a function which is just a thin wrapper.  If you want to ensure that the data object always has a specific set of groups, it would be simpler to omit 'groups' as a kwarg for StatmapData.__init__ and put the list of desired groups into the call to super(StatmapData, self).__init__() .  That means you can do away with the load_coincs function entirely and have one less level of complexity.  
Is the ```_return()``` method of StatmapData used?  If not, don't define it. 

Also, in general, I don't see what is gained by retrofitting the use of class instances to hold data so that methods return new instances (all the stuff with _return()) rather than modifying the existing object.  Particularly if they are called in a way that modifies the object anyway, ie ```d = d.cluster(args.cluster_window)```.  I think the Pythonic way of writing that would be ```d.cluster(args.cluster_window)```.  If there is some code standard or guidance saying why we shouldn't just be calling methods on data-holding objects, please point to it - otherwise keep things simple!

**Comment by ahnitz** [comment]
On Mon, Aug 10, 2015 at 2:53 PM, tdent <notifications@github.com> wrote:

> Thanks Alex. I'm afraid the i/o and data handling is still over complex,
> it's not clear why it needs to be that way.
>
> I don't see why we want to define the subclass StatmapData(..) inside a
> function which is just a thin wrapper. If you want to ensure that the data
> object always has a specific set of groups, it would be simpler to omit
> 'groups' as a kwarg for StatmapData.*init* and put the list of desired
> groups into the call to super(StatmapData, self).*init*() . That means
> you can do away with the load_coincs function entirely and have one less
> level of complexity.
>
> Ok, done. I'm rerunning the post-processing on a sample test. I'll post
back when and if it succeeds.

> Is the _return() method of StatmapData used? If not, don't define it.
>
Yes, it is. It has to be there to make sure that selecting or deleting on
it (from the parent class) returns the same class and not the parent.

> Also, in general, I don't see what is gained by retrofitting the use of
> class instances to hold data so that methods return new instances (all the
> stuff with _return()) rather than modifying the existing object.
> Particularly if they are called in a way that modifies the object anyway,
> ie d = d.cluster(args.cluster_window). I think the Pythonic way of
> writing that would be d.cluster(args.cluster_window). If there is some
> code standard or guidance saying why we shouldn't just be calling methods
> on data-holding objects, please point to it - otherwise keep things simple!
>
 I'm not sure there is a PEP standard, but it does follow the same
convention as most of numpy, etc, where all operations return new copies
and don't modify the original. The in-place operations are generally the
exception.  I do think it is clearer though at the top-level when methods
return new instances.

**Comment by ahnitz** [comment]
Ok, I've moved the class to pycbc/io/hdf.py and removed the load_coincs function. I've checked that a post-processing rerun gets the same results.

**Comment by tdent** [comment]
Hi Alex - as you surely know, ground level documentation for python classes has a method used to modify data stored in a class instance :
> d = Dog('Fido') 
> d.add_trick('roll over')

I don't think this is unclear or unusual Python code.  I thought this simplicity of syntax via object orientation [here's an object containing some data; it has a method that does something to it] was a reason for using python in the first place. 
As for numpy I can't tell why it's internally coded the way it is, but note that almost all of what it does is providing *functions* to the user: things which take in a bunch of objects and return other objects.  If it uses classes internally it has to erase almost all traces of that to appear like a suite of functions.  
I haven't seen anyone else deliberately negating the economy of class methods, I just think it will lead to more 'huh?' reactions.  You gave one reason it doesn't work as smoothly as regular class methods: 
> [the additional _return() definition] has to be there to make sure that selecting or deleting on it 
> (from the parent class) returns the same class and not the parent. 

.. one symptom of creating and having to check up on several different objects, one every time an operation is performed, rather than sticking with a single one.  It may or may not be clearer at top level but it seems more fragile.
Anyway this seems to have come as far as it can, I didn't intend to slow it up by forcing a rerun to check on every minor change, so if you don't want to reconsider the Nitz/numpy-internal-style classes then you should push, er, merge.

**Pull request merged**
