### PR TITLE
the future is now, remove stuff now supported in the version of numpy…

### PR DESCRIPTION
**Pull request by ahnitz**
Use numpy unique and in1d now that we require a modern numpy version anyway.

### CODE REVIEW

**Comment by titodalcanton** [comment]
I like less code! Did you test this? If not, I can rerun the postproc on a small IMBH workflow and check.

**Comment by ahnitz** [comment]
I haven't yet, so if you do, that would be great. Otherwise, I'll get to it tomorrow.

**Comment by titodalcanton** [comment]
Under test, stay tuned...
Before: https://www.atlas.aei.uni-hannover.de/~tito/LSC/o1/imbh/o1-imbh-chunk123-c02-phenomd-2/
After: https://www.atlas.aei.uni-hannover.de/~tito/LSC/o1/imbh/nitz-740-test/

**Comment by titodalcanton** [comment]
Result pages look identical, in particular the lists of found/missed injections. Merging.

**Pull request merged**
