### PR TITLE
Adds spin magnitude and angles Parameter classes

### PR DESCRIPTION
**Pull request by cmbiwer**
Adds ``Parameter`` classes for spin magnitude (``spin1a``) and spin angles (``spin1phi``,``spin1theta``) for both component spins. Doesn't add it for primary and secondary masses.

The PR includes them ``WaveformArray`` as well. It uses ``pycbc.coordinates``, which I broke up the Cartesian -> spherical calculations into smaller functions since it would've been overkill for ``WaveformArray``.

Need this PR though just so spin magnitude and angle shows up in the default plotting parameters list.

EDIT:
Example:
```
In [1]: from pycbc import coordinates
__init__: Setting weave cache to /local/cbiwer/5451_python27_compiled/36c77c/36c77c7a0a1f2b2d85b9e22d339418d817f0890a

In [2]: coordinates.cartesian_to_spherical(1,1,1)
Out[2]: (1.7320508075688772, 0.78539816339744828, 0.95531661812450919)

In [3]: from pycbc.io.record import WaveformArray
In [4]: warr = WaveformArray(3, names=["mass1", "mass2", "spin1x", "spin1y", "spin1z"])
In [5]: warr["spin1x"][0] = 1; warr["spin1y"][0] = 1; warr["spin1z"][0] = 1; warr["mass1"][0] = 1.4; warr["mass2"][0] = 1.4

In [6]: warr.spin1apycbc/io/record.py:1694: RuntimeWarning: invalid value encountered in divide
  return out / self.mass1**2
Out[6]: array([ 0.88369939,         nan,         nan])

In [7]: warr.spin1phi
pycbc/coordinates.py:59: RuntimeWarning: invalid value encountered in divide
  return numpy.arctan(y / x)
Out[7]: array([ 0.78539816,         nan,         nan])

In [8]: warr.spin1theta
pycbc/coordinates.py:79: RuntimeWarning: invalid value encountered in divide
  return numpy.arccos(z / spherical_rho(x, y, z))
Out[8]: array([ 0.95531662,         nan,         nan])
```

### CODE REVIEW

**Comment by ahnitz** [comment]
Hey Chris, any chance we could use azimuth and polar instead of theta / phi for the parameter names? There's always confusion with different coordinate conventions, and it would be nice to avoid that.

**Comment by cmbiwer** [comment]
Hey Alex, yeah sure I'll change it.

**Comment by cmbiwer** [comment]
Changed it to azmuthal and polar instead of phi and theta.

**Comment by ahnitz** [comment]
Any reason it is azmuthal instead of azimuthal?

**Comment by cmbiwer** [comment]
The reason? I'm illiterate. I'll fix it.

**Comment by cmbiwer** [comment]
Change it to azimuthal.

**Pull request merged**
