### PR TITLE
add option to ignore quiet or non-coincident injection

### PR DESCRIPTION
**Pull request by ahnitz**
I'm dusting off some old code I had tried a while back, but it still seems to work. This adds a executable that removes injections that are outside coincident time or are quiet in one detector. I've also added this to the workflow as an optional feature. The workflow still uses the full injection file for all purposes except filtering.

To enable only analyzing coincident injections.
[workflow-injections]
strip-injections=

I think this is a bit more experimental, but it seems to work for me, is the option to ignore injections that are further away than a fixed effective chirp distance. You can enable it my specifying it as an executable option for now.

[strip_injections]
max-effective-chirp-distance=110 ; A number I found was safe for s6 sensitivity (~SNR of 3.5)

I was able to get just over a 2x performance gain from this, using a very dense injection set (60s spacing).

### CODE REVIEW

**Comment by cdcapano** [comment]
Hi Alex,

For the bit about ignoring injections that are too far away: why draw them in the first place? Wouldn’t it be better to just make the distance bounds tighter?

Collin

On Aug 15, 2015, at 4:34 AM, Alex Nitz <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm dusting off some old code I had tried a while back, but it still seems to work. This adds a executable that removes injections that are outside coincident time or are quiet in one detector. I've also added this to the workflow as an optional feature. The workflow still uses the full injection file for all purposes except filtering.

To enable only analyzing coincident injections.
[workflow-injections]
strip-injections=

I think this is a bit more experimental, but it seems to work for me, is the option to ignore injections that are further away than a fixed effective chirp distance. You can enable it my specifying it as an executable option for now.

[strip_injections]
max-effective-chirp-distance=110 ; A number I found was safe for s6 sensitivity (~SNR of 3.5)

I was able to get just over a 2x performance gain from this, using a very dense injection set (60s spacing).

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/ligo-cbc/pycbc/pull/200

Commit Summary

  *   add script to remove non-coincident injections
  *   add function to apply strip vetoes to inj file
  *   call segment veto from pycbc hdf workflow
  *   make optional, update ini file

File Changes

  *   M bin/hdfcoinc/pycbc_make_hdf_coinc_workflow<https://github.com/ligo-cbc/pycbc/pull/200/files#diff-0> (207)
  *   A bin/hdfcoinc/pycbc_strip_injections<https://github.com/ligo-cbc/pycbc/pull/200/files#diff-1> (59)
  *   M pycbc/workflow/ini_files/example_hdf_bns.ini<https://github.com/ligo-cbc/pycbc/pull/200/files#diff-2> (5)
  *   M pycbc/workflow/injection.py<https://github.com/ligo-cbc/pycbc/pull/200/files#diff-3> (19)
  *   M setup.py<https://github.com/ligo-cbc/pycbc/pull/200/files#diff-4> (1)

Patch Links:

  *   https://github.com/ligo-cbc/pycbc/pull/200.patch
  *   https://github.com/ligo-cbc/pycbc/pull/200.diff

**Comment by ahnitz** [comment]
I agree with the not drawing them in the first place, but that requires all pipelines to understand the output, while this is general to any injection input. It's not quite the same as changing the distance bounds, though, as this primarily removes injections that are not optimally oriented in one detector or the other. (bad sky location, inclination, etc). A more sophisticated check would be to calculate the optimal SNRs at this point in the pipeline, but a check on the effective distance seems like an ok first order check.

**Comment by spxiwh** [comment]
Hi Alex,

Apologies for delay while on vacation. This branch now doesn't merge cleanly so this would need to be resolved.

This approach seems similar in principle to the one I proposed for NINJA, except here you just strip injections out of the configuration file, whereas in NINJA we took this into account at injection generation time to create a list of interesting injections to inject and a list of "missed" injections to ignore during the filtering, but to include in the post-processing .... To me that still seems the right approach, but I would have no objection to putting this into the code as an option if using pre-existing injection files or similar.

However, the issue with NINJA is also present here: The effective distance column is meaningless for precessing injections. There have been some discussions about getting the expected injection SNR into the injection file before analysis (and I know I promised to look into this, but haven't yet had the time). Has anybody thought about this in the meantime?

From a code perspective I find it a little confusing that the check on the strip-injections occurs within the veto_injections file. At a first glance at the top-level code I would assume that it *always* strips injections. Maybe put this check in the top-level code, or at least comment that the function may be a no-op depending on input options. Once that is resolved (and the patch updated with current master) I have no issues with pushing.

Cheers
Ian

**Comment by ahnitz** [comment]
> This approach seems similar in principle to the one I proposed for NINJA, except here you just strip injections out of the configuration file, whereas in NINJA we took this into account at injection generation time to create a list of interesting injections to inject and a list of "missed" injections to ignore during the filtering, but to include in the post-processing .... To me that still seems the right approach, but I would have no objection to putting this into the code as an option if using pre-existing injection files or similar.
> 
I agree that doing this in the injection code itself would be a better place in general as we can pack the injections in tighter to get a better sampling, however, exactly in the case of pre-generated files you can't do that. It should be straightforward now, with the new code structure, to allow another option in which you either provide the "missed" file separately or have the injection program handle it itself. 

> However, the issue with NINJA is also present here: The effective distance column is meaningless for precessing injections. There have been some discussions about getting the expected injection SNR into the injection file before analysis (and I know I promised to look into this, but haven't yet had the time). Has anybody thought about this in the meantime?
> 

I'm not sure they've done exactly that, but I think the suggestion has been floated to calculate the "optimial" SNR of an injection, which could be done correctly for precessing injections. I wouldn't suggest running this with cut in production mode anyway, at least for now, but it does seem to have good savings for even fairly conservative choices which might be ok more generally.

 In principle you have a similar problem when setting the distance limits correctly, and for a two-detector network at least, there are a quite a few injections where the effective distance goes way beyond this in at least one detector, so if you can set the limits, then I think you can conservatively set this parameter to the same. 

> From a code perspective I find it a little confusing that the check on the strip-injections occurs within the veto_injections file. At a first glance at the top-level code I would assume that it always strips injections. Maybe put this check in the top-level code, or at least comment that the function may be a no-op depending on input options. Once that is resolved (and the patch updated with current master) I have no issues with pushing.

Ok, I agree. It would make more sense to have that visible at the top level. I'll make a patch for that. Are you ok with the separation of the full data and the injection runs that is need to make this work? That I feel is the major change at the top level.

**Comment by spxiwh** [comment]
Okay, I'm happy for this to be merged if you are Alex. Thanks!

**Pull request merged**
