### PR TITLE
Add initial version of MCMC executable

### PR DESCRIPTION
**Pull request by cmbiwer**
This PR is not ready to merge.

Adds an executable to perform the MCMC.

### CODE REVIEW

**Comment by cdcapano** [comment]
I think the waveform parameters and prior stuff (lines 75-96) should be put into a configuration file. Then all of those options can just be condensed into a single argument. Otherwise, the arguments for this are going to get unwieldy as we add more priors.

**Comment by cmbiwer** [comment]
Well, I'd argue that there's already a lot of executables in pycbc that have unwieldy command lines but those long command lines make it easier to follow things up in the workflow. So there's some pros and cons to it. Anyways fair enough, lets use a configuration file.

If we have it read a configuration file, then perhaps something simple as:
```
[prior-mass1]
name = uniform
min = 0.0
max = 10.0
```

If we're going the route of a configuration file, I guess it makes senses to put all the waveform parameters in the file (static args and variable args). So maybe another section like:
```
[variable_args]
tc =
mass1 =

[static_args]
mass2 = 1.4
f_lower = 30.0
```

Other than this, the one other thing that needs to be done is have the executable use Collin's changes in #817 for the priors.

**Comment by duncan-brown** [comment]
I agree with @cmbiwer: we should pass arguments on the command line and not in configuration files where possible. This is important if we're going to scale out to OSG use.

**Comment by ahnitz** [comment]
@duncan-brown I agree with Collin on this. We will need to set ~100 options in the future that won't all have a uniform interface (different types of bounds, parameters, etc). While we can always override the configuration or do it entirely on the command line, in the same way we do for the workflow generator, it makes far more sense for this to be in a config file. Pegasus will have no problem handling this. Is there some other issue?

**Comment by cdcapano** [comment]
This won't be possible as we add more priors. Right now we just have uniform priors with bounds, but in the future some parameters may have priors that have no bounds, but have other parameters to set (e.g., one parameter might be a Gaussian, in which case you'll need to pass a width and a mean). Other parameters might be coupled to each other, requiring multi-dimensional priors which will have their own funky parameters. This will get to be a mess if you try to do it all on the command line. I don't know what OSG has to do with it; a config file is just an input text file like any other input file.

**Comment by cdcapano** [comment]
Hi Chris, yup, that's what I was thinking of. Can you code it up?

**Comment by cmbiwer** [comment]
Hey Collin, I'll add it.

**Comment by cmbiwer** [comment]
Hey Collin, I've made the changes. I'm running a test now, just to make sure nothing changed. So I guess if you got time take another look at the PR.

**Comment by cmbiwer** [comment]
So I compared this executable with the example I had before any of the pycbc PRs.

To compute 10000 samples, this executable is now about a factor 3 slower than the script I had before without the ```pycbc.inference``` module. I would have expected this executable would be slightly slower since I was only calculating SNR but I'd have hoped it wouldn't be that much slower.

Also when we switched from the command line to the configuration file, I changed how the initial conditions were done. Before I had the initial positions of the walkers drawn from around some point. Now its just taken from the prior, I think we want to have the option to set the initial positions around a point and let the walkers expand out and explore the space. But I don't think that needs to be in this PR, we already have a couple PRs that are piling up.

**Comment by cdcapano** [comment]
I was holding up because I wanted to suggest a different way to initialize the priors from the config file. Two things bother me: I don't like having the executable having to know about specifics about the priors (the special args bit), and it should allow for a single prior to have multiple parameters (which we'll need for coupled parameters). I have a suggestion for fixing that. However, it looks like you're addressing this in another pull request, so I'll merge this now and we'll address this over there.

That's bad to hear about the performance, but let's address optimization later.

**Comment by cmbiwer** [comment]
Thanks for taking a look Collin.

> I was holding up because I wanted to suggest a different way

Maybe I'm in the minority here but I really don't think we need to hold up because of design considerations like this, it just creates unnecessary deadtime. To me I'd rather get a working results page first, than think about how we want to read configurations for priors that require multiple arguments.

I think it should be good enough to create an issue for things that are self-contained in the MCMC code like that and we address them later separately.

**Pull request merged**
