### PR TITLE
add alternate filterbank class

### PR DESCRIPTION
**Pull request by ahnitz**
Add an alternate filterbank class that dynamically figures out the right filter length size for each template, assuming it has a length estimator.

### CODE REVIEW

**Comment by spxiwh** [comment]
Hey Alex,

This sounds good, but there's way too much duplicate code here between LiveFilterBank and FilterBank. Can this be reduced?

**Comment by ahnitz** [comment]
Ian, I've started a base class that encapsulates some of the common functionality. I don't think there is much more I can do. The obvious shared code at this point is where we set some extra data on the returned htilde, but I don't know how to really make this common in a sensible way.

**Comment by spxiwh** [comment]
I guess my concern here is *other* FilterBank classes that might want to use this functionality. It would seem now that we would have to define *two* CoherentFilterBank classes if we wanted to use both the old and the new functionality, same for PrecessingFilterBank. Maybe that's okay, maybe we just choose which FilterBank is most appropriate, I don't know. As an example, the SkyMaxFilterBank is here:

https://github.com/spxiwh/pycbc/blob/playing/pycbc/waveform/bank.py#L162

Anyway, I won't hold this up further.

You *are* changing functionality used in the primary analysis, so please do run the test workflow and post the result page. Once done I would be happy to merge this.

**Comment by ahnitz** [comment]
Ah, I see. I wasn't aware that is what you were thinking about. I should
clarify that the reason I made a second class instead of adding a different
generator of filters to the original one is that the basic input arguments
to the class would be different. I'll have to think about this a bit, but I
don't have time at the moment. In any case, I'll do the test workflow and
post the results.

On Wed, Mar 23, 2016 at 10:34 AM, spxiwh <notifications@github.com> wrote:

> I guess my concern here is *other* FilterBank classes that might want to
> use this functionality. It would seem now that we would have to define
> *two* CoherentFilterBank classes if we wanted to use both the old and the
> new functionality, same for PrecessingFilterBank. Maybe that's okay, maybe
> we just choose which FilterBank is most appropriate, I don't know. As an
> example, the SkyMaxFilterBank is here:
>
> https://github.com/spxiwh/pycbc/blob/playing/pycbc/waveform/bank.py#L162
>
> Anyway, I won't hold this up further.
>
> You *are* changing functionality used in the primary analysis, so please
> do run the test workflow and post the result page. Once done I would be
> happy to merge this.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ligo-cbc/pycbc/pull/730#issuecomment-200269052>
>



-- 
Dr. Alexander Nitz
Max Planck Institute for Gravitational Physics (Albert Einstein Institute)
Callinstrasse 38
D-30167 Hannover,  Germany
Tel: +49 511 762-17097

**Comment by ahnitz** [comment]
https://www.atlas.aei.uni-hannover.de/~ahnitz/LSC/ahnitz/projects/code_testing/q1/output3/local-site-scratch/html/

Took long enough, but I put through the test workflow with this change. I don't see any issues.

**Pull request merged**
