### PR TITLE
Issue 311. Resolve URLs to ini files, unify config file arguments.

### PR DESCRIPTION
**Pull request by lppekows**
This passes the ini files through resolve_url() to pull down any specified as http(s).  It also removes --installed-config-files and renames --local-config-files to --config-files.

### CODE REVIEW

**Comment by ahnitz** [comment]
Have you checked with Chris that he doesn't use the installed-config-file
option? I just want to make sure we don't take down the daily pages in the
process.

**Comment by lppekows** [comment]
Chris told me over mattermost that this won't be a problem for him.

**Comment by spxiwh** [comment]
Okay, approved to merge, but can you also grep for the config files command line argument in the documentation, fix anywhere it refers to the out-of-data CLIs, and merge that along with this? I don't need to approve the documentation fixes just include them here and merge.

**Comment by lppekows** [comment]
Good point!  I've updated the documentation and will merge.

**Pull request merged**
