### PR TITLE
MVSC feature construction code

### PR DESCRIPTION
**Pull request by shasvath**
MVSC code to construct features that will be used by SPR for trigger classification; this is a modified version of the mvsc_get_doubles_snglstage code on lalsuite.

### CODE REVIEW

**Comment by ahnitz** [comment]
Can you put it under bin/mvsc/.

Also, don't forget to add it to setup.py so it will be installed.

**Comment by ahnitz** [comment]
Tom,

I've assigned this to you to check over the technical detail of the script, which I don't think I can evaluate. However, the formatting and comments look good. If you are happy with it, please go ahead and merge it.

**Comment by tdent** [comment]
Shasvath, can you look at the setup.py file in the pycbc repository and see if you can add this code as an executable which will be installed.

**Comment by shasvath** [comment]
I've added a line in setup.py to include the MVSC code.

**Comment by tdent** [comment]
OK, good. 
But I just realized that the mvsc_queries needs to be present as well. 
However I think it would be fine to make this executable self-contained for the time being by including the mvsc_queries definitions in the executable as simple string assignments.  Probably a good place for this is directly after the comment 

'############## Strings for Sqlite Queries ###########################'

then you don't need to do 'import mvsc_queries' and you can remove a lot of instances of 'mvsc_queries.CandidateEventQuery' in building the sqlite strings.

**Comment by tdent** [comment]
OK.  Please remove lines that do nothing, eg 
'select_dimensions_detA = select_dimensions_detA'
 
Also I think it would be clearer to deal with the gps boundaries by calculating a list of lower bounds and a list of upper bounds (do we need +10 there though ?) and then iterating as  
for i, (gps_lower, gps_upper, ts_partition) in enumerate(zip(gps_lower_bounds, gps_upper_bounds, timeslides_partitions)):

**Comment by shasvath** [comment]
On Wed, May 27, 2015 at 6:37 PM, tdent <notifications@github.com> wrote:

> OK. Please remove lines that do nothing, eg
> 'select_dimensions_detA = select_dimensions_detA'
>
>    ---- Sorry I missed that.

> Also I think it would be clearer to deal with the gps boundaries by
> calculating a list of lower bounds and a list of upper bounds (do we need
> +10 there though ?) and then iterating as
>
   ---- gps_bounds is a list of tuples of (gps_lower, gps_upper). The very
last element has a +10 in it to make sure to include all      the remainig
injections in all_injections.


> for i, (gps_lower, gps_upper, ts_partition) in
> enumerate(zip(gps_lower_bounds, gps_upper_bounds, timeslides_partitions)):
>
 —
> Reply to this email directly or view it on GitHub
> <https://github.com/ligo-cbc/pycbc/pull/16#issuecomment-105987348>.
>



-- 
Shasvath J. Kapadia,
PhD Candidate,
Graduate Assistant,
Department of Physics,
University of Arkansas,
Fayetteville, AR-72701
USA

**Pull request merged**
