### PR TITLE
Chigram

### PR DESCRIPTION
**Pull request by ahnitz**
Add a plot of the chisq bin time series. Might be useful in some form for followup.

### CODE REVIEW

**Comment by duncan-brown** [comment]
This is very nice, but what exactly is plotted on the z-axis? (\rho/p - \rho_l)^2? Might also be nice to add a title with the actual value of the \chi^2 at t = 0.


> On Oct 26, 2015, at 10:34 AM, Alex Nitz <notifications@github.com> wrote:
> 
> Add a plot of the chisq bin time series. Might be useful in some form for followup.
> 
> Here is an example plot with a loud software injection in it.
> 
> 
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/ligo-cbc/pycbc/pull/526
> 
> Commit Summary
> 
> 	• add script to plot the chisq bin timeseries together
> 	• remove debugging line
> File Changes
> 
> 	• A bin/minifollowups/pycbc_plot_chigram (52)
> 	• M bin/pycbc_single_template (1)
> 	• M setup.py (1)
> Patch Links:
> 
> 	• https://github.com/ligo-cbc/pycbc/pull/526.patch
> 	• https://github.com/ligo-cbc/pycbc/pull/526.diff
> —
> Reply to this email directly or view it on GitHub.
> 

-- 

Duncan Brown                      http://www.gravity.phy.syr.edu/~duncan
Associate Professor of Physics         Room 263-1, Department of Physics
Director of the Graduate Program      Syracuse University, NY 13244, USA
Phone: 315 443 5993                                    Fax: 315 443 9103

**Comment by ahnitz** [comment]
Currently it is just the SNR time series for each bin plotted separately. I am not subtracting off the expectation.

**Comment by tdent** [comment]
Hi Alex, btw what's up with the y-axis, does it assign the same width to each bin?

**Comment by ahnitz** [comment]
Yeah, it is using the same width for each bin. I think that makes sense as
each bin contributes equally.

**Comment by spxiwh** [comment]
Thanks for doing this Alex. There are a few suggestions here, which mostly make sense to me. I think adding a colorbar title is necessary, but let me know once you've had a chance to read through these comments and address them.

**Comment by ahnitz** [comment]
Ok, some updates here.

Plots with the injection.

Showing the individual bins chisq contribution.
chisq_close
chisq

Showing the SNR of each bin. 
snr

**Comment by duncan-brown** [comment]
@spxiwh is this ok to merge? Looks very useful. @ahnitz can you check the color bar label on the second plot.

**Pull request merged**
