### PR TITLE
Move pycbc.inference.distributions module to its own subpackage

### PR DESCRIPTION
**Pull request by cmbiwer**
This PR moves ``pycbc.inference.distrbutions`` to ``pycbc.distributions``. This module was outgrown itself and is more general than just sampling. And puts ``pycbc.inference.boundaries`` inside ``pycbc.distributions``.

The dict that is used to map names to classes is inside ``__init__.py``.

The subpackage is organized as follows:
  * ``bounded.py`` contains ``BoundedDist``
  * ``uniform.py`` contains ``Uniform``
  * ``uniform_angle.py`` contains all the uniform angle distributions except for ``UniformSky``
  * ``uniform_sky.py`` contains ``UniformSky``
  * ``from_file.py`` contains ``FromFile``
  * ``power_law.py`` contains ``UniformRadius``

Updates examples and docs to point to new subpackage as well. Example of updated docs here: https://sugwg-jobs.phy.syr.edu/~cbiwer/docs/distributions.html

### CODE REVIEW

**Comment by cmbiwer** [comment]
I don't think the quantified code is  complaints are much. Its complaining about wildcard imports. I think its convenient to have these so you can still do ``distributions.Uniform`` instead of ``distributions.uniform.Uniform`` more quickly. And the ``classmethod`` complaint should be ignored, these are the ``NotImplementedError`` versions of these functions.

**Comment by cmbiwer** [comment]
Just realized I need to update unit test for conversions as well.

**Comment by cmbiwer** [comment]
Alright, I moved the ``SinAngle`` and ``CosAngle`` to ``angular.py``. This makes some weird imports between ``angular.py`` and ``uniform_angle.py`` for ``UniformSolidAngle``; so I moved ``UniformSolidAngle`` to ``sky_position.py``.

The Codacy messages are the same ones I commented on above.

**Comment by cdcapano** [comment]
How about putting `UniformAngle` and `UniformSolidAngle` into `angular.py`? See [my pull request](https://github.com/cmbiwer/pycbc/pull/5) on to this branch.

**Comment by cmbiwer** [comment]
I've merged your PR on my branch. Let me know if there is anything else.

**Comment by cdcapano** [comment]
@cmbiwer I spoke too soon. I just realized codacy is complaining about `Error` being undefined in `angular.py`. That may have been my fault, sorry. Could you add `from ConfigParser import Error` to that file before merging?

**Comment by cdcapano** [comment]
@cmbiwer Nevermind, realized I could do it myself through the web interface.

**Pull request merged**
