### PR TITLE
pycbc_mvsc_get features with more weight options

### PR DESCRIPTION
**Pull request by shasvath**
Included min_weights and distance_power options for signal weighting

### CODE REVIEW

**Comment by tdent** [comment]
Hi Alex, Shasvath : I see a message here 'We can’t automatically merge this pull request. Use the command line to resolve conflicts before continuing.'  I tried the steps given below that, i.e. 

Step 1: From your project repository, check out a new branch and test the changes.

git checkout -b shasvath-master master
git pull https://github.com/shasvath/pycbc.git master

Step 2: Merge the changes and update on GitHub.

git checkout master
git merge --no-ff shasvath-master
git push origin master

... but that didn't seem to make any difference at all.  (And why should it, since my origin/master isn't involved in the merge?)  Alex, should Shasvath try something like 

git fetch upstream
git rebase upstream/master

?

**Comment by tdent** [comment]
Shasvath, one further comment on the code: in the reweighting function, where you have a choice between methods via using multiple 'if' statements, it would be clearer to use 'if / elif / ..' where 'elif' is used for all choices after the first one, i.e.
 
    if weighting_method == "physical_distance":
    (...)
    elif weighting_method == "chirp_distance":

    if self.d_distr == "uniform":
    (...)
    elif self.d_distr == "log10":
    (...)

This makes it clear that these choices are mutually exclusive such only one of the statements should be executed.

**Comment by ahnitz** [comment]
Tom, 

Shasvath should do the following.

```
git checkout FEATURE_BRANCH
git fetch upstream
git rebase upstream/master
#There will be merge conflicts that need to be manually fixed, in some cases it may be trivial
git push origin FEATURE_BRANCH -f
# The changes will now be reflected in the pull request
```

If you have fixed branch yourself, you can do a pull request against Shasvath's branch also.

**Comment by tdent** [comment]
Looks OK, thanks.  I think it was just a case of some of the commits already being present on ligo-cbc:master.

**Comment by tdent** [comment]
Actually this doesn't seem to have worked correctly as the files on ligo-cbc/master have not changed (nothing in pycbc/bin/mvsc apparently changed for ~4 weeks).  The changes are, though, visible at https://github.com/ligo-cbc/pycbc/tree/a9644bf1df330948489b17ce667e78ae3cfe063e/bin/mvsc - but I don't know what this actually shows us.

**Pull request merged**
