### PR TITLE
raise error if timeslide interval is smaller than time_window 

### PR DESCRIPTION
**Pull request by ahnitz**

### CODE REVIEW

**Comment by titodalcanton** [comment]
Alex, I also suggest removing the (now invalid) `default=0` from timeslide_interval, and making the arg required.

**Comment by ahnitz** [comment]
Makes sense. I need to make one other change anyway, as you do need a way still to *not* do timeslides (only zerolag).

**Comment by duncan-brown** [comment]
@ahnitz bumping to next release so you can make @titodalcanton's change.

**Comment by ahnitz** [comment]
Tito I've rebased and updated the patch. I cannot make the argument required as we need to allow one to *not* do timeslides.

**Comment by ahnitz** [comment]
I've hand checked that this produces and error when using .01 for example, and no error otherwise.

**Comment by titodalcanton** [comment]
Alex, in the help for `--timeslide-interval` could you mention that no timeslides are done if the option is omitted, and remove the unnecessary `default=None`?

**Comment by ahnitz** [comment]
Ok, done.

**Pull request merged**
