### PR TITLE
Allow pycbc_submit_dax to use more than a single cache file

### PR DESCRIPTION
**Pull request by stevereyes01**
Add the feature to put multiple cache and map files together into one cache file without user input.

Fails if one of the cache files is malformed or does not exist (Tested and this seems to fail when you give it a cache file that isn't in the form of `file:///` or `file:///foo.map` doesn't exist or `https://foo.cache` doesn't exist.

Current test workflow in progress. Do not merge yet. I noticed that this version of pycbc_submit_dax output a syntax error when generating:

`Querying Pegasus database for job..Error: near "wf_uuid": syntax error`

However, the workflow does not seem to have failed, nor does pegasus-dashboard signal that anything is wrong. The workflow is currently ~1/5 of the way complete.

### CODE REVIEW

**Comment by stevereyes01** [comment]
Error message from submitting pycbc_submit_dax:

```
(pycbc-dev) steven.reyes@sugar-dev3:Aug26CacheTest$ ./submit.sh 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
182   182    0   182    0     0   1551      0 --:--:-- --:--:-- --:--:--  7000
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9200    0  9200    0     0  82190      0 --:--:-- --:--:-- --:--:--  390k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
101  1728  101  1728    0     0  14.3M      0 --:--:-- --:--:-- --:--:--     0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  883k  100  883k    0     0  1140M      0 --:--:-- --:--:-- --:--:--  846M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4000  100  4000    0     0  32.6M      0 --:--:-- --:--:-- --:--:--     0
Enter your LIGO.ORG username in (e.g. albert.einstein): steven.reyes
Your identity: steven.reyes@LIGO.ORG
Enter pass phrase for this identity:
Creating proxy .................................... Done
Your proxy is valid until: Aug 29 18:06:21 2016 GMT
/home/steven.reyes/pycbc-dev/lib/python2.6/site-packages/numpy/lib/utils.py:99: DeprecationWarning: `scipy.weave` is deprecated, use `weave` instead!
  warnings.warn(depdoc, DeprecationWarning)
__init__: Setting weave cache to /usr1/steven.reyes/43611_python26_compiled/f9e767/f9e7671a2fe7cc3b3686f7f4ac611193a95bcb78
Generating concrete workflow
2016.08.26 14:06:23.887 EDT: [WARNING]  unknown profile condor.accounting_group,  using anyway 
2016.08.26 14:06:23.891 EDT: [WARNING]  profile condor.accounting_group_user is empty, Removing! 
2016.08.26 14:06:24.279 EDT: [WARNING]  unknown profile condor.accounting_group,  using anyway 
2016.08.26 14:06:24.279 EDT: [WARNING]  unknown profile condor.accounting_group,  using anyway 
Rank  ( rank => 1 priority => 400 expr => file:///cvmfs/.*)
Rank  ( rank => 2 priority => 300 expr => file://.*)
Rank  ( rank => 3 priority => 200 expr => root://.*)
Rank  ( rank => 4 priority => 100 expr => gridftp://.*)
Rank  ( rank => 5 priority => 0 expr => .*)
2016.08.26 14:06:24.352 EDT: [WARNING]  unknown profile condor.accounting_group,  using anyway 
2016.08.26 14:06:24.356 EDT: [WARNING]  unknown profile condor.accounting_group,  using anyway 
2016.08.26 14:06:24.361 EDT: [WARNING]  unknown profile condor.accounting_group,  using anyway 
2016.08.26 14:06:25.396 EDT:    
2016.08.26 14:06:25.401 EDT:   ----------------------------------------------------------------------- 
2016.08.26 14:06:25.406 EDT:   File for submitting this DAG to Condor           : TestWorkflow2-0.dag.condor.sub 
2016.08.26 14:06:25.412 EDT:   Log of DAGMan debugging messages                 : TestWorkflow2-0.dag.dagman.out 
2016.08.26 14:06:25.417 EDT:   Log of Condor library output                     : TestWorkflow2-0.dag.lib.out 
2016.08.26 14:06:25.422 EDT:   Log of Condor library error messages             : TestWorkflow2-0.dag.lib.err 
2016.08.26 14:06:25.427 EDT:   Log of the life of condor_dagman itself          : TestWorkflow2-0.dag.dagman.log 
2016.08.26 14:06:25.432 EDT:    
2016.08.26 14:06:25.448 EDT:   ----------------------------------------------------------------------- 
2016.08.26 14:06:25.960 EDT:   Your database is compatible with Pegasus version: 4.6.1 
2016.08.26 14:06:26.027 EDT:   Submitting to condor TestWorkflow2-0.dag.condor.sub 
2016.08.26 14:06:26.143 EDT:   Submitting job(s). 
2016.08.26 14:06:26.148 EDT:   1 job(s) submitted to cluster 33215129. 
2016.08.26 14:06:26.153 EDT:    
2016.08.26 14:06:26.158 EDT:   Your workflow has been started and is running in the base directory: 
2016.08.26 14:06:26.164 EDT:    
2016.08.26 14:06:26.169 EDT:     /usr1/steven.reyes/pycbc-tmp.ILWtUaZm3e/work 
2016.08.26 14:06:26.174 EDT:    
2016.08.26 14:06:26.179 EDT:   *** To monitor the workflow you can run *** 
2016.08.26 14:06:26.184 EDT:    
2016.08.26 14:06:26.189 EDT:     pegasus-status -l /usr1/steven.reyes/pycbc-tmp.ILWtUaZm3e/work 
2016.08.26 14:06:26.195 EDT:    
2016.08.26 14:06:26.200 EDT:   *** To remove your workflow run *** 
2016.08.26 14:06:26.205 EDT:    
2016.08.26 14:06:26.210 EDT:     pegasus-remove /usr1/steven.reyes/pycbc-tmp.ILWtUaZm3e/work 
2016.08.26 14:06:26.215 EDT:    
2016.08.26 14:06:26.613 EDT:   Time taken to execute is 2.662 seconds 

Querying Pegasus database for job..Error: near "wf_uuid": syntax error

(pycbc-dev) steven.reyes@sugar-dev3:Aug26CacheTest$ condor_dag_status
User          Workflow         Sites      Done  Queued  Failed  Total  Path
steven.reyes  TestWorkflow2-0  local      2     1       0       5      /usr1/steven.reyes/pycbc-tmp.ILWtUaZm3e/work
steven.reyes  TestWorkflow2-0  undefined  42    5       0       569    /usr1/steven.reyes/pycbc-tmp.ILWtUaZm3e/work/./main_ID0000001
```

**Comment by duncan-brown** [comment]
I think we need the following changes around to make the database querying more robust:
```
WORKFLOW_ID_STRING=""
WORKFLOW_DB_CMD="sqlite3 -csv ${HOME}/.pegasus/workflow.db \"select submit_hostname,wf_id,wf_uuid from master_workflow where submit_dir = '${SUBMIT_DIR}/work';\""
DB_TRY=0
/bin/echo "Querying Pegasus database for job:"
# querying the database sometimes fails, so allow retries
set +e
until [ $DB_TRY -ge 10 ]
do 
  /bin/echo -n "Querying..."
  WORKFLOW_ID_STRING=`eval $WORKFLOW_DB_CMD`
  if [ $? -eq 0 ] && [ ! -z $WORKFLOW_ID_STRING ] ; then
    /bin/echo "Done."
    break
  else
    /bin/echo "Query failed: ${WORKFLOW_DB_CMD}"
    /bin/echo "Sleeping for ${DB_TRY} seconds and retrying..."
  fi
  sleep $DB_TRY
  DB_TRY=$(( $DB_TRY + 1 ))
done
set -e
```

**Comment by stevereyes01** [comment]
Please hold while I check to see if this works first!

**Comment by stevereyes01** [comment]
New test results with the 2nd commit:

```
Querying Pegasus database for job:Querying...Query failed: sqlite3 -csv /home/steven.reyes/.pegasus/workflow.db "select submit_hostname,wf_id,wf_uuid from master_workflow where submit_dir = '/usr1/steven.reyes/pycbc-tmp.YTj6kUZAZp/work';"
Sleeping for 0 seconds and retrying...
Querying...Query failed: sqlite3 -csv /home/steven.reyes/.pegasus/workflow.db "select submit_hostname,wf_id,wf_uuid from master_workflow where submit_dir = '/usr1/steven.reyes/pycbc-tmp.YTj6kUZAZp/work';"
Sleeping for 1 seconds and retrying...
Querying...Done.
Workflow submission completed successfully.

The Pegasus dashboard URL for this workflow is:
  https://sugar-dev3.phy.syr.edu/pegasus/u/steven.reyes/r/213/w?wf_uuid=15339a80-aa8e-42c0-be9f-a959783e14a6

Note that it make take a while for the dashboard entry to appear while the workflow
is parsed by the dashboard. The delay can be on the order of one hour for very large
workflows.
```

Looks like it worked. You can now merge this pull request as soon as the workflow completes. (It's currently in mini followups, should complete soon).

**Comment by spxiwh** [comment]
Please see discussion in PyCBC chat about this. It seems that this patch has broken the ability to use cache files:
```
[spxiwh@vulcan2 03:38 PM outputT14]$ pycbc_submit_dax --cache-file input.map --accounting-group ligo.dev.o1.cbc.nsbh.pycbcoffline --dax test-workflow.dax --local-dir /local/spxiwh/ --enable-shared-filesystem --no-create-proxy               
curl: (6) Couldn't resolve host 'input.map'
```
Reverting this so that @stevereyes01 can look into this and then unrevert.

**Comment by stevereyes01** [comment]
@spxiwh Yes, as seen in the chat, you'll need to use `file:///PATH_TO_MAP`.

I'm not convinced that this is the actual bug that you're falling on to though.

**Pull request merged**
