### PR TITLE
Generate XML PSDs

### PR DESCRIPTION
**Pull request by titodalcanton**
Add ability to save average PSDs in GSTLAL XML format, and include that in the PSD estimation workflow.

### CODE REVIEW

**Comment by spxiwh** [comment]
Hi Tito,

I'm happy with the changes, so merge when ready. Although the sanity checks have failed.

**Comment by titodalcanton** [comment]
Network issue, restarted... I also want to test it myself, I'll merge when done.

**Comment by titodalcanton** [comment]
Needs https://github.com/ligo-cbc/pycbc/pull/321.

**Comment by titodalcanton** [comment]
I tested this and it works, it can be merged.

**Pull request merged**
