### PR TITLE
Execute now fix

### PR DESCRIPTION
**Pull request by ahnitz**
This removes the verbatim_executable option and just decides for you if the executable will need to be transferred.

### CODE REVIEW

**Comment by ahnitz** [comment]
Larne, I only tested on a quick example that pulled lalapps_inspinj from the software repo.

**Comment by lppekows** [comment]
Hi Alex,

thanks for cleaning this up.  I tried a complete workflow which failed getting segments trying to execute the remote ligolw_segment_query_dqsegdb.  Looks like  https://github.com/ahnitz/pycbc/blob/execute_now_fix/pycbc/workflow/segment.py#L426 bypasses execute_node.

**Comment by ahnitz** [comment]
I see, hmm. This begs the question of whether "make_external_call" should
retrieve the executable as on master, which I'm not sure of, or if reslove
url should be added here.

**Comment by lppekows** [comment]
My vote would be adding it to make_external_call, which avoids having to add a check to everything that needs to be run at workflow generation (which is how I missed lalapps_inspinj).  What's the downside of doing it there?

**Comment by ahnitz** [comment]
Larne, 

I've updated this to include a call to resolve url before the make external call. I don't think the resolve belongs within that function as it really should be something that one could execute on the command line. 

I've also updated resolve url to act as a NOOP if the input is already a valid file path to something. This means that people will again be able to use full paths in configuration files for test runs.

**Comment by lppekows** [comment]
Hi Alex,

I just tested this and it failed because the downloaded ligolw_segment_query_dqsegdb wasn't executable.  I think you need to add this line back:

```
os.chmod(resolvedExe, stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR)
```

**Comment by ahnitz** [comment]
Larne, ok it should now be setting the CHMOD.

**Comment by lppekows** [comment]
Hi Alex,

I think there's a missing import

```
  File "/home/lppekows/pycbc-dev/lib/python2.6/site-packages/PyCBC-12208d-py2.6.egg/pycbc/workflow/segment.py", line 420, in get_science_segments
    permissions=stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR)),
NameError: global name 'stat' is not defined
```

**Comment by ahnitz** [comment]
You are right, should be updated now.

**Comment by lppekows** [comment]
Hm, misplaced close parenthesis?

```
  File "/home/lppekows/pycbc-dev/lib/python2.6/site-packages/PyCBC-7fef63-py2.6.egg/pycbc/workflow/segment.py", line 420, in get_science_segments
    permissions=stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR)),
TypeError: get() got an unexpected keyword argument 'permissions'
```

**Comment by ahnitz** [comment]
Ok, let me run a small test.

**Comment by lppekows** [comment]
I've got a test set up in /home/lppekows/projects/cbc/pycbc_release_tests/tmp if you want to use it.   run.sh is the top-level script.

**Comment by ahnitz** [comment]
I'll try this, thanks!

**Comment by ahnitz** [comment]
Ok, sorry for all the iteration here. It should now work, execpt for the
fact that your ini file doesn't have the gating exe, but I think the work
is done before that.

**Comment by lppekows** [comment]
Hi Alex,

yeah, all the relevant work seems to be done by then.  I'm happy to merge as soon as travis completes.

**Pull request merged**
