### PR TITLE
Revert "Cpuopt"

### PR DESCRIPTION
**Pull request by ahnitz**
Reverts ligo-cbc/pycbc#166

I've noticed some strange results, and I'm generating this as a convenience to check if the issues were introduced here.

### CODE REVIEW

**Comment by ahnitz** [comment]
Josh, Larne, 

I've reran one of my runs for my thesis using master and there are a number of missed injections that seems to be caused by this pull request. 

Here is a run made from vanilla master.
https://sugar-jobs.phy.syr.edu/~ahnitz/projects/coinc/t6/gw/html/
/home/ahnitz/projects/coinc/t6/gw

Here is the run after reverting pull request #166 
https://sugar-jobs.phy.syr.edu/~ahnitz/projects/coinc/t7/gw/html/
/home/ahnitz/projects/coinc/t7/gw

**Comment by josh-willis** [comment]
Hi Alex,

I am on vacation and will not be able to look at this at all until next week (at the earliest, August 10th).

It would help in the meantime if you can give something more specific than pointers to run result pages; for instance, what are some specific (loud) missed injections, and what template found them in the reverted run.  Clustering has changed to be more aggressive, so marginal injections near loud noise may well be missed; I assume you don't mean that?

Thanks

Josh 


On Aug 2, 2015, at 10:12 AM, Alex Nitz wrote:

> Josh, Larne,
> 
> I've reran one of my runs for my thesis using master and there are a number of missed injections that seems to be caused by this pull request.
> 
> Here is a run made from vanilla master.
> https://sugar-jobs.phy.syr.edu/~ahnitz/projects/coinc/t6/gw/html/
> /home/ahnitz/projects/coinc/t6/gw
> 
> Here is the run after reverting pull request #166 
> https://sugar-jobs.phy.syr.edu/~ahnitz/projects/coinc/t7/gw/html/
> /home/ahnitz/projects/coinc/t7/gw
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--
Josh Willis

Associate Professor 				Email:	josh.willis@acu.edu
of Engineering & Physics		

Abilene Christian University		Phone:	(325) 674-2527
Box 27963                                		Fax:		(325) 674-2146
Abilene, TX 79699-7963			Dept:	(325) 674-2165

Foster Science Building Room 317

**Comment by josh-willis** [comment]
I should add that I've done the usual thing of opening corresponding plots from the two runs in adjacent tabs and toggling, to visually detect differences.  I can't find any, in any of the plots in the "Summary" sections of either "Injections" or "Sensitivity".  Since I assume you know injections were missed by knowing which injection set and which  table to look at, please point us toward those.

Thanks,

Josh


On Aug 2, 2015, at 12:20 PM, Josh Willis wrote:

> Hi Alex,
> 
> I am on vacation and will not be able to look at this at all until next week (at the earliest, August 10th).
> 
> It would help in the meantime if you can give something more specific than pointers to run result pages; for instance, what are some specific (loud) missed injections, and what template found them in the reverted run.  Clustering has changed to be more aggressive, so marginal injections near loud noise may well be missed; I assume you don't mean that?
> 
> Thanks
> 
> Josh 
> 
> 
> On Aug 2, 2015, at 10:12 AM, Alex Nitz wrote:
> 
>> Josh, Larne,
>> 
>> I've reran one of my runs for my thesis using master and there are a number of missed injections that seems to be caused by this pull request.
>> 
>> Here is a run made from vanilla master.
>> https://sugar-jobs.phy.syr.edu/~ahnitz/projects/coinc/t6/gw/html/
>> /home/ahnitz/projects/coinc/t6/gw
>> 
>> Here is the run after reverting pull request #166 
>> https://sugar-jobs.phy.syr.edu/~ahnitz/projects/coinc/t7/gw/html/
>> /home/ahnitz/projects/coinc/t7/gw
>> 
>> —
>> Reply to this email directly or view it on GitHub.
>> 
> 
> --
> Josh Willis
> 
> Associate Professor 				Email:	josh.willis@acu.edu
> of Engineering & Physics		
> 
> Abilene Christian University		Phone:	(325) 674-2527
> Box 27963                                		Fax:		(325) 674-2146
> Abilene, TX 79699-7963			Dept:	(325) 674-2165
> 
> Foster Science Building Room 317
> 
> 
> 

--
Josh Willis

Associate Professor 				Email:	josh.willis@acu.edu
of Engineering & Physics		

Abilene Christian University		Phone:	(325) 674-2527
Box 27963                                		Fax:		(325) 674-2146
Abilene, TX 79699-7963			Dept:	(325) 674-2165

Foster Science Building Room 317

**Comment by ahnitz** [comment]
Sorry Josh, 

That would be because I linked to the wrong places. I've corrected the links in the original posts. This is the key comparison I think though.

(master)
https://sugar-jobs.phy.syr.edu/~ahnitz/projects/coinc/t7/gw/html/H1L1-PLOT_FOUNDMISSED_SUMMARY_ALLINJ-962582415-604800.png

(master - #166)
https://sugar-jobs.phy.syr.edu/~ahnitz/projects/coinc/t8/gw/html/H1L1-PLOT_FOUNDMISSED_SUMMARY_ALLINJ-962582415-604800.png

**Comment by ahnitz** [comment]
Here is a more specific example. 
(master)
https://sugar-jobs.phy.syr.edu/~ahnitz/projects/coinc/t7/gw/html/5._injections/5.3_BNSINJ/H1L1-PLOT_FOUNDMISSED_CHIRPDISTMCHIRP_STATIC_GRAD_BNSINJ-962582415-604800.png

(master - #168)
https://sugar-jobs.phy.syr.edu/~ahnitz/projects/coinc/t8/gw/html/5._injections/5.3_BNSINJ/H1L1-PLOT_FOUNDMISSED_CHIRPDISTMCHIRP_STATIC_GRAD_BNSINJ-962582415-604800.png

If you want a specific trigger, take note of the closest loud injection that appears to have a very poor far (deep) red. 

You can find it in the loudest found table 5.3, B3. If you sort by distance in ascending order, it is the 8th from the top (on both pages, thankfully). 

This is what I see at the moment. 
INJ TIME: 962921232.69
NEWSNR: 160 -> 6
TIME DIFF: 7.32 -> .49

**Comment by lppekows** [comment]
The reruns for the review are almost done and I'm close to being able to recreate the plots from P1500086, I'd like to at least look at those before reverting.  I don't think that will happen before tomorrow though.

**Pull request merged**
