### PR TITLE
Include a set of basic parameters when reading InferenceFile

### PR DESCRIPTION
**Pull request by cmbiwer**
PR #1567 does not solve sampling in spherical coordinates and would require a duplication of all the functions in ``conversions.py``. Also PR #1567 makes these very long command lines. This PR makes ``results_from_cli`` include a set of basic parameters (``mass1``, ``mass2``, ``spin1x``, ``spin1y``, ``spin1z``, ``spin2x``, ``spin2y``, and ``spin2z``). Then you have full access to doing all the conversions.

So even if you sampled in say ``mchirp`` and ``q``, all you need to specify on the command line is ``--parameters mass1 mass2`` and it will plot those parameters.

These classes could probably be used to replace those same types of functions in ``pycbc.waveform.generators``.

Requires #1590.

### CODE REVIEW

**Comment by cmbiwer** [comment]
Should include ``redshift`` in this as well so people don't have to type ``redshift(distance)``.

**Comment by cmbiwer** [comment]
Added examples to the docstring.

Now much simpler to plot ``mass1``, ``mass2`` if not sampled in it and likewise with spherical spin coordinates and ``redshift``, eg.:
```
pycbc_inference_plot_posterior --input-file test.hdf --output-file ~/public_html/tmp/tmp_posterior.png --iteration 19999 --plot-marginal --plot-density --parameters mchirp q "mass1/(1+redshift):\$m_{1}^\mathrm{src}\$" "mass2/(1+redshift):\$m_{2}^\mathrm{src}\$" chi_eff m_p redshift distance
```

**Comment by cmbiwer** [comment]
Soumi has requested some features to this PR which I will add.

**Comment by cmbiwer** [comment]
@soumide1102 Can you see if this works for all the cases you were trying?

I did a short test on sugwg with this script already:
```
TEST_OPTS="--input-file /home/cbiwer/projects/inference_convert_cli/test/test.hdf --output-file /home/cbiwer/public_html/tmp/tmp.png --iteration 1 --plot-marginal --plot-density --verbose"
pycbc_inference_plot_posterior ${TEST_OPTS} --parameters q

PRECESSING_OPTS="--input-file /home/soumi.de/projects/cbc/inference_for_events/GW150914/H1L1/inference_GW150914_H1L1_100000iter.hdf --output-file /home/cbiwer/public_html/tmp/tmp.png --iteration 5999 --plot-marginal --plot-density --verbose"
pycbc_inference_plot_posterior ${PRECESSING_OPTS} --parameters chi_a
pycbc_inference_plot_posterior ${PRECESSING_OPTS} --parameters mchirp
pycbc_inference_plot_posterior ${PRECESSING_OPTS} --parameters "chi_eff/(2):\$\chi_{eff} / 2\$" spin1x spin2_a chi_p mass1 redshift
pycbc_inference_plot_posterior ${PRECESSING_OPTS} --parameters "chi_eff/(2):\$\chi_{eff} / 2\$"
pycbc_inference_plot_posterior ${PRECESSING_OPTS} --parameters spin1x

ALIGNED_OPTS="--input-file /home/cbiwer/projects/inference_workflow/dev/H1L1-INFERENCE_0-1126259460-4.hdf --output-file /home/cbiwer/public_html/tmp/tmp.png --iteration 19999 --plot-marginal --plot-density --verbose"
pycbc_inference_plot_posterior ${ALIGNED_OPTS} --parameters mass1 "chi_eff/(2):\$\chi_{eff} / 2\$"
pycbc_inference_plot_posterior ${ALIGNED_OPTS} --parameters "mass1/(1+redshift):\$m_{1}^\mathrm{src}\$"
pycbc_inference_plot_posterior ${ALIGNED_OPTS} --parameters mass1 redshift "mass1/(1+redshift):\$m_{1}^\mathrm{src}\$"
pycbc_inference_plot_posterior ${ALIGNED_OPTS} --parameters chi_eff
pycbc_inference_plot_posterior ${ALIGNED_OPTS} --parameters chi_eff mass1
pycbc_inference_plot_posterior ${ALIGNED_OPTS} --parameters mass1
pycbc_inference_plot_posterior ${ALIGNED_OPTS} --parameters mchirp q spin1z
pycbc_inference_plot_posterior ${ALIGNED_OPTS} --parameters mchirp q polarization
pycbc_inference_plot_posterior ${ALIGNED_OPTS} --parameters redshift
```

**Comment by soumide1102** [comment]
@cmbiwer I tested the latest version of this PR, and it worked for all that I was plotting. Thanks!

**Comment by cmbiwer** [comment]
Ok thanks. Collin can you take a look at this then.

**Comment by cdcapano** [comment]
Sorry for being slow on reviewing. I'm a bit unsure about this patch. First, @cmbiwer, what did you mean by: 

> PR #1567 does not solve sampling in spherical coordinates and would require a duplication of all the functions in conversions.py.

All of the functions in coordinates.py are included in the FieldArray function library, so it should be possible to do any cartesian <-> spherical conversion on the command line. Or did I forget something in #1567 ?

I do realize that we now have long arguments if you want to plot something other than what was sampled. Is that what this patch is trying to fix? If so, I understand the desire to shorten the arguments... having to do `mass1_from_mchirp_q(mchirp, q)/(1+redshift(distance)):$\mathcal{M}$` whenever you want to plot source mass1 is a bit of a pain. But I'm not sure trying to code up all possible conversions is the best way. The problem is there are a large number of possible combinations of sampling parameters, and that could make this code quickly balloon. Already, I've found that this patch does not work if you sample in `mass1` and `mass2` (as I have been) but want to plot `mtotal`. You could figure out how to deal with that, but it's going to be tough to anticipate all possible combinations of things users may do. It also makes it a pain if we want to add new parameter combinations for priors (as we are with the uniform chi_p/chi_eff).

So... balancing the two... what about this? What if you write a function that adds virtual fields to add to the samples array on loading? You'd only need to store two strings for each field in the results file --- the string giving the function call and the name to call the field --- and so this could be stored in the attributes of the inference file. The following would do the trick:
```
# factory function for creating class method that can be added as a virtual field
def create_vfield(fstring):
    def fnc(self):
        return self[fstring]
    return fnc

# function that takes a name, a string calling a function in the FieldArray functionlib with base fields, a FieldArray of samples, and returns that as a new array with the virtual field added
def add_vfield_from_fstring(name, fstring, samples):
    fnc = create_vfield(fstring)
    return samples.add_virtualfields(name, fnc)
```
So, for example, if you sampled in `mchirp, q`, and wanted `mass1` to be a virtual field:
```
samples = add_vfield_from_fstring('mass1', 'mass1_from_mchirp_q(mchirp, q)', samples)
```
would do it.

You could add a section to the ini file that specifies some virtual fields the user thinks will be useful, something like:
```
[virtual_parameters]
; left side is the name of the parameter to create, right side is how to create it
; from the sampling parameters. Any function in coversions.py, coordinates.py,
; or cosmology.py may be used.
mass1 = mass1_from_mchirp_q(mchirp, q)
mass2 = mass2_from_mchirp_q(mchirp, q)
<etc.>
```
The tuples of `(name, fstring)` are added to the output file's attributes by `pycbc_inference`, and these are used to add the fields when loading samples by `read_samples`. It might also be good to write a small executable that can add virtual fields to the result file, in case the user decides to add more fields after doing a run.

In that way, the user is free to define whatever combination of parameters they want based on whatever they sampled in, instead of us trying to anticipate all possible combinations. Does that sound reasonable?

**Comment by cmbiwer** [comment]
>> All of the functions in coordinates.py are included in the FieldArray function library, so it should be possible to do any cartesian <-> spherical conversion on the command line. Or did I forget something in #1567 ?

What is the recommended way to plot ``chi_p`` when you sampling in spherical coordinates?

>> But I'm not sure trying to code up all possible conversions is the best way. The problem is there are a large number of possible combinations of sampling parameters, and that could make this code quickly balloon.

Look at the top of ``generator.py`` where the same thing is going on there (I would like for these classes to replace those functions). Is there a solution to get from sampling parameters to waveform generator inputs then? Because we already require these same sorts of conversions there.

There actually are not that many in my opinion either. At the moments there's (``mchirp``, ``q``), (``mass1``, ``mass2``), cartesian spins, spherical spins, and then adding the mass-weighted spins. How many more are planned to be added?

>> Already, I've found that this patch does not work if you sample in mass1 and mass2 (as I have been) but want to plot mtotal.

I didn't add conversions for ``mtotal`` and ``eta``.

I'm going to be a stick in the mud here because there's a simple rule: If you don't like it, then you don't have to use it. This PR takes away no functionality and only adds two lines to ``option_utils``.

If you want me to add one for ``mtotal`` and ``eta`` then I'll do it. But otherwise unless there's something wrong, I'd prefer not to have to specify it ahead of time in a config file and I'd like to use this functionality.

**Comment by cdcapano** [comment]
> What is the recommended way to plot chi_p when you sampling in spherical coordinates?

Oh, yeah, you can do it, but it's long...
```
chi_p(mass1_from_mchirp_q(mchirp, q), mass2_from_mchirp_q(mchirp, q), *spherical_to_cartesian(spin1a, spin1_phi, spin1_polar)[:2]+spherical_to_cartesian(spin2a, spin2_phi, spin2_polar)[:2])
```
We should probably just have a `chi_p_from_spherical` function in `conversions.py`.

> Look at the top of generator.py where the same thing is going on there (I would like for these classes to replace those functions). Is there a solution to get from sampling parameters to waveform generator inputs then? Because we already require these same sorts of conversions there.

There is a difference between what happens there and what you're trying to accomplish here. The waveform generator always needs the same set of parameters, `mass1, mass2, spin1x, etc.`, so the conversions you need to do are always `some combination of parameters -> fixed set of parameters`. Here, however, the user may want any number of a set of parameters, so the mappings you need to anticipate are `some combination of parameters -> some other combination of parameters`. That's difficult to anticipate.

That said, it is nice to have a conversion module that will do the conversions at the top of `generator.py`, and this should replace those functions. They are kind of awkwardly stuck there. Were you planning on doing that? (If so, do it an another patch.)

For using these for plotting, you're right that you can just ignore these shortcuts if you don't want to use them. So, I'll approve this (and no, you don't have to add mtotal and eta), with the caveat that I want the other solution I suggested added at some point (either you or I can do it).

**Pull request merged**
