### PR TITLE
pycbc_coinc_time arguments change

### PR DESCRIPTION
**Pull request by lauranuttall**
Added a fix to the science/veto-levels arguments to allow more than one level to be added. Updated help message to reflect this.

### CODE REVIEW

**Comment by ahnitz** [comment]
Laura, 

This is ins't quite right, you do not want to set nargs to '+' here. I am using the same syntax as the workflow generator. See the example I had given in the pull request,

>
pycbc_coinc_time \
--science-names H1:DMT-ANALYSIS_READY:1 L1:DMT-ANALYSIS_READY:1 \
--gps-start-time 1124349317 \
--gps-end-time 1125990017 \
--segment-server segments.ligo.org \
--analysis-start-pad 120 \
--analysis-end-pad 24 \
--science-veto-levels 1 \
--trigger-veto-levels 12H \
--minimum-segment-length 2064 \
--veto-definer H1L1V1-ER8_CBC_OFFLINE.xml \
--verbose

"12H', means removing CAT1/2 and Hardware injections. Also, you don't want to change the analysis start or end padding, it is correct here for the analysis we are doing. 

The help messages are not so helpful, so I'll work on fixing that.

**Comment by lauranuttall** [comment]
OK, I removed nargs '+' and tried to run the original script with the options you out. I still can't get the script to run though, I get the following error:

pycbc_coinc_time --gps-start-time 1126051217 --gps-end-time 1126562417 --veto-definer H1L1-HOFT_C00_ER8_CBC.xml --science-names H1:DMT-ANALYSIS_READY:1 L1:DMT-ANALYSIS_READY:1 --segment-server segments.ligo.org --analysis-start-pad 120 --analysis-end-pad 24 --minimum-segment-length 2064 --science-veto-levels 1 --trigger-veto-levels 12H
Traceback (most recent call last):
  File "/home/laura.nuttall/pycbc-dev/bin/pycbc_coinc_time", line 4, in <module>
    __import__('pkg_resources').run_script('PyCBC==15706rc0', 'pycbc_coinc_time')
  File "/home/laura.nuttall/pycbc-dev/lib64/python2.6/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/laura.nuttall/pycbc-dev/lib64/python2.6/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/home/laura.nuttall/pycbc-dev/lib/python2.6/site-packages/PyCBC-15706rc0-py2.6.egg/EGG-INFO/scripts/pycbc_coinc_time", line 160, in <module>
    args.gps_end_time,
  File "/home/laura.nuttall/pycbc-dev/lib/python2.6/site-packages/PyCBC-15706rc0-py2.6.egg/EGG-INFO/scripts/pycbc_coinc_time", line 67, in get_vetoes
    flags = veto_def[ifo][cat]
KeyError: 3

Also (I obviously trust your judgment with the numbers) where did you get the analysis-start/end-pad and minimum-segment-length numbers? I took the original numbers I used from: https://code.pycbc.phy.syr.edu/alex-nitz/pycbc-config/blob/m1/ER8/pipeline/analysis.ini

**Comment by ahnitz** [comment]
Hi Laura, 

Huh, strange. When I run the command you posted it works fine. Here is the verbose output.

ahnitz@atlas7:~$ pycbc_coinc_time --gps-start-time 1126051217 --gps-end-time 1126562417 --veto-definer H1L1-HOFT_C00_ER8_CBC.xml --science-names H1:DMT-ANALYSIS_READY:1 L1:DMT-ANALYSIS_READY:1 --segment-server segments.ligo.org --analysis-start-pad 120 --analysis-end-pad 24 --minimum-segment-length 2064 --science-veto-levels 1 --trigger-veto-levels 12H --verbose
2015-09-18 04:11:13,452 For IFO: H1, querying science time (DMT-ANALYSIS_READY, 1)
2015-09-18 04:11:15,047 Found 257070s of data
2015-09-18 04:11:20,049 Found 219223s after applying CAT1 vetoes
2015-09-18 04:11:20,049 Removing segments shorter than 2064s
2015-09-18 04:11:20,049 Found 211769s after applying removing padding / short segments
211728 211728 0
2015-09-18 04:11:29,021 Found 211728s after applying trigger vetoes
2015-09-18 04:11:29,021 For IFO: L1, querying science time (DMT-ANALYSIS_READY, 1)
2015-09-18 04:11:30,332 Found 147963s of data
2015-09-18 04:11:34,090 Found 142871s after applying CAT1 vetoes
2015-09-18 04:11:34,090 Removing segments shorter than 2064s
2015-09-18 04:11:34,090 Found 136158s after applying removing padding / short segments
136158 136158 0
2015-09-18 04:11:41,837 Found 136158s after applying trigger vetoes
Available Coincident Time from 1126051217-1126562417
90474 seconds, 1.04715 days

I pulled the veto definer using the curl command duncan posted.

curl https://code.pycbc.phy.syr.edu/ligo-cbc/pycbc-config/download/849bb16a90b882a83e56f6aff291a4760109db5d/ER8/dq/H1L1-HOFT_C00_ER8_CBC.xml 

 Are you using the same one? 

As for the other options, the padding has to be the complete padding on the data, not just the padding for the analysis segments (the chunking we do for each FFT). There is another 8 second padding on either end we through away before even doing matched-filtering. 

The minimum-segment-length should maybe be named minimum-science-segment-length. It is the amount of data that the shortest job needs to reed in. In this case 2048 + 16 seconds

**Comment by ahnitz** [comment]
Ok, I think this might confuse people in the future too, so is it worth using the exactly same options?

I would replace 

--analysis-start-pad
--analysis-end-pad
--minimum-segment-length

With

--segment-start-pad
--segment-end-pad
--pad-data
--segment-length
--min-analysis-segments

These can be used to recompute the more condensed values.

**Comment by lauranuttall** [comment]
Ok I've got it to work, but what is confusing me more now is how we have gotten different times despite having the same options. I guess there must be a difference on atlas vs sugar:

pycbc_coinc_time --gps-start-time 1126051217 --gps-end-time 1126562417 --veto-definer H1L1-HOFT_C00_ER8_CBC.xml --science-names H1:DMT-ANALYSIS_READY:1 L1:DMT-ANALYSIS_READY:1 --segment-server segments.ligo.org --analysis-start-pad 120 --analysis-end-pad 24 --minimum-segment-length 2064 --science-veto-levels 1 --trigger-veto-levels 12H --verbose
2015-09-17 22:26:51,358 For IFO: H1, querying science time (DMT-ANALYSIS_READY, 1)
2015-09-17 22:26:52,507 Found 256799s of data
2015-09-17 22:26:55,717 Found 218952s after applying CAT1 vetoes
2015-09-17 22:26:55,717 Removing segments shorter than 2064s
2015-09-17 22:26:55,718 Found 211498s after applying removing padding / short segments
2015-09-17 22:27:06,254 Found 211457s after applying trigger vetoes
2015-09-17 22:27:06,255 For IFO: L1, querying science time (DMT-ANALYSIS_READY, 1)
2015-09-17 22:27:07,216 Found 147740s of data
2015-09-17 22:27:09,617 Found 142648s after applying CAT1 vetoes
2015-09-17 22:27:09,617 Removing segments shorter than 2064s
2015-09-17 22:27:09,618 Found 135935s after applying removing padding / short segments
2015-09-17 22:27:14,428 Found 135935s after applying trigger vetoes
Available Coincident Time from 1126051217-1126562417
90251 seconds, 1.04457 days

I agree that the option names need to be changed, like you said this will confuse people in the future if there are exact same names in the ini file that aren't the same here.

**Comment by ahnitz** [comment]
I just checked and that was my mistake. I accidentally posted the output for a slightly different gps time. I retried your and it gives exactly the same answer.

**Comment by lauranuttall** [comment]
Few. Ok then. I'll cancel this pull request in the morning and if you could add your updates that would be great. Thanks for checking over this!

**Pull request closed without merging**
