### PR TITLE
add pycbc example for calibrating data

### PR DESCRIPTION
**Pull request by cmbiwer**
This PR adds an example for filtering `DARM_ERR` and `DARM_CTRL` to reproduce the front-end calibration.

You can view the example in `examples/cal/calibrate_data/`.

There is a docs page for the example in `docs/calibration.rst`.

Laura, can you follow the instructions and see if you can reproduce the `OAF-CAL_DARM_DQ` channel that is in the frame files? If that looks ok, then take a look at the executable.

### CODE REVIEW

**Comment by lauranuttall** [comment]
Chris: I can't see calibration.rst in the docs dir.

**Comment by cmbiwer** [comment]
You might not be looking at my branch.

You can click the "Files changed" tab on this page to see all the lines of code that I added/changed.

Or try this direct link to the doc: https://github.com/cmbiwer/pycbc/blob/cal2_dev/docs/calibration.rst

**Comment by lauranuttall** [comment]
I'm getting an error:

Traceback (most recent call last):
  File "./pycbc_calibrate_data", line 160, in <module>
    sum_darm_out_filtered = gain_m0*darm_out_m0_filtered + gain_l1*darm_out_l1_filtered + gain_l2*darm_out_l2_filtered + gain_l3*darm_out_l3_filtered
TypeError: unsupported operand type(s) for +: 'numpy.ndarray' and 'TimeSeries'

**Comment by cmbiwer** [comment]
I didn't see this error when I ran but I think I see where it would come from. I pushed another commit, could you pull the latest version of `cal2_dev` and try again? Thanks.

**Comment by lauranuttall** [comment]
I can get to the plotting stage - now a few things. The first error I get is:

Traceback (most recent call last):
  File "./pycbc_plot_frame", line 28, in <module>
    data.save('output/frame.txt')
  File "/home/laura.nuttall/.local/lib/python2.6/site-packages/pycbc/types/timeseries.py", line 392, in save
    _numpy.savetxt(path, output)
  File "/mnt/home2/detchar/opt/gwpysoft/lib64/python2.6/site-packages/numpy/lib/npyio.py", line 1028, in savetxt
    fh = open(fname, 'w')
IOError: [Errno 2] No such file or directory: 'output/frame.txt'

I simply made the output directory to see if I could make it to the end. Firstly, cal_dev_frame.png is not in the same location as the other png (I suspect they are both supposed to be in ~/public-html/tmp/cal_dev/)  and https://ldas-jobs.ligo-la.caltech.edu/~laura.nuttall/tmp/cal_dev/calibrate_oaf_cal_darm_dq_5.png is empty.

**Comment by cmbiwer** [comment]
I pushed the fix for the plotting code. It was trying to write to a directory that didn't exist.

Though I can't reproduce your result, can you send me your path and what cluster you are using?

**Comment by lauranuttall** [comment]
I'm on llo in /home/laura.nuttall/git/pycbc_fork/examples/cal/calibrate_data

**Comment by duncan-brown** [comment]
@cmbiwer let's figure out what we should do with this.

**Comment by ahnitz** [comment]
Chris, are these patches still relevant?

**Comment by ahnitz** [comment]
Chris, I'm closing this. Please re-open if it is still relevant.

**Pull request closed without merging**
