### PR TITLE
Add the ability to compute the comoving range

### PR DESCRIPTION
**Pull request by duncan-brown**
This pull request primarily adds some code from Jolien that does a Finn and Chernoff-style MC to compute the redshift-corrected SenseMon range.  It also cleans up some other issues with the code (e.g. better titles and labels) and adds the ability to print luminosity, source-frame horizon (i.e. don't divide by 2.26).

### CODE REVIEW

**Comment by ahnitz** [comment]
@duncan-brown I don't think I'll be able to look at this today or tomorrow, but  couple questions. Is this backwards compatible with the old options? and if not, will we need to update the workflow ini files for this?

**Comment by duncan-brown** [comment]
@ahnitz this isn't urgent, so no rush. Yes, it's backwards compatible with the old options.

**Comment by duncan-brown** [comment]
My crappy PSD decimation code gives about a percent loss in range accuracy for a significant code speed up in the Monte Carlo:
```
2017-01-31 16:06:03,786 Input PSD size 524289 at resolution: 0.00195312 Hz
2017-01-31 16:06:03,891 PSD decimated by factor 128 to size 4097 at resolution: 0.25 Hz
2017-01-31 16:06:03,957 horizon redshift = 0.477805
2017-01-31 16:06:03,958 horizon luminosity distance = 2.75572 Gpc
2017-01-31 16:06:03,958 VT / T of horizon = 20.2619 Gpc
2017-01-31 16:06:03,958 Range of horizon: = 1.69121 Gpc
```
compared to
```
2017-01-31 16:06:28,471 horizon redshift = 0.474153
2017-01-31 16:06:28,471 horizon luminosity distance = 2.73063 Gpc
2017-01-31 16:06:28,471 VT / T of horizon = 19.8969 Gpc
2017-01-31 16:06:28,472 Range of horizon: = 1.68099 Gpc
```
and
```
2017-01-31 16:07:07,914 Calculating range for PSD 0 / 2795
2017-01-31 16:07:08,260 Inspiral Range (Mpc) = 880.567
2017-01-31 16:07:08,260 Calculating range for PSD 1 / 2795
2017-01-31 16:07:08,604 Inspiral Range (Mpc) = 880.137
2017-01-31 16:07:08,604 Calculating range for PSD 2 / 2795
2017-01-31 16:07:08,941 Inspiral Range (Mpc) = 917.996
```
compared to
```
2017-01-31 16:07:14,397 Calculating range for PSD 0 / 2795
2017-01-31 16:07:14,427 Input PSD size 524289 at resolution: 0.00195312 Hz
2017-01-31 16:07:14,592 PSD decimated by factor 128 to size 4097 at resolution: 0.25 Hz
2017-01-31 16:07:14,596 Inspiral Range (Mpc) = 886.271
2017-01-31 16:07:14,596 Calculating range for PSD 1 / 2795
2017-01-31 16:07:14,620 Input PSD size 524289 at resolution: 0.00195312 Hz
2017-01-31 16:07:14,727 PSD decimated by factor 128 to size 4097 at resolution: 0.25 Hz
2017-01-31 16:07:14,731 Inspiral Range (Mpc) = 883.587
2017-01-31 16:07:14,732 Calculating range for PSD 2 / 2795
2017-01-31 16:07:14,756 Input PSD size 524289 at resolution: 0.00195312 Hz
2017-01-31 16:07:14,858 PSD decimated by factor 128 to size 4097 at resolution: 0.25 Hz
2017-01-31 16:07:14,862 Inspiral Range (Mpc) = 926.707
```

**Comment by duncan-brown** [comment]
Jolien has some suggestions for improvement, so I'm flagging as WIP.

**Comment by ahnitz** [comment]
I request you consider adding some of the functions to Collin's cosmology module when that's merged as well.

**Comment by duncan-brown** [comment]
Closing this for the moment. Will come back to it after O2.

**Pull request closed without merging**
