### PR TITLE
Adding segment plot to and cleaning up result page

### PR DESCRIPTION
**Pull request by a-r-williamson**
A segment availability plot is now generated at run-time and will show the offsource segment in the context of all search IFOs' science segments. If no workflow is generated due to lack of data this is also shown on this plot.

If we have sufficient science data, the plot is passed through to the results page, which has been cleaned up slightly.

### CODE REVIEW

**Comment by a-r-williamson** [comment]
Example plot:
grbexample_segments

**Comment by spxiwh** [comment]
Hi Andrew, I am happy with these changes. Please merge once sanity checks complete.

**Comment by duncan-brown** [comment]
This merge breaks ```pycbc_make_coinc_search_workflow``` so I am reverting it.

```python
Traceback (most recent call last):
  File "/home/dbrown/src/pycbc-dev/bin/pycbc_make_coinc_search_workflow", line 4, in <module>
    __import__('pkg_resources').run_script('PyCBC===98acab', 'pycbc_make_coinc_search_workflow')
  File "/home/dbrown/src/pycbc-dev/lib/python2.6/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/dbrown/src/pycbc-dev/lib/python2.6/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/home/dbrown/src/pycbc-dev/lib/python2.6/site-packages/PyCBC-98acab-py2.6.egg/EGG-INFO/scripts/pycbc_make_coinc_search_workflow", line 30, in <module>
    import pycbc.events, pycbc.workflow as wf
  File "/home/dbrown/src/pycbc-dev/lib/python2.6/site-packages/PyCBC-98acab-py2.6.egg/pycbc/workflow/__init__.py", line 39, in <module>
    from pycbc.workflow.segment import *
  File "/home/dbrown/src/pycbc-dev/lib/python2.6/site-packages/PyCBC-98acab-py2.6.egg/pycbc/workflow/segment.py", line 39, in <module>
    from pycbc.results.legacy_grb import make_grb_segments_plot
  File "/home/dbrown/src/pycbc-dev/lib/python2.6/site-packages/PyCBC-98acab-py2.6.egg/pycbc/results/__init__.py", line 6, in <module>
    from pycbc.results.legacy_grb import *
  File "/home/dbrown/src/pycbc-dev/lib/python2.6/site-packages/PyCBC-98acab-py2.6.egg/pycbc/results/legacy_grb.py", line 27, in <module>
    import matplotlib.pyplot as plt
  File "/home/dbrown/src/pycbc-dev/lib/python2.6/site-packages/matplotlib/pyplot.py", line 109, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/dbrown/src/pycbc-dev/lib/python2.6/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/home/dbrown/src/pycbc-dev/lib/python2.6/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from six.moves import tkinter as Tk
  File "/home/dbrown/src/pycbc-dev/lib/python2.6/site-packages/six.py", line 199, in load_module
    mod = mod._resolve()
  File "/home/dbrown/src/pycbc-dev/lib/python2.6/site-packages/six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "/home/dbrown/src/pycbc-dev/lib/python2.6/site-packages/six.py", line 80, in _import_module
    __import__(name)
ImportError: No module named Tkinter
```

**Comment by duncan-brown** [comment]
This works if Tkinter is installed, which it wasn't on the OSG head node where I was testing ```pycbc_make_coinc_search_workflow```. I have installed the RPM and can get around this patch.

However, I don't understand why the GRB plotting lives in the generic workflow/segments.py module. I should be able to run ```pycbc_make_coinc_search_workflow``` without importing the GRB segment plotting code. @a-r-williamson please can you prepare a patch to clean this up?

**Comment by ahnitz** [comment]
Duncan,

The code doesn't seem to use the module explicitly. It is just importing
matplotlib. That's not ideal, but even if you can get the workflow
generator to run from some non-standard environment, won't we have problems
with all the other plotting codes failing down the line? Are you solving
that through some other method? Also, is there a reason OSG isn't a good
candidate for the prebuilt executables?

**Comment by duncan-brown** [comment]
@ahnitz I was testing a on sugar-dev2 which we had not installed all of LIGO RPMs on, so tkinter was missing. This was fine until @a-r-williamson's commit. 

The only non-bundled code I've been running on OSG is the version of ```pycbc_make_coinc_search_workflow``` and ```pycbc_submit_dax``` from my development branch during testing. In general this won't be a problem as everything would be pre-built bundles.

**Comment by ahnitz** [comment]
Ok, thanks. That makes sense then.

**Pull request merged**
