### PR TITLE
add sine-Gaussian chisq class, update pycbc_inspiral

### PR DESCRIPTION
**Pull request by ahnitz**
This splits off just the changes to add the sine-Gaussian chisq to pycbc_inspiral.

### CODE REVIEW

**Comment by spxiwh** [comment]
@ahnitz I'm mostly happy with these changes, but please do comment on the pull requests. The issue about overriding a `values` attribute does seem a bit hacky .. Do we actually need to ChiSquared base class, and if so could it be refactored, or is this not a problem here?

**Comment by spxiwh** [comment]
Sorry, please comment on the code issues highlighted by Codacy and landscape (QC seems redundant)

**Comment by spxiwh** [comment]
... And fix the whitespace issues.

**Comment by ahnitz** [comment]
@spxiwh Thanks, I just attempted to fix some of the whitesapce issues, so we'll see how that goes. It is easier to subclass from SingleDetChisq to enable use of its methods for caching chisq bins, so I don't see a problem with this.

**Comment by spxiwh** [comment]
I guess the better solution would be to create a class with the stuff that Chisq and SQChisq shares and have both inherit that ... But I won't require that for this patch.

**Comment by duncan-brown** [comment]
@ahnitz just to confirm, if ``--sgchisq-snr-threshold`` and ``--sgchisq-locations`` are **not** passed to ``pycbc_inspiral`` the code implements the old behavior?

**Pull request merged**
