### PR TITLE
add more colorbar options to coinc snrchi

### PR DESCRIPTION
**Pull request by ahnitz**
Add the choice of what is plotted for the color in the coinc snrchi plots

* effective distance
* mchirp
* eta
* weighted spin

### CODE REVIEW

**Comment by tdent** [comment]
Hi Alex, this is quite useful - could you also include total mass?  
Also please use the phenomb_chi function I recently added to pnutils.py rather than coding the effective spin by hand again.

**Comment by ahnitz** [comment]
Tom,

Is there a reason that the function is phenomb_chi? I think that is a really bad name. Why not just effective_spin? Also, I don't like the fact that it is calling into lalsimulation for such a simple formula.

**Comment by tdent** [comment]
There are different formulae for effective aligned spin in the literature, in the low-mass limit it is something more complicated which can be read off from the PN formulae.  This one was, I think, an approximation first used to parameterize the PhenomB model for higher-mass BBH and called 'chi' in that context. 
Yes, the formula is simple but the more times you code it by hand the higher the probability of making a typo and the harder it is to check that our code is consistent as a whole.  If LALSimulation has the correct function we should use it.

**Comment by ahnitz** [comment]
Ok, changes should be done. Is this ok to merge now?

**Comment by tdent** [comment]
Yup. I'm not sure whether making the colorbar log for eta is the best choice, but we'll see how it turns out.

**Pull request merged**
