### PR TITLE
allow workflows to run on internaly made Gaussian noise with a given PSD

### PR DESCRIPTION
**Pull request by ahnitz**
I'm opening this to start the debug process on travis. I can do no testing atm due to ATLAS being down though. This should be the minimal change set required to make this work in a reasonable fashion, in conjuction with changes to the config file for this mode. I haven't changed segment handling so atm, that is bootstrapped with whatever you like. That could be simplified as well to have a no segments query mode, where all time is good option.

For all PyCBC user: When this is merged, fake strain will not return the same realization it used to.

### CODE REVIEW

**Comment by ahnitz** [comment]
To run on a standard offline workflow (or anything else that reuses these modules). 

1) change the datafind method to "AT_RUNTIME_FAKE_DATA"
2) Turn off all segment / frame / summary checks
3) add to inspiral / single_template / psd / timefreq sections the fake frame options as standard from the strain module

**Comment by ahnitz** [comment]
Here's an example completed run. 

https://www.atlas.aei.uni-hannover.de/~ahnitz/LSC/projects/O2/higher_modes/gtest/output/html/

**Comment by ahnitz** [comment]
There appears to be a bit more memory usage (several gigs) when using this. I have some ideas to reduce this, but won't have the chance before, I think. So, for now bump the memory request of jobs.

**Comment by spxiwh** [comment]
I'm not seeing the same large memory usage for inspiral jobs. I see a small increase (which I think I can fix), but not a huge one. For the calculate-PSD jobs this seems to be a bigger effect ... Was that what you meant? That the issue was in calculate_PSD?

**Comment by spxiwh** [comment]
(My solution is to avoid np.concatenate and instead create a numpy.zeros to hold the full data set and then fill this chunk by chunk.)

**Comment by spxiwh** [comment]
Deleting comments above, as the memory usage of the fake strain is a little higher than zeroNoise because the PSD is estimated on the full dataset and not because of concatenate operations.

**Comment by spxiwh** [comment]
One potential issue with the new reproducible module though is that while the *white* noise will always be the same, the *colored* noise can be different for different time windows. In other words if I ask for data in [0,1000] and then in [0,500] and [500,1000] and cat the latter 2 together, I do not have the same data sets .... Maybe using a non-wrapping time-domain convolution with the PSD auto-correlation function instead of a frequency-domain whitening would make this more reproducible?

**Comment by spxiwh** [comment]
I'll merge this now and then open up a PR for memory reducing later.

**Pull request merged**
