### PR TITLE
Add square root distribution

### PR DESCRIPTION
**Pull request by cmbiwer**
For sampling uniform in ``chi_p`` want to add a distribution that samples uniform in the PDF ``p(x)=c*x^(0.5)``.

This is essentially the same calculation as sampling uniform volume, except the index of the power law is 0.5 instead of 3.

Needs some documentation.

EDIT: Fixed equation.

### CODE REVIEW

**Comment by cmbiwer** [comment]
I've included transformations from going back and forth from:
```
spin1x,spin1y,spin1z,spin2x,spin2y,spin2z <-> chi_eff,chi_a,phi_a,phi_s,xi1,xi2
```

This bit needs some better docstrings in parts and I need to do a more exhaustive that the primary/secondary masses/spins are being selecting in the appropriate functions that need it.

An example script for the simple test converting between these two coordinates:
```
import numpy
from pycbc import conversions

mass1 = 20.4
mass2 = 1.4

xi1 = 0.11
xi2 = 0.13
phi_a = 0.39
phi_s = 0.44
chi_eff = 0.21
chi_a = 0.12

spin1z = conversions.spin1z_from_mass1_mass2_chi_eff_chi_a(mass1, mass2, chi_eff, chi_a)
spin2z = conversions.spin2z_from_mass1_mass2_chi_eff_chi_a(mass1, mass2, chi_eff, chi_a)
spin1x = conversions.spin1x_from_xi1_phi_a_phi_s(xi1, phi_a, phi_s)
spin1y = conversions.spin1y_from_xi1_phi_a_phi_s(xi1, phi_a, phi_s)
spin2x = conversions.spin2x_from_mass1_mass2_xi2_phi_a_phi_s(mass1, mass2, xi2, phi_a, phi_s)
spin2y = conversions.spin2y_from_mass1_mass2_xi2_phi_a_phi_s(mass1, mass2, xi2, phi_a, phi_s)

print "spin1x", spin1x
print "spin2x", spin2x
print "spin1y", spin1y
print "spin2y", spin2y
print "spin1z", spin1z
print "spin2z", spin2z
print "|s1|", numpy.sqrt(spin1x**2 + spin1y**2 + spin1z**2)
print "|s2|", numpy.sqrt(spin2x**2 + spin2y**2 + spin2z**2)

xi1 = conversions.primary_xi(spin1x, spin1y)
xi2 = conversions.secondary_xi(mass1, mass2, spin2x, spin2y)
chi_eff = conversions.chi_eff(mass1, mass2, spin1z, spin2z)
chi_a = conversions.chi_a(mass1, mass2, spin1z, spin2z)
phi_a = conversions.phi_a(spin1x, spin1y, spin2x, spin2y)
phi_s = conversions.phi_s(spin1x, spin1y, spin2x, spin2y)

print "xi1", xi1
print "xi2", xi2
print "phi_a", phi_a
print "phi_s", phi_s
print "chi_eff", chi_eff
print "chi_a", chi_a
```

**Comment by cdcapano** [comment]
@cmbiwer Can you split off the change to `conversions.py` to a new pull request, then update this for the new distributions?

**Comment by cdcapano** [comment]
@cmbiwer poke

**Comment by cmbiwer** [comment]
Replaced by other PRs.

**Pull request closed without merging**
