### PR TITLE
Add network snr as possible coinc stat

### PR DESCRIPTION
**Pull request by tdent**
To give a proper statement of network SNR for an event we need the highest network SNR coinc, which requires this statistic to be recognized by the coinc code.

### CODE REVIEW

**Comment by spxiwh** [comment]
This is bizzarre. I was about to open the very same pul request!

**Comment by spxiwh** [comment]
@tdent Can you rebase this against master? This is based against quite an old version of master, so isn't really doing the testing right, and is confusing landscape.

**Comment by spxiwh** [comment]
Ah, screw it. I'll run landscape myself after this is merged to make sure everything is fine and merge now, as this is quite simple. Please do rebase in the future though.

**Comment by tdent** [comment]
I just failed by a few seconds to screw it and instead did rebase and push, so not sure what state that will leave this in ...

**Comment by spxiwh** [comment]
Master is fine:

https://github.com/ligo-cbc/pycbc/commit/f134e09649db62535742b1b4e1405978a00314b4

you can delete your local branch.

**Pull request merged**
