### PR TITLE
Fix the items in the available segments table

### PR DESCRIPTION
**Pull request by duncan-brown**
Obsoletes https://github.com/ligo-cbc/pycbc/pull/580

### CODE REVIEW

**Comment by duncan-brown** [comment]
Test running at https://sugar-dev2.phy.syr.edu/pegasus/u/dbrown/r/167/w?wf_uuid=feedff07-2063-4ad5-8c3c-e29c3ac3cb5b

**Comment by duncan-brown** [comment]
Testing now at https://sugar-dev2.phy.syr.edu/pegasus/u/dbrown/r/168/w?wf_uuid=78bc7838-9323-4c55-bcfe-2ebfde4c20d9

**Comment by ahnitz** [comment]
Thanks Duncan, I'll take a look when the results are ready.

**Comment by duncan-brown** [comment]
Looks correct: https://sugar-jobs.phy.syr.edu/~dbrown/orange-grid/sugar-nonsharedfs-test-12/

**Pull request merged**
