### PR TITLE
Add marginalized phase likelihood

### PR DESCRIPTION
**Pull request by cdcapano**
This adds a likelihood class that analytically marginalizes over coalescence phase. This can be used with aligned-spin, dominant-mode-only waveforms (or, generally, any signal model that can be written like `h(f) ~ A(f) exp[i (Psi(f) + phi)]`, where `phi` is the nuisance parameter to be marginalized over.

Marking as work in progress right now because I haven't tested this yet.

### CODE REVIEW

**Comment by cdcapano** [comment]
Ok, I've tested this on a non-spinning injection, and it seems to work well. Here's a test using kombine with the standard Gaussian noise likelihood class on a non-spinning injection: [posterior plot](https://www2.atlas.aei.uni-hannover.de/~work-cdcapano/projects/test_phase_marginalization/no_marginalization/posterior.png).
Here is a run with the same settings using the marginalized phase (and removing `coa_phase` from the variable args): [posterior plot](https://www2.atlas.aei.uni-hannover.de/~work-cdcapano/projects/test_phase_marginalization/marginalization_no_coa_phase/posterior.png).

The latter converged in about half the number of iterations. Using `max_posterior` for the burn-in test, without phase marginalization burn in occurred after 6782 iterations, whereas with phase marginalization it burned in after 3017 iterations. Here's a couple of movies comparing the two:
 * [no phase marginalization](https://www2.atlas.aei.uni-hannover.de/~work-cdcapano/projects/test_phase_marginalization/no_marginalization/movie.mp4)
 * [with phase marginalization](https://www2.atlas.aei.uni-hannover.de/~work-cdcapano/projects/test_phase_marginalization/marginalization_no_coa_phase/movie.mp4)

I think this is ready to merge.

**Comment by cdcapano** [comment]
@vivienr poke

**Comment by ahnitz** [comment]
@cdcapano It doesn't seem like @vivienr has time at the moment to review. I think the code is clear and as far as code review, reasonably passes.

**Comment by ahnitz** [comment]
@cdcapano Feel free to merge, unless you'd like to wait to hear back from @vivienr.

**Comment by vivienr** [comment]
sorry, travels prevented me to act on this in a timely manner.

**Comment by cdcapano** [comment]
@vivienr Yes, it looks like the expression I get here is the same as Eq. 11 in LIGO-T1300326. The codacy complaints are due to line width, but I don't think I can break equation lines in documentation... so ignoring and merging.

**Pull request merged**
