### PR TITLE
Proposed v1.4.1 Release

### PR DESCRIPTION
**Pull request by a-r-williamson**
@duncan-brown ,

I have compiled a set of commits that I would like to propose form a v1.4.1 release. This fixes a few issues in the GRB pipeline, and I've tried to pull in other more general bug fixes. I've left out some of the precessing and MCMC commits as they introduce executables that, at the moment, won't build.

Let me know if I should include any other recent commits, or if there's any other problem with this proposal.

### CODE REVIEW

**Comment by duncan-brown** [comment]
@a-r-williamson any reason why this needs to be a branch, rather than just a tag on master? In PyCBC we have been using GitHub's tag/release facility, not branches. Master should always be in a non-broken state, so it should be safe to tag as a release.

You should just be able to follow the instructions at http://ligo-cbc.github.io/pycbc/latest/html/release.html

A separate branch should not (in general) be necessary.

**Comment by duncan-brown** [comment]
Tagging @spxiwh @cdcapano and @cmbiwer if there are  precessing and MCMC commits as they introduce executables that, at the moment, won't build.

**Comment by duncan-brown** [comment]
@a-r-williamson can you just patch https://github.com/ligo-cbc/pycbc/blob/master/tools/static/cant_be_built to exclude the bad executables?

**Comment by a-r-williamson** [comment]
Ok, not a problem.

**Comment by spxiwh** [comment]
@duncan-brown The precessing merge is now almost complete, but at no point did I introduce executables that don't build (as evidenced by the Travis tests). What am I missing here?

**Comment by duncan-brown** [comment]
@spxiwh I'm not sure. I was quoting @a-r-williamson above. Maybe something is not bundling correctly? Andrew, what is the exact issue?

**Comment by a-r-williamson** [comment]
@spxiwh by "don't build" I meant the process for building static versions (submitting a dag with a number of pyinstaller jobs) doesn't complete for some recent additions. And they may all be associated with the MCMC work, I didn't delve into it too deeply.

**Comment by duncan-brown** [comment]
@a-r-williamson I had not realized that those ``git checkout`` instructions had been added to page:

https://github.com/ligo-cbc/pycbc/blame/master/docs/release.rst

They are incorrect for a regular release and should only be done if a back-port of a bug fix to an old release is needed (i.e. backporting something from 1.4 to 1.3, which is what Amber was doing).

**Comment by duncan-brown** [comment]
@a-r-williamson sorry for the confusion, I have flagged this https://github.com/ligo-cbc/pycbc/issues/876

Closing this commit, as I think all that is needed is a patch to https://github.com/ligo-cbc/pycbc/blob/master/tools/static/cant_be_built  to exclude the bad executables, and then tagging master as 1.4.1

**Comment by duncan-brown** [comment]
@a-r-williamson on second thought, let's just merge this. We can make the 1.4 release series only for the O1 GRB search and use 1.5 for O2.

**Comment by a-r-williamson** [comment]
@duncan-brown ok, thanks.

Once I've generated the release fully I will still try to address the things mentioned above so they are fixed on master.

Cheers.

**Pull request merged**
