### PR TITLE
Cpuopt

### PR DESCRIPTION
**Pull request by lppekows**
This pulls in the CPU optimizations done for the nsf review and subsequent bug fixes.  It has been validated against individual inspiral jobs on the standard test data sets as well as a full workflow.

### CODE REVIEW

**Comment by ahnitz** [comment]
Larne, can you please post a link here to the validation work?

**Comment by lppekows** [comment]
Sure, the validation efforts are documented here:
https://www.lsc-group.phys.uwm.edu/ligovirgo/cbcnote/Optimization/pycbc_inspiral/merging_cpuopt?action=edit&editor=text

**Comment by ahnitz** [comment]
Ok, I've started up comparison runs with master and with this request applied. I'll let you know what the results are as soon as I get them. If they look ok, then I am happy for this to be merged.

**Comment by ahnitz** [comment]
Larne, Josh,

I've tried to run this and it fails doing operations in EventManager. I see a number of changes in that file that look like reverts of fixes we have made in the pasts months. Could you rebase that one file from master, and just pull in the changes you need for cpuopt? 

For reference, I've noticed the following features missing, but there may be others (and bug fixes), so I would really prefer if you pull changes from cpuopt to the master version of the file. 

   * keep loudest X triggers in time window has been lost
   * template duration no longer stored
   * not all dof stored correctly 

I've also walked through the other file changes, and they look OK . I'll list of couple of things that we should relax in the future, but I won't hold up the merge for. 

  * cluster window should not be given to MatchedFilter class.
  * list of segments should not be given to MatchedFilter class (use caching of the correlators instead as  it finds a new segment)

**Comment by josh-willis** [comment]
Hi Alex,

I don't know if I know how to rebase just one file, and especially how to do so where git does not think the solution is just to overwrite all of the recent features that you want preserved.

There were relatively few changes to events.py, and all were stand-alone, so I don't know why other things would have been changed.

As far as the other issues you mention (for the future) it is probably possible to do segment caching, but I'll want to think carefully about performance impacts.  I *strongly* prefer a model where in the core matched filtering engine, things happen in Python only in the class constructor, and in the matched filter loop happen only in C or library calls.  Otherwise it becomes too complex to distinguish which Python things can be safely done without impacting performance (and there's no one answer, since the effect is cumulative and strongly depends on both hardware, mode of operation, and matched filter options).  So unless there's a good use case where the segments would be expected to vary as we move over the template bank, I don't think caching them is a good idea even if it can be done.

As far as not passing the window: this requires some care, especially if we add back in the capability to somehow signal that we want events thresholded, not clustered (as Ian has asked for development work) since then a completely different function will have to be called, and we don't want to be testing for that inside of the loop every time, it should be decided only once at class construction. But we will want to expand to add in varying length windows, as could be done by passing in the clustering method as well.

**Comment by lppekows** [comment]
Hi Alex, Josh,

it wasn’t always clear how to resolve conflicts so it’s entirely possible that I made the wrong choices somewhere along the line.

Just doing a diff between the cpuopt and current master versions of events.py shows that they’ve basically completely diverged, so I don’t think the git model of incrementally applying patches is going to work here.  I’d suggest that I start with the current cpuopt and go through the commits to master manually to ensure that the purpose of each is maintained.  Any objections (or suggestions for better ways to use git to deal with this kind of situation?)

**Comment by josh-willis** [comment]
Hi Larne,

I don't know about a better way, but I'd suggest basically the opposite: start with current master.

In events.py, the only things that should be needed for cpuopt are the (schemed) definition of the function _threshold_cluster_factory, and the definitions of the two classes ThresholdCluster and _BaseThresholdCluster (and making sure the ThresholdCluster class is exported via __all__ at the bottom of the file).

I haven't tracked the recent changes to master so it's possible that something that currently happens won't get picked up if it isn't accessed through the threshold_cluster class, but I don't think cpuopt should have made any changes to EventManager itself, and git blame on (my) version of cpuopt doesn't show anywhere else that I touched that file in cpuopt.

**Comment by lppekows** [comment]
Hi,

I’ve done that and am running standalone tests.  If those look OK I’ll push -f and Alex can retry his tests.

**Comment by ahnitz** [comment]
Ok, I'll rerun my workflow tests when you've pushed.

**Comment by lppekows** [comment]
I've confirmed the changes to the output between this version and the previous one are minimal.  Alex, I think you can go ahead and run your tests.

**Comment by ahnitz** [comment]
Thanks, Larne. Test underway.

**Comment by ahnitz** [comment]
The runs should be done by EOD but already it looks like jobs are completing and at least of couple of the files look to have correct output. Fingers crossed.

**Comment by ahnitz** [comment]
I'm happy to report that this branch has passed the test as far as I am concerned. Try to spot the difference. It is very hard. You can see some triggers moving around in the single distributions though. 

Cpuopt

https://sugar-jobs.phy.syr.edu/~ahnitz/projects/verify/t2/gw/html/sensitivity/H1L1-PLOT_SENSITIVITY_MCHIRP_BINS_ALLINJ-966384015-1000000.png

https://sugar-jobs.phy.syr.edu/~ahnitz/projects/verify/t2/gw/html/background/H1L1-PLOT_SNRIFAR_FULL_DATA_FULL_123H-966384015-1000000.png

https://sugar-jobs.phy.syr.edu/~ahnitz/projects/verify/t2/gw/html/background/L1-PLOT_SNRCHI__FULL_DATA-966384015-1000000.png

Original (master)

https://sugar-jobs.phy.syr.edu/~ahnitz/projects/verify/t2o/gw/html/sensitivity/H1L1-PLOT_SENSITIVITY_MCHIRP_BINS_ALLINJ-966384015-1000000.png

https://sugar-jobs.phy.syr.edu/~ahnitz/projects/verify/t2o/gw/html/background/H1L1-PLOT_SNRIFAR_FULL_DATA_FULL_123H-966384015-1000000.png

https://sugar-jobs.phy.syr.edu/~ahnitz/projects/verify/t2o/gw/html/background/L1-PLOT_SNRCHI__FULL_DATA-966384015-1000000.png

**Pull request merged**
