### PR TITLE
plot_singles_timefreq: enable SEOBNRv2 inspiral tracks

### PR DESCRIPTION
**Pull request by titodalcanton**
Enable using different approximants (currently TaylorF2 and SEOBNRv2_ROM_DoubleSpin) to compute the inspiral time-frequency curves. This improves the plot by taking into account spins and physical termination frequencies.

### CODE REVIEW

**Comment by titodalcanton** [comment]
Tests/comparisons here:
https://www.atlas.aei.uni-hannover.de/~tito/LSC/inspiral_track_plots/1135770133_taylorf2.png
https://www.atlas.aei.uni-hannover.de/~tito/LSC/inspiral_track_plots/1135770133_variable_approx.png
https://www.atlas.aei.uni-hannover.de/~tito/LSC/inspiral_track_plots/1136540135_taylorf2.png
https://www.atlas.aei.uni-hannover.de/~tito/LSC/inspiral_track_plots/1136540135_variable_approx.png

**Comment by tdent** [comment]
Hi Tito - 
looks good, indeed.  We may as well deal with a bunch of formatting issues at the same time. 
 -  Reduce the size of the images.  Currently they are 2000*4000 pixels, that can be reduced by a factor of at least 4 without hurting visibility. 
 - Increase the axis label and tick label and title text sizes considerably. 
 - Increase the alpha for the 'ghost' tracks of not-loudest triggers which are almost invisible at the moment.

**Comment by titodalcanton** [comment]
Ok this looks more readable:
https://www.atlas.aei.uni-hannover.de/~tito/LSC/inspiral_track_plots/L1_1128050336.png

**Comment by tdent** [comment]
OK, nearly there ..  please reduce by another factor 2 in size though - the image still doesn't even fit on my laptop screen at full size.  And ideally the axis labels and ticks should be as big as the title is now.

**Comment by titodalcanton** [comment]
Done, the text sizes now match other plots in followups.

**Pull request merged**
