### PR TITLE
Add foton filtering module to pycbc

### PR DESCRIPTION
**Pull request by cmbiwer**
This PR adds a module, ``pycbc.filter.fotonfilter``, that has some functionality to filter arrays with foton filter files and get filterbank values from frame files.

I added a somewhat robust example script in ``examples/cal/foton_filter_inva/pycbc_foton_filter`` that shows how to use the module. And the script ``run_pycbc_foton_filter.sh`` in the examples dir shows how you can filter a waveform through the ``CAL-INJ_BLIND`` filterbank with ``pycbc_foton_filter``.

EDIT: Note you need ``ROOT`` and ``foton`` python packages to run this module and they are not included in the standard pycbc installation instructions.

### CODE REVIEW

**Comment by duncan-brown** [comment]
Chris, please can you wrap the root and photon imports in try/except statements and put them after the command line argument parsing, so that the documentation will build?

**Comment by cmbiwer** [comment]
Hi Duncan,

I put all the ``ROOT`` and ``foton`` imports in a try-except statement.

**Comment by lppekows** [comment]
Some work will need to be done to get PyInstaller to bundle programs that use this module.  It may be nothing worse than ensuring that ROOT is available at build time, but I'll need to check.

**Comment by cmbiwer** [comment]
This is in the examples directory. Is this an issue? Nothing uses this module aside from this example. The reason I put it in the examples dir is so it wouldn't be built with the rest of pycbc.

**Comment by lppekows** [comment]
Hi Chris,

My thought was that down the line someone might want to use this in an official "bin" program.  If that's not an immediate concern I'm happy not to worry about PyInstalling now.

**Comment by cmbiwer** [comment]
I don't think that's an immediate concern to move this stuff into ``bin/``.

**Comment by lppekows** [comment]
Sounds good, I have no objection to merging then.

**Pull request merged**
