### PR TITLE
save/load array, timeseries, frequencyseries to hdf

### PR DESCRIPTION
**Pull request by ahnitz**
Add the ability to save and load pycbc types to hdf files using the 'save' method or the load_* methods.

### CODE REVIEW

**Comment by titodalcanton** [comment]
Looks good, just two comments:
* The docstrings of the changed methods should be updated to mention the additional hdf support.
* To be consistent with the npy and txt formats, the TimeSeries.sample_times and FrequencySeries.sample_frequencies should also be saved along with the actual data.

**Comment by ahnitz** [comment]
Ok, I'll update the docstrings. I'm not so keen on including the sample times though. The only reason for the text format, I thought was to be consistent with the asd/psd format that other codes are producing/reading. Do you we need to copy this for the hdf format?

**Comment by ahnitz** [comment]
Ok, documentation updated.

**Comment by titodalcanton** [comment]
The point of having the sample times/frequencies in .txt/.npy formats is that otherwise you have no way of knowing them, so you're dropping information about the time/frequency series (i.e. you couldn't reconstruct the same time series once you've saved it to a file). In HDF you're using attributes to store the same info, so you're right, I guess we can go without the explicit sample times/frequencies in HDF and save some space.

You're converting the delta_t and delta_f to ints before saving them as attributes, is that wanted?

**Comment by ahnitz** [comment]
No, that was a bug. It is using those (along with the epoch) to reconstruct
the original. It is now updated.

**Comment by titodalcanton** [comment]
I think I spotted a few leftover docstrings and exceptions still only mentioning .npy and .txt. Other than that, looks good to go.

**Comment by ahnitz** [comment]
Ok, I think I've tracked down the straggling docstrings

**Pull request merged**
