### PR TITLE
fix monte carlo sensitivity calculation for chirp distance distributions

### PR DESCRIPTION
**Pull request by tdent**
#27

### CODE REVIEW

**Comment by ahnitz** [comment]
Tom,

The changes look ok to this function, but you've added an argument, so I think calling codes will be broken by this. At the moment, the only one is pycbc_page_sensitivity. Could you make sure that it is updated to the new interface? If that isn't possible let me know.

**Comment by tdent** [comment]
OK, will do.  I think the help messages need a bit of editing as well: options can be assumed to be optional unless otherwise stated, and (especially) defaults should be explicitly shown so that people can predict the default behaviour

**Comment by tdent** [comment]
The code will crash if --bins isn't specified or there are fewer than 2 bin boundaries, won't it? 
I think it would be good to have a default behaviour of putting everything into 1 bin ..

**Comment by tdent** [comment]
Updated/rebased against recent changes to pycbc_page_sensitivity, any further comments or requests Alex?

**Comment by ahnitz** [comment]
Tom,

Ok, the changes look fine to me. 

For everyone,

Keep in mind  that this does change the arguments to the executable so if you've used the old 'method' option your ini file will need to change to reflect that.

**Comment by tdent** [comment]
Hi Alex - so about the .ini file(s), is there now / still a location for example files that we (hopefully) keep maintained which we should update for this?

**Comment by ahnitz** [comment]
I've gone ahead and updated it already, but there are ones here.

pycbc/workflow/ini_files/

**Pull request merged**
