### PR TITLE
Several changes to FFT infrastructure

### PR DESCRIPTION
**Pull request by josh-willis**
This pull request makes several changes to how FFTs are handled in PyCBC. The main changes are:
 
  * Always set a default backend (same as #2034, but for all schemes not just CPU)
  * Remove the caching of 'plans' and similar data structures in FFTW/MKL support. This means that plans will be re-generated for the function-based API; users wanting to amortize that overhead should instead used the class-based API
  * The options related to wisdom files are no longer performed as part of `fftw.from_cli`. This change allows that function to now occur anywhere within an executable, not just after entering a processing scheme context. So if specifying `--fft-backend mkl` users should see MKL used for all FFTs, not just those in the context block. This requires making explicit calls to the import wisdom functions (as was already the case for export) and has been changed for `pycbc_inspiral`, but no other executables.

### CODE REVIEW

**Comment by ahnitz** [comment]
@josh-willis I think the only other executable that should be updated is pycbc_live

**Comment by josh-willis** [comment]
@ahnitz Do you want the options to read in wisdom files in `pycbc_live`, or is that not used there? (that is, I can just move up where `fft.from_cli` is called, or I can also add the options to import wisdom files if they were given on the command line)

**Comment by ahnitz** [comment]
@josh-willis We need to retain the wisdom file reading in pycbc_live.

**Comment by josh-willis** [comment]
@ahnitz OK, I added that, and also a call to verify the FFT options (which hadn't been there before)

**Pull request merged**
