### PR TITLE
Code changes made to replace pycbc_splitbank with pycbc_hdf5_splitbank in pycbc_make_coinc_search_workflow 

### PR DESCRIPTION
**Pull request by soumide1102**
This PR is about replacing `pycbc_splitbank` with `pycbc_hdf5_splitbank` while running `pycbc_coinc_search_workflow` . I have tested these changes applied to pycbc-v1.5.10 in a workflow run on O1 Analysis 3 data using ER10 settings, the results page for which can be found here : https://sugwg-jobs.phy.syr.edu/~soumi.de/ER10/testWorkflow/test-hdf5-splitbank-o1-analysis-3-er10-settings-v1510-rerun/ .

To run this, I had changed `splitbank = ${which:pycbc_splitbank}` to `splitbank = ${which:pycbc_hdf5_splitbank}` in the `executables` section of the `ER10/pipeline/executables.ini` file. So I have made a PR in pycbc-config to include that https://code.pycbc.phy.syr.edu/ligo-cbc/pycbc-config/commit/572c888d7506613390a78f04620b249537a2dfd9 .

### CODE REVIEW

**Comment by cdcapano** [comment]
It looks good to me. Am I right in understanding that this change will disable xml banks entirely in the workflow (aside from the input)? In other words, this isn't just putting in the option to use the hdfbank files, this is making it permanent? If so, I'm fine with that, but I defer to @ahnitz and @spxiwh.

**Comment by ahnitz** [comment]
Soumi, I am happy with this as well.

**Comment by soumide1102** [comment]
@cdcapano Yes, that right. This *isn't* introducing an option to use xml or hdf banks, but is removing the use of xml banks completely in the workflow, except the input xml bank, as you said.

**Comment by duncan-brown** [comment]
@cdcapano @spxiwh I think it's reasonable to do that, as we just convert the bank to HDF5 anyway for most parts of the code.

@cdcapano do you want to go ahead and merge?

**Comment by a-r-williamson** [comment]
Hi all,

This change passed under my radar, so apologies for not speaking up earlier, but this breaks the GRB workflow currently. We will of course be moving over to hdf5 in the near future, but I would like to add back the functionality to still use pycbc_splitbank in a workflow.

Andrew

**Comment by duncan-brown** [comment]
@a-r-williamson please can you propose a patch that would allow this? It might be good to have some discussion in a Wednesday PyCBC call.

**Comment by soumide1102** [comment]
Hi @a-r-williamson The `pycbc_hdf5_splitbank` has been introduced in pycbc-v1.6.0 . So you should be able to use `pycbc_splitbank` if you use pycbc-v1.5.10 or any other version of the v1.5 series.

- Soumi

**Comment by a-r-williamson** [comment]
@duncan-brown 

Proposed patch is ligo-cbc/pycbc#1321

**Pull request merged**
