### PR TITLE
Fix error in Travis lalsuite update, update lalsuite for Docker images

### PR DESCRIPTION
**Pull request by titodalcanton**
Stupid mistake.

While I am at it, how about also updating the lalsuite hash for Docker images?

### CODE REVIEW

**Comment by ahnitz** [comment]
@titodalcanton Yeah, let's update the docker build too.

**Comment by titodalcanton** [comment]
Huh?
```
Collecting psycopg2==2.6 (from pegasus-wms==4.7.5)
  Using cached psycopg2-2.6.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    Error: could not determine PostgreSQL version from '10.1'
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-GCmOhV/psycopg2/
```
This does not seem related to the lalsuite change, and I found this: https://github.com/psycopg/psycopg2/issues/594. What is requiring psycopg2 2.6 exactly? I do not see it in CVMFS releases and it does not appear to be an explicit pegasus requirement. Also, where is PostgreSQL 10.1 coming from? Especially since it was released a month ago only…

**Comment by titodalcanton** [comment]
Ok, psycopg2 2.6 is indeed explicitly required in pegasus' `setup.py` (even in the latest version 4.8.0) but *only* if `pg_config` is available… So I guess a way forward is making sure it is not installed ;)

**Comment by titodalcanton** [comment]
Hacky workaround, but seems to work. Hopefully the next pegasus release will bump the psycopg2 requirement to 2.7.

**Pull request merged**
