### PR TITLE
removed OPENCL import

### PR DESCRIPTION
**Pull request by SebastianKhan-LIGO**
Importing OPENCL faithsim calculation to fail.
I talk to Ian and he said to remove the OPENCL import
which worked.

### CODE REVIEW

**Comment by SebastianKhan-LIGO** [comment]
I think I had cloned the pycbc version 1.0.0 in my attempts to get pycbc to work which is why Alex's commit is there. The final commit fixes the version and release text to be what's on master currently.
Sorry about that

**Comment by spxiwh** [comment]
Hi Seb,

Can you rebase against the current master so that there is only one commit .... It seems a bit weird a revert a bunch of stuff, and then put it back, for a one-line change.

**Comment by SebastianKhan-LIGO** [comment]
I have done git stash and then git rebase... should I close this pull request then open a new one?

**Comment by spxiwh** [comment]
I think you would need to do:

git rebase origin/master

**Comment by SebastianKhan-LIGO** [comment]
I did that and it says 'current branch master is up to date'..

**Comment by josh-willis** [comment]
You issue the 'git rebase origin/master' command while you have checked out whichever feature branch has your proposed change on it, not while you have master checkout out.  Is that what you did?

On Jul 8, 2015, at 2:11 PM, SebastianKhan-LIGO wrote:

> I did that and it says 'current branch master is up to date'..
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--
Josh Willis

Associate Professor 				Email:	josh.willis@acu.edu
of Engineering & Physics		

Abilene Christian University		Phone:	(325) 674-2527
Box 27963                                		Fax:		(325) 674-2146
Abilene, TX 79699-7963			Dept:	(325) 674-2165

Foster Science Building Room 317

**Comment by SebastianKhan-LIGO** [comment]
Created new pull request to remove unnecessary commits: https://github.com/ligo-cbc/pycbc/pull/147

**Pull request closed without merging**
