### PR TITLE
add pycbc-pyla and pycbc-glue as dependence

### PR DESCRIPTION
**Pull request by ahnitz**
Add pycbc-pylal as an install depency to pycbc. This should make it so python setup.py install will download pycbc-pylal and auto install it. At the moment, this sets it to pull the master version. If a tag is available, perhaps we should point to that?

### CODE REVIEW

**Comment by ahnitz** [comment]
depends on https://github.com/ligo-cbc/pycbc-pylal/pull/2

**Comment by ahnitz** [comment]
If possible, I would like more people to test this, and make sure this works. After this patch, pycbc-pylal should be automatically installed.

**Comment by ahnitz** [comment]
I've updated this to add both pycbc-glue and pycbc-pylal as dependencies. The initial versions are also now uploaded to PyPI, so they should resolve. Please let me know if this patch works.

**Comment by spxiwh** [comment]
Hi Alex,

I just did the following test:

 * Install lalsuite master (no glue or pylal)
 * Set my PYTHONPATH  to ""
 * Install pycbc from this commit

This seemed to install everything correctly, I still get the error "TypeError: 'NoneType' object is not callable" Tom reported on list, but this doesn't seem to cause any problems. I think this can be merged.

Cheers
Ian

**Comment by ahnitz** [comment]
Ok, great. Thank you Ian. If there are any other issues, I'm not sure they'll shake out until people test it themselves, but hopefully it will just work for most people.

**Pull request merged**
