### PR TITLE
Distributions examples for Documentation

### PR DESCRIPTION
**Pull request by stevereyes01**
I'm adding 2 example codes for using some of the distributions from distributions.py

They make the following 3 plots:
https://sugwg-jobs.phy.syr.edu/~steven.reyes/ER10/distributionExamples/massDistr.png

https://sugwg-jobs.phy.syr.edu/~steven.reyes/ER10/distributionExamples/spinDistr.png

https://sugwg-jobs.phy.syr.edu/~steven.reyes/ER10/distributionExamples/spinSpatialDistr.png

Don't merge this yet, since I think we should fix the issue of Gaussian and Uniform Distributions not working the same. I could take a uniform distribution, `foo['mass1']` to get a numpy array of floats of all of the mass1 parameters, but when I tried this for the gaussian distribution `foo['mass2']` it returned an error:

```
Traceback (most recent call last):
  File "massExamples.py", line 27, in <module>
    print mass2_samples['mass2']
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

Plus the documentation isn't very great yet anyway, so this is just a placeholder for if I get it to look nice at all.

### CODE REVIEW

**Comment by cmbiwer** [comment]
Hey Steven, its nice that you're working on this!

I see you're still working on it but please avoid CamelCase, eg. change ``spinSpatialDistrExample.py`` to ``spin_spatial_distr_example.py``.

**Comment by stevereyes01** [comment]
Codacy is complaining that there's two cases of trailing whitespace, but I can't find them in the code that I'm trying to submit.

It's also complaining that I'm not using `from mpl_toolkits.mplot3d import Axes3D`, but that's how the 3d plot above is being made. If I comment that line out, the code won't run.

**Comment by cmbiwer** [comment]
Steven what's the status of this?

**Comment by stevereyes01** [comment]
Hey Chris, I basically haven't touched it since November, I'll work on resurrecting it though. Thanks for asking.

**Comment by cmbiwer** [comment]
Just so you know Steven, sometime in the next few days ``pycbc.inference.distributions`` will be changed to ``pycbc.distributions``. You'll need to update this if this documentation is not merged before then. If you merge it beforehand, I'll update it myself.

**Comment by stevereyes01** [comment]
Messed up the branch. Gonna close and re-open it later.

**Pull request closed without merging**
