### PR TITLE
Recovery hist

### PR DESCRIPTION
**Pull request by tdent**
Do some improvements on the parameter recovery plot and first work towards getting injection-restricted rate results, i.e. plot to look at the distribution of templates a given inj run is recovered in

### CODE REVIEW

**Comment by tdent** [comment]
Hi Ian, the code quality complaint about the lambda function is bogus because I need the lambda to do the numpy vectorize.  The other complaint is about "continuation line unaligned for hanging indent" which I don't understand or know exactly how to fix (3 iterations so far on this).  Is it saying that because I've put the dict keys on separate lines with a 2-space indentation I'm not allowed to use any further indentation for readability?  Seems to be very arbitrary given that *the 3 previous dict items* also use further indentation.  (But they have brackets, so maybe that makes it thinks that is OK??)

**Comment by spxiwh** [comment]
I think there's python style guides that describe this better than me. I think line-continuation indentations (like this) should be 4 or 8 extra spaces (which this is not), or lined up with brackets. Try removing two spaces.

Codacy is right about the lambda function:
```
In [4]: pycbc.detector.Detector('H1')
Out[4]: <pycbc.detector.Detector at 0x7f32b0159690>

In [5]: det = pycbc.detector.Detector('H1')

In [6]: td = numpy.vectorize(det.time_delay_from_earth_center)

In [7]: td([1.2,1.3], [1.2,1.3], [10,11])
Out[7]: array([-0.01491573, -0.01484732])
```

**Comment by tdent** [comment]
I thought I tried it without the lambda function and I got an error.  Oh well, have to try again. 
BTW I haven't seen any written guidance saying continuation indents should have a multiple of 4 spaces, quite the reverse.  I HAVE read the style guides.  They say 'readability first'. 
And guess why I don't contribute so much code these days ...

**Comment by spxiwh** [comment]
This is already approved, so you can merge this when you're happy. I'm not going to enforce the unindentation thing, but when done badly it can be unreadable, which is why there are guidelines, but the main thing that is enforced is readibility is more important than the guidelines.

The lambda thing seems to me to be unnecessary code, I would remove that as codacy suggests, but I leave both of these things to your discretion.

**Pull request merged**
