### PR TITLE
Banksim asym mchirp window

### PR DESCRIPTION
**Pull request by alex-nielsen**
adding functionality to do asymmetric mchirp_windows in both pycbc_banksim and pycbc_make_banksim

### CODE REVIEW

**Comment by duncan-brown** [comment]
Do we need this for validating the ER8 banks? If so, please add the O1 Critical Milestone.

**Comment by alex-nielsen** [comment]
Stuff will work without it, but the banksims will be faster and more efficient with it.

**Comment by duncan-brown** [comment]
If @cdcapano can't get to it today, I will look and merge.

**Comment by spxiwh** [comment]
Hi Alex,

Why not use (in the option parsing) 
```
nargs="+", type=float
```
and allow either 1 or 2 arguments. If 1 argument behave as before, if 2 do upper and lower as you are doing it. The optparse->argparse change makes things like this easier, so we shouldn't really be having option parsing in the executables.

**Comment by cdcapano** [comment]
Sorry for not looking at this yesterday, was busy with wedding stuff.

Alex, it looks fine to me. Before I merge, can you indicate whether or not you've tested it? I want to make sure that the change to make_banksim is doing the right thing.

Ian, yes, switching banksim over to using ArgumentParser would be the correct thing to do, but at this point I think we just want something that works, even if it isn't pretty. Nitz and I are planning to come back to banksim and fix it up at some point, probably after the end of O1.

**Comment by alex-nielsen** [comment]
I've tested that it works. The banksim for the BBHabove20 was run with 0.5,1.0, see here;
https://atlas3.atlas.aei.uni-hannover.de/~alex.nielsen/LSC/Banksims/aligned_spin_banks/Uberbank/ER8/BBHabove20/recoveredparams.png
Notice that there are a couple of points right on 50% below mchirp.

**Comment by spxiwh** [comment]
Hi guys. The change I suggested is only minor. The code already uses argparse, I just suggest a change to how the option is provided.

**Comment by cdcapano** [comment]
HI Ian, whoops, you're right. I saw OptionParser in make_banksim and was thinking it was in pycbc_banksim. Eh, so, sure, if Alex wants to switch to using nargs='+', he can. Does it really matter? Parsing a comma separated string doesn't seem terrible to me.

**Comment by cdcapano** [comment]
Ok, since Alex's current version works now, I'm just merging. We can revisit making the syntax better later.

**Pull request merged**
