### PR TITLE
Split calculation of optimal SNR over multiple cores

### PR DESCRIPTION
**Pull request by titodalcanton**
Adds a `--cores` argument which defaults to 1.

### CODE REVIEW

**Comment by duncan-brown** [comment]
@titodalcanton I think you also need similar code in the workflow to the PSD estimation code to set the number of cores requested. This patch will run the code on multiple cores, but only one core is requested from condor:
```shell
(pycbc-dev)[dbrown@sugar analysis2-parallel-optsnr]$ condor_q -long 26677284.0 | egrep -i (request|cores)
RequestCpus = 1
Arguments = "-n optimal_snr-BNS01_INJ-H1L1_ID235 -N ID0053339 -R local -L main -T 2015-10-19T19:07:33-04:00 /home/dbrown/projects/aligo/o1/analysis2-parallel-optsnr/output/work/main_ID0000001/optimal_snr-BNS01_INJ-H1L1_ID235 --snr-columns H1:alpha1 L1:alpha2 --sample-rate 16384 --cores 6 --input-file HL-INJECTIONS_BNS01_INJ-1127271617-1027800.xml --time-varying-psds L1-MERGE_PSDS-1127271617-1027800.hdf H1-MERGE_PSDS-1127271617-1027800.hdf --output-file H1L1-OPTIMAL_SNR_BNS01_INJ-1127271617-1027800.xml"
```

**Comment by ahnitz** [comment]
Duncan,

This is a configuration file change.

[pegasus_profile-optimal_snr]
request_cpus = XXX

**Comment by duncan-brown** [comment]
Got it.

**Comment by ahnitz** [comment]
Ok, I'm tired. This is the right syntax.

[pegasus_profile-calculate_psd]
condor|request_cpus = ${calculate_psd|cores}

**Pull request merged**
