### PR TITLE
Update inference unit test to run samplers

### PR DESCRIPTION
**Pull request by cmbiwer**
This PR updates ``test/test_inference.py`` which contains the unit test for the inference subpackage. Currently, it only initializes the likelihood evaluator class. I've expanded it to run each sampler for 4 iterations.

I've only included the CBC waveform generator, however, I've left it open to adding the ringdown waveform generator as well (if someone else wants to in a future PR). You would just need to append ``TestSamplers.likelihood_evals`` with your likelihood evaluator class that uses ringdown waveforms, and probably include your priors in the ``get_prior_evaluator`` function.

This includes two other changes as well. In ``sampler_kombine`` I added a check that if ``pool is None`` then ``process=1``. And in ``emcee`` it checks the output of the prior returned for if its either a float or array.

Just a quick explanation of this file. ``TestSamplers`` is the test class. The functions ``get_cbc_fdomain_generator``, ``get_prior_evaluator``, ``get_likelihood_evaluator``, and ``get_cbc_fdomain_likelihood_evaluator`` are helper functions for setting up the sampler class. And the ``test_samplers`` functions actually runs the unit test.

I believe this should catch any pickling problems with the samplers at the time of the PR now. Hopefully, this can be expanded even more.

Also provides a somewhat nice example (if you're willing to untangle the helper functions) of how to use these classes which is nice.

### CODE REVIEW

**Comment by duncan-brown** [comment]
@cmbiwer this branch will need to be rebased to master for Travis to complete. See https://github.com/ligo-cbc/pycbc/issues/1758

**Comment by cmbiwer** [comment]
I rebased but looks like its getting a different dtype returned in one of the functions. I'll have to take a look.

**Comment by cmbiwer** [comment]
Took a look, seems a dtype was missing after I rebased. Pushed the fix. Once checks pass I'll merge.

**Comment by cmbiwer** [comment]
Seems to be an issue linking numpy with openblas. Don't merge yet.

**Comment by cmbiwer** [comment]
Note for myself so I don't forget: problem with openblas was kombine looks for it in set directories however it does not look where Debian installs it (though it does look where RH/yum would install it so that's why I didn't see this problem before). Ben removed harcoded path checking bit in 0.8.2. Upgrade the requirements for pycbc here and seeing if this fixes it. Will check again later.

**Comment by cmbiwer** [comment]
Unit tests passed!

**Pull request merged**
