### PR TITLE
added IMRPhenomD peak frequency support

### PR DESCRIPTION
**Pull request by SebastianKhan-LIGO**
This PR adds support to the pnutils.get_freq() function
for a new function in LALSimulation master which
returns the frequency of the peak fourier domain amplitude
for the IMRPhenomD model.

There is something a little weird going on though. The first time I evaluate the function I get
a RuntimeWarning error, I've pasted an example below.
But all evaluations afterwards do not throw an error.

I would prefer to not have this error before merging this, so does anyone have any ideas?

Thanks!

In [3]: pnutils.get_freq("fIMRPhenomDPeak", 10, 10, 0, 0)
/Users/sebastian/git/lscsoft/pycbc-dev/lib/python2.7/site-packages/numpy/lib/function_base.py:1880: RuntimeWarning: divide by zero encountered in _get_freq (vectorized)
  outputs = ufunc(*inputs)
Out[3]: array(792.19642924046)

### CODE REVIEW

**Comment by SebastianKhan-LIGO** [comment]
@spxiwh Hi Ian, could you take a look at this? Thanks!

**Comment by spxiwh** [comment]
Hi Seb, I have no issue with the code, but you said you were worried about the divide by zero. Did you figure out what was going on? It seems to be coming from within Phenom code, but I'm a little confused about where this could come from! Maybe try this with vectors as input?

**Comment by SebastianKhan-LIGO** [comment]
If I call the lalsimulation function "IMRPhenomDGetPeakFreq" through python I don't get this error.

If by vector inputs you mean m1 = [10] , m2 = [10] , etc... I get the following

In [7]: pnutils.get_freq('fIMRPhenomDPeak', m1[0], m2[0], s1[0], s2[0])
/Users/sebastian/git/lscsoft/pycbc-dev/lib/python2.7/site-packages/numpy/lib/function_base.py:1880: RuntimeWarning: divide by zero encountered in _get_freq (vectorized)
  outputs = ufunc(*inputs)
Out[7]: array(792.19642924046)

**Comment by spxiwh** [comment]
No I mean:
```
pnutils.get_freq('fIMRPhenomDPeak', numpy.array([10,15]), numpy.array([10,12]), numpy.array([0,0]), numpy.array([0,0]))
```

**Comment by SebastianKhan-LIGO** [comment]
Running that code still initially produces the same error

**Comment by SebastianKhan-LIGO** [comment]
Thanks for taking this pull request upon Ian.

I'm still not sure how this error comes about...
Is there anyone else who might know a solution?

**Comment by spxiwh** [comment]
I figured it is easiest to merge this as it won't break anything. Please try to figure out what is going on though!

**Comment by SebastianKhan-LIGO** [comment]
Thanks Ian, I'll try and figure it out.

**Pull request merged**
