### PR TITLE
shorter column names for better formatting

### PR DESCRIPTION
**Pull request by duncan-brown**

### CODE REVIEW

**Comment by ahnitz** [comment]
Sorry, we can't just let people self approve these. In any case, I approve this change. I would have done it this way to start with if I had known html better. Please push when you feel ready.

**Comment by duncan-brown** [comment]
@ahnitz i assigned to to me as i'm running a test workflow. I was going to bounce it to you once the test is complete.

**Comment by duncan-brown** [comment]
Testing at https://sugar-dev3.phy.syr.edu/pegasus/u/dbrown/r/183/w?wf_uuid=715f8198-775f-473b-8210-10476ba7d54e

**Comment by ahnitz** [comment]
Ok, sorry. I see now that you had only just posted it. That makes sense.

**Comment by duncan-brown** [comment]
Looks good: https://sugar-jobs.phy.syr.edu/~dbrown/workflow-test/workflow-test-8/7._open_box_result/7.02_loudest_event_followup/

@ahnitz please can you merge?

**Pull request merged**
