### PR TITLE
Update pycbc.inference documentation

### PR DESCRIPTION
**Pull request by cmbiwer**
This updates the ``pycbc.inference`` documentation page examples and adds an example how to read real data and how to use ``pycbc_inference_plot_posterior``.

Trying to address a number of things that RIT @a-r-williamson brought up last week.

@stevereyes01 can you take a look at this page as well and if something doesn't make sense them let me know.

Afterwards I'll probably end up assigning this to @cdcapano once @stevereyes01 has given me some feedback.

An example of the rendered documentation is here: https://sugwg-jobs.phy.syr.edu/~cbiwer/docs/inference.html

### CODE REVIEW

**Comment by ahnitz** [comment]
This page doesn't seem right. Also you don't seem to have committed a distributions.rst file.

**Comment by stevereyes01** [comment]
@cmbiwer I'll have a look over this, sorry I just saw this today.

**Comment by stevereyes01** [comment]
One minor comment, there's still that nagging line:
`fp = InferenceFile("cbc_example-n1e4.hdf.hdf", "r")`

Other than that, I think it looks good at my first pass over it.

If you think it would help, it may not hurt to put some examples of the plots referenced in this documentation. I've seen a bunch of them before, so I don't think I would need to see them. I'll leave that to your discretion.

**Comment by cdcapano** [comment]
@cmbiwer Just want to say, I like that you have the suggested options to be the skip-burn-in. People keep asking me about how long it's supposed to take before they can see results because they have kombine's burn-in turned on, and I keep telling them to turn that off. I was going to file a PR to change that in the docs, but then saw you had already addressed it.

**Comment by cmbiwer** [comment]
I've corrected the typo that Steven pointed out. But Steven please take a closer look at this documentation. You should understand everything on the page.

**Comment by ahnitz** [comment]
@cmbiwer Have you fixed the generation of this page? https://sugwg-jobs.phy.syr.edu/~cbiwer/docs/distributions.html

**Comment by cmbiwer** [comment]
I've fixed the issues with the distributions documentation page: https://sugwg-jobs.phy.syr.edu/~cbiwer/docs/distributions.html

I'll assign this to @duncan-brown for now but @stevereyes01 and @cdcapano I'll make an issue and if you want me to make other changes please make those requests in the issue.

**Comment by cmbiwer** [comment]
Landscape problem is a landscape Server Error.

**Pull request merged**
