### PR TITLE
move statistic classes from pycbc_coinc_findtrigs into the library

### PR DESCRIPTION
**Pull request by ahnitz**
Also, add some basic documentation to the classes!

### CODE REVIEW

**Comment by spxiwh** [comment]
Hey Alex,

Both QuantifiedCode and Landscape are reporting things that should be looked at, even though both tests pass.

**Comment by ahnitz** [comment]
Ok... I can go through again. They mostly seemed silly to me (such as no emptry lines with 4 spaces in the documentation). Is there something in there that you actually cared about?

**Comment by spxiwh** [comment]
Yes. Landscape reported a few new "smells" (unused variables, overriding builtins) that should be fixed. The QuantifiedCode points out that a few things would be better as static methods (and that we should use .format for string formatting.

**Comment by ahnitz** [comment]
Ian,

I've done the best I can. The remaining flags items are ones I do not feel need to be addressed. In this case, it is flagging unused variables (and recommending static methods) for methods that need a uniform interface. Not all implementations of a stat class need to use all the potential input, but some may. I don't know of a cleaner solution to this.

**Comment by spxiwh** [comment]
Okay, merging this now.

My concern would be that locking in "slide" and "step" as mandatory options for all coinc classes makes it difficult to add a class that might use some other parameter (a crappy example: the H1-H2 effective distance cut parameter used in S5). Maybe it would be better to supply these variables in a params dictionary (or similar) .... This wouldn't cause CodeQuality to stop complaining about unused variables, but might be more future-proof.

**Pull request merged**
