### PR TITLE
Move window dependance out of constructor

### PR DESCRIPTION
**Pull request by lppekows**
Now that we allow clustering over template-dependant windows we don't know the window length when the CUDAThresholdCluster object is constructed.  This patch moves the impacted code from the constructor to the threshold_and_cluster method, which already accepted a window argument.  Fortunately it looks like someone already anticipated this as get_tkernel caches its results :)

### CODE REVIEW

**Comment by ahnitz** [comment]
This looks fine to me Larne. Now that the cpu cluster has a window option this makes the method more in line with the original GPU implementation, which is why there was already caching for the functions.

**Comment by ahnitz** [comment]
While the code change visually looks Ok, have you had a chance to make sure that it at least runs? If so I am happy for this to be merged.

**Comment by lppekows** [comment]
Yes, I've confirmed this runs on spice-dev5 and the results from a small template bank are sane.

**Comment by ahnitz** [comment]
Ok, great! Then approved.

**Pull request merged**
