### PR TITLE
Add KL divergence module.

### PR DESCRIPTION
**Pull request by cmbiwer**
Adds KL divergence convenience function for ``numpy.array`` of samples or ``numpy.array`` of PDF values.

Example:
```
from pycbc import distributions
from pycbc.inference import kl
nsamples = 100000
parameter = "distance"
min_val = 0
max_val = 1000
dist1 = distributions.distribs["gaussian"](distance=(min_val, max_val),
                                           distance_mean=500,
                                           distance_var=300**2)
dist2 = distributions.distribs["gaussian"](distance=(min_val, max_val),
                                           distance_mean=500,
                                           distance_var=300**2)
samples1 = dist1.rvs(nsamples)[parameter]
samples2 = dist2.rvs(nsamples)[parameter]
print kl.kl(samples1, samples2,
            bins=100, hist_min=min_val, hist_max=max_val)
```

Would like to use this in a unit test (add unit test in another PR) that compares our ``Distribution.rvs`` and ``Distributions.pdf`` functions for consistency with some threshold on the KL divergence. This could finds its way into other analysis perhaps as well.

### CODE REVIEW

**Comment by cdcapano** [comment]
@cmbiwer Thanks for putting this together. Few requests: could you call the module something more general than 'kl.py', maybe 'entropy.py'? I think we'll want to add some other functions eventually that can calculate JS divergence (Miriam has been calculating this), entropy, etc. All those things should probably live in the same module.

Also, for the calculation of the KL divergence, if the samples are drawn from the p distribution, `(log2(p) - log2(q)).mean()` (and `.std()/len(q)**0.5` for the error); i.e., a Monte Carlo integration. Here, `p` and `q` are pdf values.

**Comment by cmbiwer** [comment]
>>> Also, for the calculation of the KL divergence, if the samples are drawn from the p distribution, (log2(p) - log2(q)).mean() (and .std()/len(q)**0.5 for the error); i.e., a Monte Carlo integration. Here, p and q are pdf values.

It isn't very clear what you're trying to say here - are you asking for a code change?

**Comment by soumide1102** [comment]
Everything looks good to me. I can approve this after @cdcapano explains if he wants changes.

**Comment by cmbiwer** [comment]
@cdcapano I've renamed the module to ``entropy.py``. If you wanted another change, I need a bit more of an explanation.

**Pull request merged**
