### PR TITLE
Add ringdown configuration file to inference documentation

### PR DESCRIPTION
**Pull request by micamu**
Add an example of an ini file for ringdown parameter estimation

### CODE REVIEW

**Comment by cmbiwer** [comment]
I think this needs to be rebased, landscape is picking up a lot of changes that have nothing to do with this PR.

**Comment by micamu** [comment]
I had pulled before creating this branch, and when rebasing it just tells me that the current branch is up to date. I don't know why it is not picking up #978. I'll try again after lunch.

**Comment by ahnitz** [comment]
Miriam, did you remember to git fetch origin (or whatever you've called the
ligo-cbc github remote) before rebasing from that remote?

On Tue, Jul 12, 2016 at 6:40 PM, micamu <notifications@github.com> wrote:

> I had pulled before creating this branch, and when rebasing it just tells
> me that the current branch is up to date. I don't know why it is not
> picking up #978 <https://github.com/ligo-cbc/pycbc/pull/978>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ligo-cbc/pycbc/pull/980#issuecomment-232103919>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ACGrRkKELDPb5m7mW-qKEEmj1WkaCtV7ks5qU8NsgaJpZM4JKgQZ>
> .
>



-- 
Dr. Alexander Nitz
Max Planck Institute for Gravitational Physics (Albert Einstein Institute)
Callinstrasse 38
D-30167 Hannover,  Germany
Tel: +49 511 762-17097

**Comment by micamu** [comment]
Done

**Pull request merged**
