### PR TITLE
Fix issues with segment handling

### PR DESCRIPTION
**Pull request by titodalcanton**
* fromsegmentxml: make segment times of type lal.LIGOTimeGPS
* fromsegmentxml: fix apparently wrong logic for handling the id != None case (please check!)
* fromsegmentxml: cleanup code and arg names conflicting with Python keywords
* segments_to_file: fix potential ValueError due to multiple LIGOTimeGPS types

### CODE REVIEW

**Comment by spxiwh** [comment]
Hi Tito, thanks for doing this. We should not be using glue's LIGOTimeGPS class anywhere, the lal class should be used, and this should work with all the normal glue utility functions. Are there no other instances of this in PyCBC?  It would be better if for *all* PyCBC programs this class is made to point to the LAL version so that if any sub-functions use the glue type (for e.g. glue's datafind module)  it will actually see the LAL type. Not sure what the best way is to do that though.

.... Anyway, this patch is fine, the only thing I don't understand is why you cast to float in jobsetup.py. Why not cast to int? I am happy for this to be merged if you make this change or if you give a good reason why this needs to be a cast to float.

**Comment by titodalcanton** [comment]
Hi Ian, there are a few other places using the wrong LIGOTimeGPS:
* bin/gstlal/pycbc_pickle_horizon_distances
* bin/pycbc_inspinjfind
* bin/mvsc/pycbc_mvsc_get_features
For the last one I can ask Tom/Shasvath, but maybe you're the best one to comment on the first two.

I was wondering whether I should cast to int and truncate, or cast to float and have it round properly. I decided to go with the latter as that seemed more correct (round to the closest second). Since having a non-integer time is effectively an error, I guess the ideal behavior would be to assert that the nanosecond part is exactly zero (or the time is an int in the first place). But that requires some additional code, probably a function somewhere. Do you prefer this approach, or simply casting to int?

**Comment by spxiwh** [comment]
Hi Tito,

I don't have a strong preference on this, it just seemed weird to cast an integer to a float and then use %.0f to round. For the pycbc_inspiral command line it is true that a non-integer value is a failure, so if you want to check for that - if seg[1] != 0 - then that would be good.

For the other two codes you mention that I am responsible for, these are not currently in use, and I might attic these at some point.

Cheers
Ian

**Comment by titodalcanton** [comment]
Hi Ian, let me know if this looks better and I'll merge it.

**Comment by spxiwh** [comment]
Hi Tito,

Thanks, I am happy for this to be merged.

Cheers
Ian

**Pull request merged**
