### PR TITLE
add option to get frame from datafind

### PR DESCRIPTION
**Pull request by ahnitz**
Add the option to get frame files through an internal datafind query. You provide the option frame-type instead of frame-cache or frame-files.

### CODE REVIEW

**Comment by spxiwh** [comment]
Hey Alex,

This looks good but can you add an option to pass a non-default datafind server to the frame_paths option .... In a future pegasus model we might conceivably want to query and pull frames from remote sites if not present at the local.

Also is there code duplication between here and the workflow.datafind module?

Cheers
Ian

**Comment by ahnitz** [comment]
On Fri, Jun 26, 2015 at 3:57 AM, spxiwh <notifications@github.com> wrote:

> Hey Alex,
>
> This looks good but can you add an option to pass a non-default datafind
> server to the frame_paths option .... In a future pegasus model we might
> conceivably want to query and pull frames from remote sites if not present
> at the local.
>
Good point. Ok, I'll add that option.

> Also is there code duplication between here and the workflow.datafind
> module?
>

I checked, and I don't think so. They share the datafind method and beyond
there really isn't much more than a single method call.

**Comment by spxiwh** [comment]
Hey Alex, I'm still waiting for this additional option before merging this. Did I miss something?

**Comment by ahnitz** [comment]
Ian,

No, you aren't missing anything. I haven't had time to add the additional feature, and it really isn't on my high priority list.

**Comment by spxiwh** [comment]
May as well merge this now and add the additional feature later.

**Pull request merged**
