### PR TITLE
Add utility to save conditioned strain in various formats

### PR DESCRIPTION
**Pull request by titodalcanton**

### CODE REVIEW

**Comment by ahnitz** [comment]
Is this in a state you want reviewed?

**Comment by titodalcanton** [comment]
Hi Alex,

I wanted to test it a bit more, which I did now. I also wanted other's opinion on the ability to save the strain in other formats, especially HDF5. I can put that bit in before merging if there are cases where it would be used.

**Comment by ahnitz** [comment]
I'd like the option to save as HDF. Then we can put this in the workflow as an optional intermediate step to reduce frame file size.

**Comment by titodalcanton** [comment]
This now supports all formats understood by TimeSeries.save(). It also allows one to save conditioned strain in single precision after scaling by the dynamic range factor. It could now be used as a preprocessing step for workflows with very large banks.

I also added a commit that compresses datasets in HDF files produced by {Array, TimeSeries, FrequencySeries}.save(). Without that change, conditioned strain saved in HDF is about twice larger than the same data in frame format. With compression enabled, HDF files are as large as frame files for double precision conditioned strain, and a bit smaller for single precision.

**Pull request merged**
