### PR TITLE
In InjectionSet.apply taper before project_wave

### PR DESCRIPTION
**Pull request by cmbiwer**
This PR tapers software injections in ``InjectionSet.apply`` before the call to ``project_wave``.

This way the call to LALSimulation inside ``project_wave`` that offsets the waveforms doesn't have to interpolation across a step since its already been tapered.

Image of waveform tapering with this PR: https://sugar-jobs.phy.syr.edu/~cbiwer/tmp/inject_fix_2_tapering_start.png

### CODE REVIEW

**Comment by cmbiwer** [comment]
One new comment because I noticed there was some cruft, ie. convert to lal ``TimeSeries`` then back to pycbc ``TimeSeries``.

**Comment by titodalcanton** [comment]
Hi Chris, why is this change needed? I think it may actually lead to distortion of the waveform in some cases: if you taper the two polarizations independently then the length of the tapered portion is not necessarily equal, which can cause some phase rotation. That's probably not a big error since it's just at the beginning, but I'd like to know why we need to do it that way.

**Comment by michal-was** [comment]
Hi Tito. On that aspect, if you taper after projection to detectors, then the tapering may be different in each detector, and the injection won't be coherent between detectors at the tapering. It's probably better to run the risk of having a wrong phase than inconsistent signals between detectors. It may be a not so small error, as tapering for inspiral only injections needs also to happen at the end of the waveform.

**Comment by titodalcanton** [comment]
Aha, that's a good point Michal.

**Pull request merged**
