### PR TITLE
io/hdf : allow SingleDetTriggers to continue without bank file

### PR DESCRIPTION
**Pull request by tdent**

### CODE REVIEW

**Comment by tdent** [comment]
Appears that Tito is out of action ATM

**Comment by spxiwh** [comment]
Hi Tom, I have a few issues with this.

 * If an argument is optional, it should be a key-word argument (this module disobeys this in a few places, I know!)
 * If the bank-file is optional, then things like class.mass1 should at least give a meaningful error message (ie. "Cannot access mass1 unless you give me a bank file".)

Making this a key-word argument would break a number of codes in production, so maybe we can hold off on that for now, but it would be good to have the sane error messages for mass1, mass2, spin1z, spin2x now.

**Comment by tdent** [comment]
Ian it's not optional, it's just allowed to be None.  I don't know of any style guidance that says that arguments that may be None *should* be kwargs.  The expectation is that a bank will be given to the class otherwise indeed some properties will fail, so I can look at the nicest way to flag that. 
Maybe one also should allow the class to be initialized without a bank and add it later ...

**Comment by tdent** [comment]
So the second commit is what this was intended for.  See e.g. 
https://atlas3.atlas.aei.uni-hannover.de/~tdent/LSC/o1/trigplots/gw150914_plots/L1-PLOT_HIST_SUMM_SNR_FULL_DATA_SPECIAL-1126051216-1220400.png

**Comment by tdent** [comment]
Any more requests before pushing this Ian?

**Pull request merged**
