### PR TITLE
Add script for plotting gated times

### PR DESCRIPTION
**Pull request by titodalcanton**
Example: https://sugar-jobs.phy.syr.edu/~tito/gated_times.html

Needs to be integrated into the workflow, opening for comments.

### CODE REVIEW

**Comment by ahnitz** [comment]
Tito, were you going to add it to the workflow in this pull request? Or are you waiting on me to approve this first? I think this is fine. Another place to have this kind of information though would be on the time series followup plot.

**Comment by titodalcanton** [comment]
Yes I'll add the workflow integration here.

**Comment by titodalcanton** [comment]
Testing, hold on on merging.

**Comment by titodalcanton** [comment]
Works, example here: https://atlas1.atlas.aei.uni-hannover.de/~tito/LSC/er8/er8b_c00_beyond_uberbank_update/1._analysis_time/1.2_gating/

**Comment by ahnitz** [comment]
Looks good. Thank you Tito for also updating the gating function documentation!

**Pull request merged**
