### PR TITLE
The functions lalsimulation.SimInspiralWaveformParamsInsertTidalLambd…

### PR DESCRIPTION
**Pull request by benjaminlackey**
…a1, lalsimulation.SimInspiralWaveformParamsInsertTidalLambda2, lalsimulation.SimInspiralWaveformParamsInsertdQuadMon1, lalsimulation.SimInspiralWaveformParamsInsertdQuadMon2 were misnamed. They are now corrected.

### CODE REVIEW

**Comment by ahnitz** [comment]
@spxiwh Ian, anything else?

**Comment by spxiwh** [comment]
Why is Travis not running? @ahnitz

**Comment by duncan-brown** [comment]
@spxiwh I turned travis off last week when AWS was down.

**Comment by duncan-brown** [comment]
Just turned it back on, but it needs a build cycle to enable it. It won't appear for this pull request.

**Pull request merged**
