### PR TITLE
Add hdf module in io package, update and clean up trig fitting code

### PR DESCRIPTION
**Pull request by tdent**
Same subject as always.  So this time - having 1) forced my local fork of master to be exactly identical with ligo-cbc master and 2) pushed that state to my fork on github, I just picked the commits I knew I wanted from my local branch onto my local fork of master and pushed that.  
My local branch in the current state seems to be entirely useless for the purpose of making pull requests since it seems (though I don't know how to diagnose why) it was not set up as was envisaged for this use case. 

This has taken me several hours longer than was necessary because the instructions - such as I could understand them from github.com and the cbc wiki page - were not explicit about how to create the branch concerning distinctions between upstream (ligo-cbc) vs. my fork, and between the local state of any branch vs. the state in the repository.  At least I didn't see anywhere that the topical branch should be created *directly from upstream/master*. 

Concerning the command 'git branch FEATURE upstream/master' is this sufficient for the case when other potentially conflicting changes could be made to upstream/master over the period when development is made on the FEATURE branch?  You said 'Github will state for example if the request actually cleanly applies to master' - what if it doesn't?

### CODE REVIEW

**Comment by ahnitz** [comment]
Hi Tom, 

I assume the pull request is now in a state you'd like me to look at. Comments shortly.

> Concerning the command 'git branch FEATURE upstream/master' is this sufficient for the case when other potentially conflicting changes could be made to upstream/master over the period when development is made on the FEATURE branch? You said 'Github will state for example if the request actually cleanly applies to master' - what if it doesn't?

You must then rebase from the current master and do a force push to this branch.

git fetch upstream
git rebase upstream/master 
# Resolve the issues
git push origin FEATURE -f

**Comment by ahnitz** [comment]
Woops, markup error. I didn't mean to make that a big title...

**Comment by ahnitz** [comment]
### pycbc/io/hdf.py

Please follow the numpydoc guidelines for documentation. For new code we should try to keep to this so we don't have so many places to fix later. This is required for the documentation pages to be generated properly. 

https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt

I think I understand the FileData class. Correct if I am wrong, but at the moment it is simply a convenience to apply a masking function, in the case where one would do so for many different columns. I'm not sure I understand much of a benefit of using this directly in the case of one file, but I do see that you are using it in the DataFromFiles class, which I think makes a lot of sense. I am ok with the general structure of these classes, with the following suggestions.

 - do not make an argument a keyword if it is not optional (as seen by raising an error), just make it a standard argument
 - do not use print statements in the code, if you want logging, use the logging module 

### pycbc/binpycbc_fit_sngl_trigs

 - Please do not use the 'template_hash' attribute that exists in the individual inspiral files. It is my fault for having no documentation, but I don't want people relying on this attribute existing into the future. It is used for internal bookkeeping,  which I'd like to keep the flexibility to remove or simplify in the future. Please use the 'template_id' column that exists in the full run trigger file (the ones named *MERGE*.hdf). If that doesn't work for you, please let me know and I'll have to think through your use case. 

The following aren't as critical, so if you don't have the time, I'd be willing to approve this pull request before the following are complete, but I think are necessary for production use.

 - please separate out the plotting functionality of this script into a separate one
 - avoid using '--plot-dir' type syntax and move a model of explicitly setting the output names

**Comment by tdent** [comment]
Hi Alex - I am aware of the standard numpy-like documentation convention, if the plan is to try and make all the hdf-related code use it then I can do this. 

The FileData apparatus is indeed mainly a memory-saving device for getting only subsets of data from files, either in the case of very large files or large numbers of small ones.  Maybe there is a more hdf-like way to do this but I wasn't aware of it if one wants to apply boolean conditions. 

I was testing the code on ANielsen's ER6 test run (before the order=-1 duration and SPA fixes) which at the time did not have the 'MERGE.hdf' files available because some jobs could not complete.  So I ran on the raw INSPIRAL .hdf files instead.  However, as you say this is not the final use case, I can swap out the 'template_hash' usage for template_id instead and see if it works on Tito's more recent runs which do have MERGE files.

The more pressing issue is how to apply vetoes to the triggers.  Should I look at e.g. the ReadByTemplate class?  Does a general purpose apply-vetoes function exist, is it worth writing one? 

As for the housekeeping of plotting codes, see if we can work out how this is going to fit in to a pipeline.  At the moment I am considering the following: 
 - one script which reads (vetoed, thresholded) single trigs, does fits and outputs a fits file (at the moment .txt, but not reason not to use .hdf) and optionally plots the fits vs. the trigger distributions 
 - the fits file is then read by the coinc code and used to construct the coinc statistic for all pairs of triggers template by template 
With a separate plotting script it would be:
 - one script which reads thresholded single trigs, does fits and outputs a fits file 
 - a plotting script which reads thresholded single trigs and the fits file and plots fits vs. trigs 
 - the coinc code reads the fits file. 
I don't particularly mind either way, it saves some dozens of lines of code not to have two separate scripts for fitting and plotting but you may want to separate analysis from plotting codes in the pipeline.

**Comment by ahnitz** [comment]
On Sun, Jun 14, 2015 at 9:51 AM, tdent <notifications@github.com> wrote:

> Hi Alex - I am aware of the standard numpy-like documentation convention,
> if the plan is to try and make all the hdf-related code use it then I can
> do this.
>
> The FileData apparatus is indeed mainly a memory-saving device for getting
> only subsets of data from files, either in the case of very large files or
> large numbers of small ones. Maybe there is a more hdf-like way to do this
> but I wasn't aware of it if one wants to apply boolean conditions.
>
Well you can directly apply boolean arrays to hdf5, but I'm not sure if
that helps you all that much. Across multiple files, you basically have to
do what you coded.

f = h5py.File('h1_sigls.hdf')

snr = f['H1/snr'][:] # read as numpy array, still have to be able to fit
one array into memory
mask = snr > 8   # need to be able to fit mask into memory

chisq = f['H1/chisq'][mask] # Only needs as much memory as the number of
points that survive the mask, this is handled directly by the hdf5 library

Note that only boolean masks are supported directly (without reading into a
numpy array).

So in principle you could get by with reading in two columns worth of data
and masking on the rest, but if that is too much memory, than you'll need
to do a partial read.  This can be done per template as seen in the
ReadByTempmlate class, but need not be. You can do a slice into the hdf5
vecotry, and only the slice is read into memory.

There are some example of this in the hdf5 documentation if you are
interested.
http://docs.h5py.org/en/latest/high/dataset.html


> I was testing the code on ANielsen's ER6 test run (before the order=-1
> duration and SPA fixes) which at the time did not have the 'MERGE.hdf'
> files available because some jobs could not complete. So I ran on the raw
> INSPIRAL .hdf files instead. However, as you say this is not the final use
> case, I can swap out the 'template_hash' usage for template_id instead and
> see if it works on Tito's more recent runs which do have MERGE files.
>
The more pressing issue is how to apply vetoes to the triggers. Should I
> look at e.g. the ReadByTemplate class? Does a general purpose apply-vetoes
> function exist, is it worth writing one
>
There are some utilities to help with applying vetoes here.

https://github.com/ligo-cbc/pycbc/blob/master/pycbc/events/veto.py#L210

In particular 'indices_outsides_segments' might do what you are interested
in, which is take a numpy array of end times and a list of segment xml
files to figure out which of the times are not within any of the 'veto'
segments. The results is an array of indices that survice, and the
segmentlist. If there is a more convenient form to take for your use, yes
we should add it.

**Comment by tdent** [comment]
Hi Alex - I just tried to update my local copies (forks? checkouts?) of master to get more recent changes and this seems to have broken things again.  Since my fork on github seems to have got a bunch of unwanted commits and/or in the wrong order, and I can't push the state of ligo-cbc master to it without getting a non-fast-forward error, I don't know how to proceed.

**Comment by tdent** [comment]
ok, push --force and putting the commits back seems to have kept this alive but I'd really prefer not to have this hanging round on my local master ... opened yet another request #66 from a hopefully correctly created topical branch from upstream/master

**Pull request closed without merging**
