### PR TITLE
switch pycbc_generate_hwinj over to multi-IFO option groups

### PR DESCRIPTION
**Pull request by cmbiwer**
This PR depends on #299.

This PR changes ``pycbc_generate_hwinj`` over to the multi-IFO option groups so that you can read in data for each IFO, eg. set ``--channel-name H1:${CHANNEL_NAME_H} L1:${CHANNEL_NAME_L}``, etc.

### CODE REVIEW

**Comment by cmbiwer** [comment]
I will fix the merge commits from appending PR #299 and post again once they have been resolved.

**Comment by tdent** [comment]
Hi Chris - please see the comments on #299 for the first commit. 
Otherwise I have tested this and it looks OK at first sight.  A couple more suggestions: 
 - since you want `--frame-type` and `--frame-files` to be alternatives to one another, the code should throw an error if they are both specified. 
 - don't use a hardcoded default upper frequency cutoff for calculating sigma, either use Nyquist (= 0.5*sample rate) or allow a command line option.  Hardcoding will always screw you in the end ..

**Comment by cmbiwer** [comment]
Hey Tom,

Fix the conflicts with #299. Yeah I made those two changes mention in the comments to #299 but for some reason github didn't remove the commit from this PR #300. Regardless, those changes have already been committed with #299 .

I've added the ``--psd-high-frequency-cutoff`` option, I agree we should remove hardcoded things. The default will be the nyquist frequency.

I've added the verify option group functions as well, that will check for consistency of the frame options as well as a slew of other things.

I've also removed the ``StrainSegment`` option group, it wasn't being used.

I've also expanded the ``pycbc_generate_hwinj`` instructions to include these new options.

Should be good to take a look now.

**Comment by tdent** [comment]
Looks OK, you might want to say explicitly in the high freq cutoff help message that the default will be sample rate / 2. 
Otherwise merge when ready.

**Comment by cmbiwer** [comment]
Updated the help message. Merged.

**Pull request merged**
