### PR TITLE
Fixes to handle no foreground/injection triggers

### PR DESCRIPTION
**Pull request by spxiwh**
Sometimes when running with a small bank for testing, you may end up with no foreground triggers, or no injection triggers. The code should handle this case gracefully.

The following patch fixes issues I found when trying to do this. I also remove some debugging lines in a few places. Example output page to follow.

### CODE REVIEW

**Comment by spxiwh** [comment]
Example page here:

https://galahad.aei.mpg.de/~spxiwh/LVC/ER8/analyses/uberbank/small_bank_run1/

**Comment by spxiwh** [comment]
Added one more fix to one of the plotting codes.

**Comment by ahnitz** [comment]
Hi Ian,

The changes look ok. I'm going to run with this patch on a test example, to make sure nothing else crops up. If that is ok, this can merge.

**Comment by ahnitz** [comment]
Ok, everything looks ok to me (no visible changes in result pages), and no failed jobs in my test case. 

https://sugar-jobs.phy.syr.edu/~ahnitz/projects/plots/a1/gw/html/

**Comment by ahnitz** [comment]
Ian, 

Can you verify for me which version of h5py you used. It seemed this didn't really solve the issue, as 2.5.0 can't set a zero length array. Do you have a later one, or something else?

**Comment by spxiwh** [comment]
In [3]: h5py?
Type:       module
String Form:<module 'h5py' from '/home/spxiwh/virtual_envs/pycbc_lalsuite_master/lib/python2.7/site-packages/h5py/__init__.pyc'>
File:       /home/spxiwh/virtual_envs/pycbc_lalsuite_master/lib/python2.7/site-packages/h5py/__init__.py
Docstring:
This is the h5py package, a Python interface to the HDF5
scientific data format.

Version 2.5.0

HDF5 1.8.12

**Comment by ahnitz** [comment]
Can you wite a zero length array to an hdf file is the better question. I'll post an example shortly

**Comment by ahnitz** [comment]
import h5py, numpy
f = h5py.File('test.hdf', 'w')
f['data'] = numpy.array([], dtype=numpy.float32)

**Comment by spxiwh** [comment]
```
In [1]: import h5py, numpy

In [2]: f = h5py.File('test.hdf', 'w')

In [3]: f['data'] = numpy.array([], dtype=numpy.float32)

In [4]: 
```

**Comment by spxiwh** [comment]
Is this maybe related to the underlying HDF version, not the version of h5py? I have 1.8.12 as shown above

**Comment by ahnitz** [comment]
Ok, sugar has 1.8.5 apparently

**Comment by spxiwh** [comment]
It looks like the debian machines have 1.8.12 and SL6 has 1.8.5 ....

**Comment by ahnitz** [comment]
Atlas has 1.8.12, and it also works fine. So this was fixed between then.

**Pull request merged**
